### ISSUE TITLE
undo problem

### ISSUE THREAD

**Issue by netjune** [joaotavora/yasnippet#1006]
I have not tried with 'emacs -Q'. I just tried with my emacs setting.

1. expand a snippet
2. in a snippet field, use company-mode to complete something
3. finish the snippet
4. undo
5. It seems that yasnippet is in an unexpected state.

**Comment by npostavs** [comment]
Could you elaborate a bit more? What does the snippet look like? What does "unexpected state" mean?

**Comment by netjune** [comment]
I made a screencast: http://www.vanweitech.com:3080/upload/yasnippet_undo.mp4

After the snippet finished, run the command undo, then the last field of the sippet is highlighted again, but don't known how to cancel the highlight.

**Comment by npostavs** [comment]
Yes, the snippet wasn't being restored properly. Should be fixed by #1008.

**Comment by netjune** [comment]
Thank you.

I tried the patch and see that, after undo, the cursor is at the beginning of the active field, not at the end of the field where it leaved from. This is not a big problem for me. It will be better if it is fixed.

**Comment by npostavs** [comment]
Hmm, I'm not sure if undo can remember cursor locations, but let me double check it.

**Comment by npostavs** [comment]
> if undo can remember cursor locations,

It can, but by the time we're recording the undo entry for the snippet, we've lost the original location. It wouldn't be impossible to fix this, but I'm going to leave it as it is for now.

**Comment by netjune** [comment]
OK. Thanks.
