### ISSUE TITLE
Extra parentheses with RefTeX

### ISSUE THREAD

**Issue by adamliter** [joaotavora/yasnippet#1007]
With the following snippet:

```
# -*- mode: snippet -*-
# name: textcite \textcite
# key: ct
# --
\textcite[$3]{${2:label$(unless yas-modified-p (reftex-citation 'dont-insert))}}$0
```

After looking up a citation label to insert using LaTeX, the output ends up being:

```
\textcite[]{(author2019)}
```

But the expected output is:

```
\textcite[]{author2019}
```

(See also this question on [TeX.SX](https://tex.stackexchange.com/q/136876/32888); note that the suggested answer does not seem to fix the problem.)

I was able to reproduce this issue with version 0.13.0 of yasnippet in an Emacs session started with `-Q`. Is this a bug? If not, is there something wrong with how the snippet is written?

**Comment by npostavs** [comment]
Does it work if you use `(car (reftext-citation 'dont-insert))`?

**Comment by adamliter** [comment]
@npostavs Thanks for the suggestion. That sort of works. It works when you're only inserting one entry with RefTeX, but if you're inserting multiple entries it doesn't work.

But based on your suggestion, this works as expected:

```
# -*- mode: snippet -*-
# name: textcite \textcite
# key: ct
# --
\textcite[$3]{${2:label$(unless yas-modified-p (mapconcat 'identity (reftex-citation 'dont-insert) ","))}}$0
```

So I think I'll go ahead and close this issue. Thanks for the suggestion!
