### ISSUE TITLE
Don't bind [C-c j] to command `yas-expand-from-keymap` in Org Mode

### ISSUE THREAD

**Issue by stardiviner** [joaotavora/yasnippet#1009]
In Org Mode, I found `[C-c j]` is bound to `yas-expand-from-keymap`. In other major modes like `emacs-lisp-mode` don't have this binding. I tracke down this into source code, seems related to `yas--direct-keymaps`. which auto generated local variable `yas--direct-org-mode`. When it is `t`, `[C-c j]` is bound. When I manually set it to `nil` locally `(setq-local yas--direct-org-mode nil)`. Then `[C-c j]` is unbound.

**Comment by npostavs** [comment]
I think this means you have some org-mode snippet which has a `#binding: C-c j` header.

**Comment by stardiviner** [comment]
Aha, I see. Thanks.
