### ISSUE TITLE
yas-auto-next inconsistent with $2

### ISSUE THREAD

**Issue by pksadiq** [joaotavora/yasnippet#1010]
`yas-auto-next` has a different behavior with the 2nd item expanded. When at $2, after the item is selected followed by a RET sets `point` to the beginning of the inserted text in $2, instead of going to $3 expansion.

Here is the snippet I tested:
```
# -*- mode: snippet; require-final-newline: nil -*-
# name: align...
# key: p.a
# --
${1:right$(yas-auto-next (yas-choose-value '("right" "left")))}
${2:right$(yas-auto-next (yas-choose-value '("right" "left")))}
${3:right$(yas-auto-next (yas-choose-value '("right" "left")))}$0
```

Thanks

**Comment by npostavs** [comment]
Right, thanks. Should be fixed by #1011.
