### ISSUE TITLE
Set default value for `yas-choose-value`

### ISSUE THREAD

**Issue by quazgar** [joaotavora/yasnippet#1016]
Is there a way to set a default value for `yas-choose-value`? If not, it would be great if that could be implemented, for example just taking the first or last one, or supplying an extra argument to `yas-choose-value`.

Example what I'm looking for:

```
# -*- mode: snippet; require-final-newline: nil -*-
# name: method
# key: m
# Here, "public" would be the default choice, which could be tabbed over
# --
${1:$$(yas-choose-value "public" '("public" "private"))} ${2:name}(${3:args}) {
            $0
}
```

**Comment by npostavs** [comment]
You can use `yas-completing-read` which does accept a default, but you can't "tab over it", you have to press `RET` to finish the call. Use `yas-auto-next` to avoid having to `RET` and `TAB`.

```
# -*- mode: snippet; require-final-newline: nil -*-
# name: method
# key: m
# Here, "public" would be the default choice, which could be tabbed over
# --
${1:$$(yas-auto-next (yas-completing-read "Visibility (public): " '("public" "private") nil nil nil nil "public"))} ${2:name}(${3:args}) {
            $0
}
```

**Comment by haqle314** [comment]
Since this is not exactly a rare use case, do you think something like this is useful? I can make a new pull request for it.
```
(defmacro yas-choose-value-final (&rest possibilities)
  "Like `yas-choose-value' but automatically jump to the next field."
  `(yas-auto-next (yas-choose-value ,@possibilities)))
```

**Comment by npostavs** [comment]
> `(defmacro yas-choose-value-final (&rest possibilities)`

This saves a pair of parens, but doesn't really seem worth it.
