### ISSUE TITLE
Possible regression for elisp evaluation in yasnippet

### ISSUE THREAD

**Issue by analyticd** [joaotavora/yasnippet#1022]
Upgraded yasnippet to latest in git repo instead of older package on melpa. This snippet:

```
# key: provide
# name: provide
# --
(provide '`(file-name-sans-extension (file-name-nondirectory (buffer-file-name)))`)
$0
```

used to work, but now blows up.

Is it a regression or should I be doing this differently?

**Comment by npostavs** [comment]
Works for me, can you reproduce this from `emacs -Q`?
