### ISSUE TITLE
snippets that just inserts text behave behave weridly when used inside other snippets

### ISSUE THREAD

**Issue by saheratarch** [joaotavora/yasnippet#1028]
>I have a snippets that makes me go into math-mode in latex $$ I can tab out of the dollar signs.
>I have a snippet that just inserts a 0
Now when I trigger a math-mode snippet and have a $$ and then trigger the zero snippet $0$ I have to press tab twice in order to get out of the dollar signs.
Why is that? How can I fix it so that I only need to tab twice

**Comment by npostavs** [comment]
I'm not sure I understand the scenario exactly. Are you asking for something like in #797?
