### ISSUE TITLE
question: how to use the hook executed after a snippet is completed

### ISSUE THREAD

**Issue by paaguti** [joaotavora/yasnippet#1029]
I would like to know how to use the ```yas-after-exit-snippet-hook```

I haven't found any example

Thanks a ton

**Comment by ChongQing520** [comment]
The semicolon ';' terminates an input expression in maxima-mode .

If you have a snippet like

``` elisp
copylist(${1: alist });$0
```

how can you use it in

``` elisp
car( copylist| )
```

**Comment by paaguti** [comment]
Just for others who may be wondering:

in any .emacs.d/<loaded>.el define the hook function. An example would be a function to reread the local variables from the local buffer:

```
(defun tex-set-local-vars ()
  "Set the local variables as set in the snippet"
  (interactive)
  (hack-local-variables nil))
```
and then include

```# expand-env: ((yas/after-exit-snippet-hook '(tex-set-local-vars)))```

in the snippet header.
