### ISSUE TITLE
Is there a way to have some snippets *always* active?

### ISSUE THREAD

**Issue by quazgar** [joaotavora/yasnippet#1030]
I'd like to see a way to have some snippets always active, at least whenever yasnippet is active.  Kind of like a parent for all modes.

## Use case ##

- Enter a copyright line or license header into a file.

**Comment by npostavs** [comment]
> Kind of like a parent for all modes.

Yes, `fundamental-mode` is this parent mode (see #949).

**Comment by quazgar** [comment]
Thank you very much!
