### ISSUE TITLE
[Question] How to remove group column from snippet table

### ISSUE THREAD

**Issue by WhatDothLife** [joaotavora/yasnippet#1034]
I want to remove the group column from the table that shows up after calling `yas-describe-tables`, because it's often empty and I don't need to see it. Since I display the buffer in a popup window at the right of my frame it takes up a lot of unnecessary space. How can I customize this property?

**Comment by npostavs** [comment]
It's not customizable at the moment, see `yas--describe-pretty-table`.

**Comment by WhatDothLife** [comment]
Ok, thanks. I'm looking forward to see this being implemented in the future.
