### ISSUE TITLE
Iteration on alist inside template

### ISSUE THREAD

**Issue by howdoicomputer** [joaotavora/yasnippet#1039]
Right now I have something along the lines of `(assoc-default 'size 5e-emacs-monster)` to take a value from an alist and populate its text.

However, I'd like to iterate over an array of alists in order to produce org mode entries. Is that possible?

**Comment by npostavs** [comment]
Yes, it should be possible with, e.g., `mapconcat`. Not entirely sure how the question relates to yasnippet though.
