### ISSUE TITLE
How to overwrite a snippet provided by a library?

### ISSUE THREAD

**Issue by tobiasBora** [joaotavora/yasnippet#1040]
Hello,

First, thanks for this great tool. However, I can't find a way to do the following: I installed the package `yasnippet-snippets` and I also created my own snippets. The thing is that I don't like the snippets `eq` (LaTeX mode) of `yasnippet-snippets` , and I'd prefer to overwrite it with mine. So I created a snippet `eq` but now when I press `eq<TAB>`, I have a prompt `Choose a snippet` asking me which snippet I'd like to use. I guess that sometimes it's nice to have this menu (for example when you have several possible default template for a file), but here I type `eq` so often that I don't want to always chose which snippet I need.

Can I define a priority number for the snippet, so that if a snippet 1 has priority greater than snippet 2 it is selected by default? Or if not can I hide some snippet installed from a library? (of course I don't want dirty `rm`)

Thanks!

**Comment by npostavs** [comment]
Did you give your `eq` snippet the same `#name:` value as the `yasnippet-snippets` provided one?

**Comment by zw963** [comment]
Yes, i think only different `name:` but same `key:`, will popup `Choose a snippet`.

**Comment by tobiasBora** [comment]
Oh sorry I don't know why, I missed your answers. Indeed, giving the same name solves the problem, thanks!
