### ISSUE TITLE
Snippet with elisp function causes yas--snippet-parse-create: Wrong type argument

### ISSUE THREAD

**Issue by Quintus** [joaotavora/yasnippet#1055]
Hi,

this snippet:

~~~~~
# -*- mode: snippet -*-
# name: Normale Karte
# key: nk
# --
* <<${1:`(foo)`}/${2:Nr}>> ${3:Zusammenfassung}

$0
~~~~~

where `foo` is defined as:

~~~~~ emacs-lisp
(defun foo ()
  (save-excursion
    (save-match-data
      (search-forward-regexp "[[abc _]]")
      (match-string 0))))
~~~~~

causes this error:

~~~~
yas--snippet-parse-create: Wrong type argument: char-or-string-p, ("[[abc _]]")
~~~~

Yasnippet 0.14.0, Emacs 26.1.

Is it a bug or is it me doing something wrong?

**Comment by npostavs** [comment]
Your search is failing to get a match. Due to a bug in yasnippet, you get a nonsensical error message in this situation. I also suspect you don't really mean to double the square brackets like that.

**Comment by Quintus** [comment]
Am 03. Juni 2020 um 19:49 Uhr -0700 schrieb Noam Postavsky:
>Your search is failing to get a match. Due to a bug in yasnippet, you
>get a nonsensical error message in this situation. I also suspect you
>don't really mean to double the square brackets like that.

Thanks for the hint. Of course, I did not mean to double them. This 
search was using a POSIX character class before and I appearently forgot 
to remove the corresponding brackets, thus doubling the brackets. I 
should really have seen that. Probably that error message did made me 
not see the forest for the trees, as we like to say in Germany... Thank 
you anyway.

This can then probably be closed.

-- 
Blog: https://mg.guelker.eu

**Comment by npostavs** [comment]
I've merged the fix for the error handling, and I'm closing the issue.
