### ISSUE TITLE
Condition seems to be loosely applied

### ISSUE THREAD

**Issue by tecosaur** [joaotavora/yasnippet#1065]
Hello!

I'm trying to set up some context-specific snippets using the following function:
```elisp
(defun +yas/org-src-header-p ()
  "Return non-nil if point is on a org src header, nil otherwise."
  (car
   (member
    (downcase
      (save-excursion
        (goto-char (line-beginning-position))
        (buffer-substring-no-properties
         (point)
         (or (ignore-errors
               (search-forward " " (line-end-position)))
             (1+ (point))))))
    '("#+property:" "#+begin_src" "#+header:"))))
```

Which I use like so:

```yas
# -*- mode: snippet -*-
# name: Header arg - eval
# key: v
# contition: (+yas/org-src-header-p)
# --
:eval `(ivy-read "Evaluate: " '("no" "query" "no-export" "query-export"))` $0
```

However, this condition doesn't seem to be applied. If at a particular point (for example in an empty org buffer) I type `v` then `TAB`: yas expands the snipped - even though if I call `(+yas/org-src-header-p)` at the point prior to `TAB` that function evaluates to `nil`.

I can't quite work out what's going on here. I use yasnippet with doom, and am at 5b1217a.

Any help would be much appriciated.

**Comment by npostavs** [comment]
>     # contition: (+yas/org-src-header-p)

You misspelled conDition?

**Comment by tecosaur** [comment]
Ah.... _yes_

![Ooop](https://media.giphy.com/media/Ho2mVZ5dvsW7S/source.gif)

Welp. Sorry about that :sweat_smile:, thanks for pointing out that.
Funny how you can read what you expect.
