### ISSUE TITLE
Two snippets with same name but different keys: one is not loaded

### ISSUE THREAD

**Issue by tobiasBora** [joaotavora/yasnippet#1082]
Hello,

Sorry if that issue was raised before, but I couldn't find any reference to that. So I'm using both `doom-snippets` and `yasnippet-snippets`, and I can't use some snippets defined in yasnippet-snippets. Notably:

- `io` and `std` in c-mode (the corresponding snippet has name `stdlib)
- `ifm` in python-mode (name `ifmain`)

It turns out that all these snippets have the same property: there exists in `doom-snippet` another snippet with the same name but a different key:

```
$ cat yasnippet-snippets/snippets/python-mode/ifmain 
# -*- mode: snippet -*-
# name: ifmain
# key: ifm
# --
if __name__ == '__main__':
    ${1:main()}
```
```
$ cat doom-snippets/python-mode/ifmain 
# -*- mode: snippet -*-
# name: ifmain
# --
if __name__ == '__main__':
    ${1:`(or % "pass")`}
```

In `M-x yas-describe-tables`, I can find some snippets that belong to `yasnippet-snippets`, like `ic`, but it turns out that the snippet whose name is `ifmain` belongs to `doom-snippets`:
```
state name                                  key
(a) ifmain                                  ifmain
```
Ideally, I'd prefer to have two snippets defined, one with `ifmain` key, that sends me to the snippet of `doom`, and one with `ifm` that sends me to the snippet of `yasnippet-snippet`.

Thanks!

**Comment by zw963** [comment]
I meet same issue today.

Following is two snippet.

```cl
# -*- mode: snippet -*-
# name: println!
# key: p
# --
println!("`(yas-field "1" "p" "" ": ")`{}", $0)
```

```
# -*- mode: snippet -*-
# name: println!
# key: pr
# --
println!("$0")
```

The second one will never be loaded because two snippet with same name (but different key), the first one shadow the secondary one.

**Comment by joaotavora** [comment]
This is a limitation that I'm unlikely to change.  Snippets must have unique names. So just change the snippet's name.
