### ISSUE TITLE
Snippets inside snippets

### ISSUE THREAD

**Issue by veronikazaglotova** [joaotavora/yasnippet#1086]
I use LaTeX. I have a "frac" snippet from "yasnippet-snippets" (from the readme). When I want to make anything in a "\frac" or "\sqrt{}" or anything else, I can't get yasnippet to work from that. A lot of the time I have a fraction in a fraction or a fraction under a root or root in a fraction and yasnippet simply doesn't work. yas-expand does nothing.
Also, it's probably obvious but I still want to say that: a snippet in a snippet shouldn't stop the other snippet. E.g. if I had this `\frac{\frac{1}{x}}{5}{denominator}` code completed with yasnippet, after I exit the "frac" snippet inside another frac I can still append something to the numerator and when I press tab the cursor has to go to the "denominator".

**Comment by joaotavora** [comment]
I seem to remember having implemented this. Yes, try `(setq yas-triggers-in-field t)` and you should have snippets in snippets.

**Comment by veronikazaglotova** [comment]
Thx!

**Comment by dian-yu-luo** [comment]
that doesn't work for me
that my config and snippet 
```
(use-package yasnippet
  :init
  (setq yas-triggers-in-field t)
  :config
  (define-key yas-minor-mode-map (kbd "C-c y") #'yas-expand)
  (add-to-list 'yas-snippet-dirs "~/.emacs.d/learning/emacs/snippets")
  (yas-global-mode 1)
  )

```

```
# -*- mode: snippet -*-
# name: frac 
# key: frac
#condition: (texmathp)
# --

\frac{$2}{$1} $0
```
```

# -*- mode: snippet -*-
# name: square root
# key: srt
#condition: (texmathp)
# --
\sqrt $1 {$0}
```


at the condition 
```
\begin{gather*}
\frac{}{srt} 
\end{gather*}
```
my cursor is after srt but when i use tab ,is just jump to previous {}

**Comment by dian-yu-luo** [comment]
but if I use the shortcut I defined "C-c y" It can expand
