### ISSUE TITLE
Snippet expand in dollar sign region?

### ISSUE THREAD

**Issue by joshcho** [joaotavora/yasnippet#1127]
When I am in a $beg|$ block (say, in org mode) where | is the cursor, I cannot expand snippets. This works fine in a () block. How do I emulate that behavior in $$ block?

**Comment by ilyaw39** [comment]
> When I am in a $beg|$ block (say, in org mode) where | is the cursor, I cannot expand snippets. This works fine in a () block. How do I emulate that behavior in $$ block?

Well... The reason for that is the dollar signs are not considered delimiters by default. This means the dollar signs are just equivalent to common characters. For example, telling YASnippet to expand `$beg|$` is the same thing telling it to expand `foobeg|foo`. In this case YASnippet cannot determine which key is demanded, that is, `foobeg` or `beg`.

There is an easy way to do this. First you need to set `yas-triggers-in-field` to `t`, which enables YASnippet expanding keys in the field that has been earlier expanded. Then you just need to add a snippet file that makes `$|$` a field. For example, mine is

``` YASnippet
# -*- mode: snippet -*-
# name: foo
# key: bar
# --
\$$1\$$0
```

So next time if you want to expand something inside the dollar signs, you may trigger the key `bar` first, then it will create a field inside the dollar signs that makes triggering snippets inside available.

**Comment by joshcho** [comment]
Perfect, thank you. I use tab to complete snippets, so the following trick worked well for me.

```
# -*- mode: snippet -*-
# name: foo
# key: $
# --
\$$1
```
