### ISSUE TITLE
please tag new release for Emacs 29 compat (affects MELPA stable and others)

### ISSUE THREAD

**Issue by sten0** [joaotavora/yasnippet#1173]
Hi!

Thank you for continuing to maintain yasnippet!  The old version we have in Debian was recently broken by upstream Emacs 29 changes, and it looks like your recent work fixes emacs29 compat as well as emacs28, thus would you please consider tagging a new release?  In particular this will benefit users who track MELPA stable, and in Debian we strongly prefer to track releases rather than snapshots.

Kind regards,
Nicholas

**Comment by dgutov** [comment]
@sten0 I think the recent commits only changed the tests, didn't they? Those are probably not even included in the package by Debian.

I was also wondering why the *main* MELPA package still isn't updating, and that's likely because neither of the included files have changed since 2020.

**Comment by sten0** [comment]
>
> @sten0 <https://github.com/sten0> I think the recent commits only changed
> the tests, didn't they? Those are probably not even included in the package
> by Debian.
>

To be honest, I just read the one line commit message.  Well, it depends
what you mean by the package...yes, they're cut from the so-called "binary
package" (the deb file, for user consumption), but we import full upstream
source whenever possible, and use tests in our three CI networks as part of
"source package" and to validate the "binary package".  P.s. There were
some recent changes on the Debian side, but I can't remember if they were
fixes or skipping failing tests.

I was also wondering why the *main* MELPA package still isn't updating, and
> that's likely because neither of the included files have changed since 2020.
>

Good question, and I'm not sure.  Maybe MELPA can be contacted about which
files to watch for changes?  On the other hand, MELPA doesn't do any CI
last I checked, so maybe tests are irrelevant there.

>

**Comment by dgutov** [comment]
> On the other hand, MELPA doesn't do any CI last I checked, so maybe tests are irrelevant there.

It doesn't package the tests, that's the thing. And it simply relies on whatever CI is set up in the upstream repo.

Personally, it wouldn't make sense to me to cut a release just to have downstream's test runner happier, so one solution is for Debian to carry the extra patch for the tests. But we had a discussion recently that might mean that yasnippet is going to get some minor non-test changes too (https://github.com/company-mode/company-mode/discussions/1414#discussioncomment-7320812).

**Comment by monnier** [comment]
We have made a new 0.14.1 release in the mean time, so I think we can close this

**Comment by monnier** [comment]
> Sounds good to me, but please push the 0.14.1 tag.
> https://stable.melpa.org/#/yasnippet

It's on GNU ELPA, so I see no need to have it on MELPA

**Comment by sten0** [comment]
>> Sounds good to me, but please push the 0.14.1 tag.
>> https://stable.melpa.org/#/yasnippet
>
> It's on GNU ELPA, so I see no need to have it on MELPA

Fair point.  For your convenience, here's my best guess on how to remove
the outdated version from MELPA (I'm guessing remove the file in a PR):

  https://github.com/melpa/melpa/tree/master/recipes/yasnippet

Would you please push the 0.14.1 tag because versions up to 0.14 have
tags, and because the Debian package of yasnippet depends on new tags as
the new upstream version notification mechanism?
