### ISSUE TITLE
unwanted prompt when pressing TAB

### ISSUE THREAD

**Issue by simonmichael** [joaotavora/yasnippet#1176]
Thanks for maintaining yasnippet. I'm pretty sure that in my setup it recently started prompting unnecessarily when I press TAB. Previously it would immediately insert the snippet whose name is before point, now it asks me to choose a snippet and I have to type the name again and press ENTER.

```
$ cd /tmp
$ git clone https://github.com/joaotavora/yasnippet.git yasnippet
$ cd yasnippet/
$ git log -1 --oneline
76e1eee (HEAD -> master, origin/master, origin/HEAD) Merge commit '0650f1989b6da752f60a15aa6b5222e340388cc2' from elpa.git
$ HOME=$PWD emacs -L . -nw
(require 'yasnippet)
(yas-global-mode 1)
M-x yas-load-directory   # load my usual ~/.emacs.d/snippets/ including "day" snippet in Fundamental mode
type day, press TAB   # expected snippet inserted, got Choose a snippet prompt
```

**Comment by simonmichael** [comment]
Solved; I had renamed a snippet, causing `day` to match multiple snippets. This was hard to diagnose, if you'll like a PR changing the "Choose a snippet" prompt and/or adding this to the FAQ, let me know.

**Comment by gvoysey** [comment]
i just hit this; to future readers who are searching this repo for the string "Choose a snippet: " -- consider if you, like me, had symlinked your foo-mode snippet directory to also be foo-ts-mode; if you do this, then every snippet will appear twice and you'll get a single-snippet prompt every time.
