### ISSUE TITLE
Some functions don't work in yasnippet

### ISSUE THREAD

**Issue by joergdw** [joaotavora/yasnippet#1181]
I need the function `replace-regexp-in-string` for a snippet. When you evaluate `(seq-map (lambda (mode) (replace-regexp-in-string "\\(-ts\\)\\{0,1\\}-mode" "" mode)) (list "rust-ts-mode" "python-mode" "tex"))` in emacs, you get the result `("rust" "python" "tex")`. However, if you do that in a snippet, it does not work for me. A minimal example could be the following snippet for the org-mode:

```
#+BEGIN_SRC ${1:rust$$(yas-choose-value (seq-map (lambda (mode) (replace-regexp-in-string "\\(-ts\\)\\{0,1\\}-mode" "" mode)) (list "rust-ts-mode" "python-mode" "tex")))}
  `yas-selected-text`$0
```
The retrieved result is: `("rust-ts-mode" "python-mode" "tex")` – `replace-regexp-in-string` seems to have been ignored.

**Comment by monnier** [comment]
> #+BEGIN_SRC ${1:rust$$(yas-choose-value (seq-map (lambda (mode)
> (replace-regexp-in-string "\\(-ts\\)\\{0,1\\}-mode" "" mode)) (list
> "rust-ts-mode" "python-mode" "tex")))}
>   `yas-selected-text`$0

I think you need to double all those backslashes (yes, the result is
horrendous), because \ is used by YASnippet to escape those magic
characters like $, {, }, etc...

**Comment by monnier** [comment]
> #+BEGIN_SRC ${1:rust$$(yas-choose-value (seq-map (lambda (mode)
> (replace-regexp-in-string "\\(-ts\\)\\{0,1\\}-mode" "" mode)) (list
> "rust-ts-mode" "python-mode" "tex")))}
>   `yas-selected-text`$0

BTW, for regexp instead of `\{0,1\}` you can write `?`

**Comment by joergdw** [comment]
@monnier Thank you for your help. The missing `\` were precisely the issue.
