### ISSUE TITLE
Template variables do not work in template lines starting with #

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [joaotavora/yasnippet#1183]
Hi,

Do template variables e.g. `$1` work in lines that start with `#`?

I'm trying to create a snippet for source code blocks in org mode with the following template

```
# key: src
# --
#+BEGIN_SRC $1
  $0
#+END_SRC
```
When the snippet is inserted, the cursor is not placed in the `$1` position to specify a language. Instead the cursor is moved to the beginning of a line like in the image below
![image](https://github.com/joaotavora/yasnippet/assets/3127565/4406530d-87e5-4ea6-8e99-41bd836d19a7)

Is it possible to make the above template work as expected: specify a language at the `$1` position and then move to the `$0` position?

Thank you!

**Comment by volodymyrprokopyuk** [comment]
I understand that this error is a kind of chicken-egg problem:
- yasnippet inserts a template without a language that is about to be introduced
- org-mode signals an error as the language is not specified
- yasnippet cancels instantiation of the template due to the error in org-mode

I can see two possible solutions
- yasnippet continues template instantiation even in face of errors (what is proposed in the above patch)
- org-mode does not throw an error while yasnippet template instantiation is in progress (probably is a better approach that improves integration between org-mode and yasnippet)

**Comment by monnier** [comment]
It might be worth a bug report over in Org land, indeed, but I installed my patch so we won't be surprised by similar problems in other modes anyway.
