### ISSUE TITLE
Case sensitive major modes?

### ISSUE THREAD

**Issue by dankessler** [joaotavora/yasnippet#1193]
Are the folder names used to organize snippets case sensitive with respect to major modes?

I'm asking mostly because I noticed that AUCTeX recently renamed its major modes, e.g., from `latex-mode` to `LaTeX-mode`, and I'm curious if snippets in the `latex-mode` subfolder will still be available while I am in `LaTeX-mode`.

**Comment by monnier** [comment]
> Are the folder names used to organize snippets case sensitive with respect to major modes?

Good question, I haven't checked.

> I'm asking mostly because I noticed that AUCTeX recently renamed its major
> modes, e.g., from `latex-mode` to `LaTeX-mode`, and I'm curious if snippets
> in the `latex-mode` subfolder will still be available while I am in
> `LaTeX-mode`.

I just pushed a fix to `master` for that.
