### ISSUE TITLE
Drag and drop snippets

### ISSUE THREAD

**Issue by mattfidler** [joaotavora/yasnippet#360]
Allow dropping files onto emacs in certain modes to fill in code associated with that file.  This is partially implemented in:

https://github.com/mlf176f2/extend-dnd

I will not try a patch until I have an idea of how you want the snippet syntax for drag-and-drop snippets.  

With this, more of TextMate snippets can possibly be used.

**Comment by npostavs** [comment]
I don't see this moving, and I have no plans to implement it myself; closing.
