### ISSUE TITLE
Org-mode: trouble auto-indenting snippets that insert headings and drawers

### ISSUE THREAD

**Issue by novoid** [joaotavora/yasnippet#362]
# Summary

An Org-heading (starting with an asterisk) followed by a line
with something like ":word: $1-test" does not work with yasnippet and
Org-mode.

No change in behavior in following cases:
- empty line after heading
- empty line and in-between text after heading
- replacing ":ID:" with ":test:"
- replacing "$1-after" with "${1}-after" 

Versions:
- Org-mode version 6.33x (7.9.3e.1054.g5d467) (latest git)
- yasnippet (version 0.8.0 (beta)) (from github, 2013-02-15)

I started with «emacs -q test.org» and only activated yasnippet and Org-mode without customizations.

Although, in http://article.gmane.org/gmane.emacs.orgmode/66297 somebody could not re-produce this effect. I don't have any clue why he got different behavior especially because I did not use any customization (emacs -q).
# Demonstration

Snippet:

```
* Test
:ID: ${1:test}-after
```

Expected result:

```
* Test
:ID: foo bar-after
```

-> This is what I'd like to achieve.

But unfortunately:

```
* Test
foo bar  :test:     test-after
```

-> "foo bar" is at beginning of line and "test" does not get
replaced by "foo bar" (which was the user input in every example here)
when being in Org major mode. (It works in text mode.)
## Demo: omitting one colon

```
* Test
ID: ${1:test}-after
```

... results in:

```
* Test
  ID: foo bar-after
```

-> works when first colon is missing
## Demo

```
* Test
:ID: $1-after
```

... results in:

```
* Test
foo bar  :ID:       -after
```

-> ERROR
## Demo: omitting the string after $1

```
* Test
:ID: $1
```

... results in:

```
* Test
  :ID: foo bar
```

-> works when "-after" is not given
## Demo

```
* Test
:ID: ${1:test}
```

... results in:

```
* Test
foo bar
```

-> ERROR (second line is marked as a wole and thus overwritten by user)
## Demo: missing heading

```
:ID: ${1:test}-after
```

... results in:

```
:test: foo bar-after
```

-> works when heading line is omitted

**Comment by npostavs** [comment]
Problematic indenting code seems to be at [org.el:22202-22206](https://github.com/emacs-mirror/emacs/blob/emacs-24.5/lisp/org/org.el#L22202-L22206)

**Comment by novoid** [comment]
Issue still persists:

- GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5) of 2016-03-19 on trouble, modified by Debian
- Org-mode version 8.2.10 (release_8.2.10 @ mixed installation! /usr/share/emacs/24.5/lisp/org/ and /home/vk/.emacs.d/elpa/org-30000101/)
- elpa/yasnippet-20160410.833

Emacs started with `-q` and following configuration:
```
(setq package-user-dir "~/.emacs.d/elpa")
(package-initialize)
(add-to-list 'package-archives '("melpa" . "http://stable.melpa.org/packages/"))
(require 'use-package)
(use-package yasnippet
  :demand t
  :mode ("/\\.emacs\\.d/snippets/" . snippet-mode)
  :diminish yas-minor-mode
  :defer 15
  :config
  (yas-load-directory "~/.emacs.d/snippets/")
  (yas-global-mode 1)
)
```

Snippet used:
```
# name : Testing yasnippet issue
# --

** Test ${1:test}
:PROPERTIES:
:ID: $1-myid
:END:

```

**Comment by npostavs** [comment]
Can you try out the fix in #755, please?

**Comment by novoid** [comment]
I failed.

I replaced the patched `yasnipet.el` with the one from the commit mentioned.

Then I started `emacs -q` and did a `eval-buffer` on the `yasnippet.el` file.

To load my test snippet, I opened the `test-orgissue` snippet file and invoked `yas-load-snippet-buffer`. This is asking me `Choose or enter a table (yas guesses text-mode): ` but `org-mode` in not a possible option. Therefore I also failed on invoking the snippet in a `test.org` file.

Could you please give me a hint how to test this properly? Thanks!

**Comment by npostavs** [comment]
Assuming `yasnippet.el` is this file: https://raw.githubusercontent.com/npostavs/yasnippet/f3f20bb688f602adc18efe24f90dc03575d331b1/yasnippet.el, and you're in its directory.

Run `emacs -Q -L . -l yasnippet.el -f yas-global-mode -f org-mode`
Then `C-u M-x yas-new-snippet RET`. 
Copy this snippet into the `*new snippet*` buffer that pops up:

```
# name : Testing yasnippet issue
# key: test
# --

** Test ${1:test}
:PROPERTIES:
:ID: $1-myid
:END:
```

 do `C-c C-l`, hit `RET` at the prompt (it should say `Choose or enter a table (yas guesses org-mode):`).

Now you should be able to invoke your snippet in `org-mode`, by typing `test` and hitting <kbd>tab</kbd>.

**Comment by novoid** [comment]
Awesome instructions, thanks.

I can verify that the patch did fix the issue.

Do you have an idea when the patch will find its way to the master branch?

**Comment by npostavs** [comment]
> I can confirm that the patch did fix the issue.

Thanks for testing. 

> Do you have an idea when the patch will find its way to the master branch?

Probably a week or two.
