### ISSUE TITLE
Add backspace to yas-keymap

### ISSUE THREAD

**Issue by philc** [joaotavora/yasnippet#408]
You can delete selected text in a yas snippet using C-d, but not backspace.

We should add a function `yas-skip-and-clear-or-delete-backward-char` and bind it to backspace.

**Comment by npostavs** [comment]
> `yas-skip-and-clear-or-delete-char` could be refactorized to something like `yas-skip-and-clear-or-call-original` that takes an extra argument specifying the fallback command.

I've written a patch using the `:filter` keybinding method instead, see #892.
