### ISSUE TITLE
Export snippet descriptions

### ISSUE THREAD

**Issue by AndreaCrotti** [joaotavora/yasnippet#443]
Now starting to have a lot of snippets it's hard to remember all of them sometimes.

I just recently found out yas-describe-tables which is very nice, but I was wondering if it might be worth to have a way to generate a big static table of all the Snippets (as HTML/whatever).

I could then automate it for every release for example of my snippets, so it's also available as documentation, and would help me also reorganizing them.
What do you think?

I might do that in Python though parsing the snippets because I'm not that good at Elisp and also because I want to have a simple script generating them. You don't have some code for similar purposes maybe?

Would you like this script in this repository by the way or should I add it to mine?

Thanks

**Comment by AndreaCrotti** [comment]
Hello there @npostavs and @joaotavora 
In the end I did write something, to export everything to HTML:

http://andreacrotti.github.io/yasnippet-snippets/snippets.html
I actually used Clojure and it's not in CI yet so I just generated everything manually, but I've done it in Clojure since it's much easier for me than Elisp, and I can maybe expand it to something even nicer.

Maybe if I actually get the data from yasnippet internal functions instead of parsing all the files myself though I get a better result.
Any thoughts/suggestions about this?

**Comment by npostavs** [comment]
> Maybe if I actually get the data from yasnippet internal functions instead of parsing all the files myself though I get a better result.

Sure, looks simple enough to generate. I can help translating to Elisp if you like (I don't know Clojure well, but I guess this code won't be too complicated).

**Comment by AndreaCrotti** [comment]
Yes well the thing is that I would like to make that part of CI, so building and publishing automatically that HTML somewhere for every release.

Also I could add some tests to ensure that snippets are well formed, and again add that in CI.
I think this could be done by `emacs --batch` as well, but I suspect that Clojure would be a better choice for that kind of stuff.
The "grammar" is so simply anyway that it's not such a big deal imho if I have to reimplement something.

This generated HTML should maybe just be used for people who want to get an idea of what's available, Emacs users can still use `yas-describe-tables` inside Emacs to see it in a nice Emacs buffer.

**Comment by npostavs** [comment]
> The "grammar" is so simply anyway that it's not such a big deal imho if I have to reimplement something.

Well, the main issue there is that you might not be bug-compatible.
