### ISSUE TITLE
Keybinding (TAB) conflict between YASnippet and autocomplete packages

### ISSUE THREAD

**Issue by ldkxingzhe** [joaotavora/yasnippet#526]
In ubuntu14.04,gnu emacs 24.3.1, I installed yasnippet 0.8.0 and autocomplete 1.4.

Code in my .emacs:

``` elisp
(require 'auto-complete-config)
(require 'auto-complete)
(add-to-list 'ac-dictionary-directories "~/.emacs.d/elpa/auto-complete-1.4/dict")
(global-auto-complete-mode t)
(ac-config-default)
(require 'yasnippet)
(yas-global-mode 1)
```

When i open a file(.cpp),the snippets works well, but the auto-complete doesn't. this confused me. Can you help me ? Thank you anyway.

**Comment by fommil** [comment]
I use the recommendation at http://orgmode.org/manual/Conflicts.html

```lisp
(defun yas/org-very-safe-expand ()
  "WORKAROUND http://orgmode.org/manual/Conflicts.html yas conflict."
  (let ((yas/fallback-behavior 'return-nil)) (yas/expand)))
(add-hook 'org-mode-hook
          (lambda ()
            (make-variable-buffer-local 'yas/trigger-key)
            (setq yas/trigger-key [tab])
            (add-to-list 'org-tab-first-hook 'yas/org-very-safe-expand)
            (define-key yas/keymap [tab] 'yas/next-field)))
```

but it would be great if this were supported out of the box in yas.

**Comment by npostavs** [comment]
> The following code stops auto complete falling back on yas and looping from there:

I think this shouldn't a problem any more since yasnippet moved to conditional keybindings, `yas-fallback-behavior` is `return-nil` by default (and other settings are considered obsolete).
