### ISSUE TITLE
YASnippet select more than field in latex mode

### ISSUE THREAD

**Issue by pascal-niklaus** [joaotavora/yasnippet#579]
In a LaTeX snippet, when the snippet is inserted, not just "field" is selected for entering but the entire line including the leading %% (see below). For the 2nd field, this then works correctly. Looks like it is related to the '%', because adding another character after the two (or three) % fixed this behaviour.

```
# -*- mode: snippet; require-final-newline: nil -*-
# name: xtst
# key: xtst
# binding: direct-keybinding
# --
%%
%% ${1:field}
%%
%% ${2:field}
%%
```

![yasissue](https://cloud.githubusercontent.com/assets/9673983/7671455/34377d3a-fcd1-11e4-99ed-e14aa1560d42.png)

**Comment by npostavs** [comment]
Doesn't happen here. Which Emacs and Yasnippet versions are you using? Also, is this the builtin `latex-mode`, or are you using `AUCTeX` package?

**Comment by pascal-niklaus** [comment]
I am using AUCTeX, package-activated-list equals (auctex auto-complete-auctex auto-complete popup yasnippet hideshow-org popup yasnippet).

Version is 20150415.244 from elpa.

**Comment by npostavs** [comment]
Emacs version?

Can you check if it happens with just builtin `latex-mode`?

**Comment by pascal-niklaus** [comment]
Emacs is version 24.5.1. The problem disappears if I uninstall auctex.

**Comment by npostavs** [comment]
Confirmed. The markers for the field go wrong during indentation, I can't tell why.

Minimal reproduction recipe:
- download and untar http://ftp.gnu.org/pub/gnu/auctex/auctex-11.88.tar.gz
- `./configure --disable-preview`
- `make tex-site.el`
- `emacs -Q -L yasnippet/ -L auctex-11.88/ -l yasnippet.el -l tex-site.el -f yas-global-mode -f latex-mode`
- Create a new buffer
- <kbd>M-x</kbd> `latex-mode`
- <kbd>M-:</kbd> `(yas-expand-snippet "%\n% ${1:field}")`

**Comment by capitaomorte** [comment]
> The markers for the field go wrong during indentation, I can't tell why.

Indentation happens after snippet field insertion (it may depend on field contents, for instance). The problem is that some indentation techniques destroy the whole whitespace in front of the line (or maybe the whole line, who knows?) and restore an indented version. Obviously, yasnippet's markers aren't restored by those strategies, so there is `yas--indent-according-to-mode`, which tries to. There is some effort there to describe the problem, though in a language that I myself found hard to understand. And the implementation seems a little bit contorted (this is quite old code...)

I don't have time to fix this right now, but if you can think of some better approach, I would very much like to hear it, as this problem is central in the yasnippet engine, which is being exported to the `snippet-engine` branch.

From your exchange, though, I still haven't understood if this happens with vanilla Emacs'  `latex-mode`, though.

**Comment by capitaomorte** [comment]
In `yas--indent-according-to-mode`, a better approach might be to take a snapshot of the current line's contents and yas-specific markers, before calling `indent-according-to-mode`, then call it, then finally match the snapshot against newly indented line and reset the markers from that.

**Comment by npostavs** [comment]
> From your exchange, though, I still haven't understood if this happens with vanilla Emacs' latex-mode, though.

It doesn't.

**Comment by npostavs** [comment]
> The problem is that some indentation techniques destroy the whole whitespace in front of the line (or maybe the whole line, who knows?) and restore an indented version. Obviously, yasnippet's markers aren't restored by those strategies

I *think* it might be enough to `(set-marker-insertion-type <field-start-marker> t)`. It looks like the markers stay in place fine when the whitespace is deleted, but if the marker happens to be sitting at the beginning, then when adding text back in, the marker stays put, while the actual field start gets pushed forward. Type `t` markers get pushed forward when text is inserted at their position.

It works for this case at least, need to test more to see if it works elsewhere.

---

I used this code to play with marker types:

```elisp
(switch-to-buffer (get-buffer-create "mtest.latex"))
(erase-buffer)
(latex-mode)

(defvar m-beg (make-marker))
(defvar mt-beg (make-marker))
(defvar m-end (make-marker))

(insert "%\n% ")
(set-marker m-beg (point))
(set-marker mt-beg (point))
(insert "field")
(set-marker m-end (point))

(set-marker-insertion-type mt-beg t)


(defun show-markers ()
  (interactive)
  (message "(%d, %d): %s; (%dt, %d): %s"
           (marker-position m-beg) (marker-position m-end) (buffer-substring m-beg m-end)
           (marker-position mt-beg) (marker-position m-end) (buffer-substring mt-beg m-end)))
(define-key global-map [f12] 'show-markers)
```

Hit <kbd>f12</kbd> to see where the markers are currently, then change the buffer text and hit <kbd>f12</kbd> again to see how the markers were affected.

**Comment by capitaomorte** [comment]
> Probably related to what AUCTeX calls "inner indentation":

Most definitely, yes.

> I think it might be enough to (set-marker-insertion-type <field-start-marker> t).

Not enough. Suppose you have "whitespace -> null field -> whitespace", for example. You are also assuming that the major-mode adds whitespace using `insert` at the very beginning of the line, but it might not. Later today I'll try to dig other issues that dealt with exactly this problem, I kinda remember `cperl-mode` being problematic

**Comment by npostavs** [comment]
> Suppose you have "whitespace -> null field -> whitespace",

Ah, I didn't consider null fields indeed.
