### ISSUE TITLE
yassnippets doesn't load snippets for source block in org-mode

### ISSUE THREAD

**Issue by kendriu** [joaotavora/yasnippet#649]
I'm using org-babel in org-mode I'm adding emacs-lisp source block

```
#+BEGIN_SRC emacs-lisp
;; Some code in emacs lisp
#+END_SRC
```

It would me nice to use snippets emacs-lisp snippets, but yassnippets doesn't seems to load theme.

**Comment by npostavs** [comment]
It works if you use `C-c '` (`org-edit-special`) though, right? I don't see a way to implement this in the org mode buffer.

**Comment by capitaomorte** [comment]
Yeah, this is the "multiple-major-mode" holy grail... I think this can be striked out of yasnippet's feature request list and added to Emacs's

**Comment by kendriu** [comment]
@npostavs Indeed it works in `org-edit-sepcial`, thank you for this tips. Altghough it would be nice, if I hadn't to leave org-mode (safes keystrokes ^_^)

**Comment by npostavs** [comment]
> I don't see a way to implement this in the org mode buffer.

Actually, it might be possible to copy in all the snippets to org-mode, but add a [condition][c] that checks whether point is in a suitable org source block.

[c]: http://capitaomorte.github.io/yasnippet/snippet-expansion.html#sec-2-2
