### ISSUE TITLE
Support ${0:ephemeral-text} exit marker style

### ISSUE THREAD

**Issue by joaotavora** [joaotavora/yasnippet#653]
Textmate used to support this. I tried it once in 4a8651f34f8a7a44a09704e85b36d2789e2f8d9e, but it's not working now.

The idea is that navigating to `${0:soon-to-be-deleted}` exits the snippet but leaves `soon-to-be-deleted` selected so that the next insertion or keystroke erases it. 
- Currently, that region is _not_ left selected as the active region. 
- As an exception to the former textmate behaviour, this could be adapted to followif Emacs' standard "delete-selection" switches

**Comment by npostavs** [comment]
It works if there are any other fields, just not if the 0 fields is the only one.
