### ISSUE TITLE
Something wrong with non-english character expanding?

### ISSUE THREAD

**Issue by myme5261314** [joaotavora/yasnippet#700]
I've add some customize snippets, one of them is
```
# name: (now)
# key: now
# --
`(insert (format-time-string "[%Y-%m-%d %a %H:%M]"))`
```
The %a will be interpreted as a localize character stand for workday, say "五" equivalent to Friday.
The thing is it can be expanded at first time once. And then the yasnippet seems crash or something. Type any character won't trigger dropdown list but echo such error.
```
Server error: KeyError(u'\u4e94\u6708',)
```

I've tested replace `%a` to `%u` in the snippet, which interpreted as `5` equivalent to `Friday`.
Then, no issue occurs.

So, any idea how to fix this?

**Comment by npostavs** [comment]
Does it work without the `insert` call?
```
# name: (now)
# key: now
# --
`(format-time-string "[%Y-%m-%d %a %H:%M]")`
```
I tried to reproduce with 
```
# name: (now)
# key: now
# --
`(insert "五")`
```
But it worked fine for me.

> Type any character won't trigger dropdown list but echo such error.

Does this indicate something going wrong with your input method? Can you get a backtrace with `debug-on-error`?
