### ISSUE TITLE
extra content when yas-expand-snippet in snippet

### ISSUE THREAD

**Issue by myme5261314** [joaotavora/yasnippet#701]
I've write two snippets:
```
# name: (year)
# key: year
# --
`(format-time-string "%Y" (current-time))`
```
```
# name: (head)
# key: head
# --
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © `(yas-expand-snippet (yas-lookup-snippet "(year)"))`
#
# Distributed under terms of the license.

"""
$0
"""
```

If you expand `(year)` by type some character and select to expand manually. The result is correct with `2016`. But if you expand `(head)` manually, that line becomes `# Copyright © t2016`. Seems the t is kind of the return value of `yas-expand-snippet` or `yas-lookup-snippet`

And I want to say, is there a more convenient way to ref other snippets in certain snippets? Yasnippet really hard to use for this purpose.

**Comment by myme5261314** [comment]
Seems find the workaround solution. Just change `year` snippet to the following:
```
# name: (year)
# key: year
# type: command
# --
(insert (format-time-string "%Y" (current-time)))
```
Then, problem solved. Cheers :-)

**Comment by myme5261314** [comment]
by the way, the `head` snippet need to add the property below or the indent will be ugly.
```
# expand-env: ((yas-indent-line 'auto))
```

**Comment by npostavs** [comment]
> And I want to say, is there a more convenient way to ref other snippets in certain snippets? Yasnippet really hard to use for this purpose.

Not yet, see #558.

> Seems find the workaround solution. Just change year snippet to the following:

The problem here is that your are then inserting the snippet contents by side-effect, which is not the intended semantics of yasnippet's backquote construct. I think you could use a temp buffer instead:
```
# name: (head)
# key: head
# --
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © `(with-temp-buffer (yas-minor-mode +1) (yas-expand-snippet (yas-lookup-snippet "(year)" 'python-mode)) (buffer-string))`
#
# Distributed under terms of the license.

"""
$0
"""
```

> Seems the t is kind of the return value of yas-expand-snippet or yas-lookup-snippet

Of `yas-expand-snippet`, yes.
