### ISSUE TITLE
instead of one snippet one file, is it possible to group severl snippets into a file?

### ISSUE THREAD

**Issue by introom** [joaotavora/yasnippet#705]
Hi,

Possible to put snippets inside one file instead of making a new file for each snippet?

**Comment by npostavs** [comment]
You can use `yas-compile-directory` to collect snippets into a single file. It's not intended to be instead though, because the result is not so editable.

**Comment by introom** [comment]
thanks for the reply.

In other words, for resonable usability, one has to create one file for a snippet.

**Comment by npostavs** [comment]
> In other words, for resonable usability, one has to create one file for a snippet.

Yes.
