### ISSUE TITLE
yas-expand won't expand within double quotes

### ISSUE THREAD

**Issue by zmwangx** [joaotavora/yasnippet#706]
### Background

Please skip if you're not interested.

Basically, I have a few python-mode snippets for shaping numpy-styled docstrings. I haven't used the numpy style for a while, so those snippets weren't touched. Just now I needed to use them, and I was surprised that they simply won't expand. Digging around a bit, I noticed that those snippets expand fine unless when I'm within an unclosed double quote.

### Steps to reproduce

With latest master:

1. `emacs -Q --load yasnippet.el`;
2. Within the scratch buffer, `M-x yas-new-snippet` to create a random snippet, e.g.,

    ```
# -*- mode: snippet -*-
# name: a
# key: a
# --
Expanded snippet "a".$0
```

   then save it by answering a bunch of prompts.

3. `M-x yas-minor-mode`;
4. Type `a<TAB>` in the scratch buffer. `a` expanded to `Expanded snippet "a".`;
5. Now type `"a<TAB>`. Nothing happens;
6. Delete what we have so far and type `'a<TAB>`. Expands fine.

Conclusion: `yas-expand` doesn't work in an unclosed double quote. And as an aside, single quote has no such effect.

### Problematic commit

`git-bisect` shows that the problematic commit is 140c415505b7f2673fe58fdbf033213b089c22b3, which is supposed to fix #305. I'm not sure what it does exactly, but at least it broke expanding within double quotes for me, and my python-mode docstring snippets are supposed to operate within double quotes.

Is it intentional, or is it a bug? I would like to see an option if it is intentional. Thanks.

**Comment by zmwangx** [comment]
Oops, accidentally submitted with hotkey. Please wait while I edit in the content.

**Comment by zmwangx** [comment]
Done editing.

**Comment by npostavs** [comment]
You fulfilled my prophecy in https://github.com/joaotavora/yasnippet/pull/638#issue-121831941:

> since the condition was effectively ignored for a long time due to only checking `yas-expand-from-trigger-key` and not `yas-expand`, [...] people will start complaining that snippets no longer work in comments [and strings]...

;) 

> I would like to see an option if it is intentional.

Simply set `yas-buffer-local-condition` to `nil`.

**Comment by zmwangx** [comment]
Cool. Sorry for not reading the manual.

**Comment by zmwangx** [comment]
For future reference, I believe `force-in-comment` should be quoted, i.e., one should write 

````lisp
# condition: 'force-in-comment
```

in snippets.

https://joaotavora.github.io/yasnippet/snippet-expansion.html#sec-2-2
https://joaotavora.github.io/yasnippet/snippet-reference.html#yas-buffer-local-condition

**Comment by npostavs** [comment]
> For future reference, I believe force-in-comment should be quoted

Yes, you're correct. Also, to expand regardless of snippet condition, you should set `yas-local-buffer-condition` to `always`, not `nil` like I said before ( setting to `nil` would in fact disable all snippet expansion!)
