### ISSUE TITLE
`yas-expand-snippet' needs properly setup `yas-minor-mode'

### ISSUE THREAD

**Issue by fommil** [joaotavora/yasnippet#708]
I'm getting weird errors in ensime when running my test, I have a suspicion that we've been narrowly missing this problem by chance for many months.

I have a buffer with `yas-minor-mode` enabled and I'm getting this error which is triggered by our own functions. Is our template somehow malformed? are the brackets causing a problem or something?

```
Debugger entered--Lisp error: (error "[yas] `yas-expand-snippet' needs properly setup `yas-minor-mode'")
  signal(error ("[yas] `yas-expand-snippet' needs properly setup `yas-minor-mode'"))
  error("[yas] `yas-expand-snippet' needs properly setup `yas-minor-mode'")
  yas-expand-snippet("(${1:block: (Int) => String})" 437 437)
```

The buffer looks like this at the time, with `^^^` indicating the point (position 437)

```
package com.helloworld
object HelloWorld {
  private var _field:Int = 1
  def field = _field
  def field_=(i:Int) { _field = i}
  def add(a:Int, b:Int) = {
    a + b
  }
  def str(i:Int) = {
    i.toString
  }
  def doBlock(block:(Int => String)) = {
    block(1)
  }
  def doByName(block: => String) = {
    block
  }
  def test() {
    val c = add(2, 3)
    val d = c + 5
    val e = d + 8
    val f = doBlock(str)
    val g = doBlo^^^
    val h = doByNa/*6*/
      this.fie/*7*/
    "kjsdf".hashCo/*8*/
    "kjsdf".getByt/*8_1*/
    5.toLo/*9*/
  }
}
```

**Comment by fommil** [comment]
bizarrely, the `yas-minor-mode` is being set to `nil` even though a `C-x m` is listing `Yas` as a minor mode for the buffer.

**Comment by npostavs** [comment]
`yas-minor-mode` does get let-bound to `nil` in `yas--fallback`, though I need more context to see how you're hitting that.

**Comment by fommil** [comment]
once I have my work-in-progress working and merged, I'll point you at the code.

How would I find myself in `yas--fallback`?

**Comment by npostavs** [comment]
> How would I find myself in `yas--fallback`?

Trying an interactive snippet expansion command (`yas-expand` (aka `yas-expand-from-trigger-key`) or `yas-expand-from-keymap`) and failing to find a snippet.

**Comment by fommil** [comment]
oh, I think I know what that could be. It might be conflicting meanings for TAB, so the user would type TAB to do company-mode complete (and probably trigger some failed yas expansion) and then inside our company-mode backend we're using `yas-expand` to dynamically generate an expansion for our completions... e.g. a method completion with all the parameter names and types filled in. Is it safe in such a situation to just set the `yas-expand` to `t`? Failing that, how can we make sure that we completely disable yas on TAB? We're currently doing https://github.com/ensime/ensime-emacs/blob/master/ensime-company.el#L122-L130

**Comment by npostavs** [comment]
> Is it safe in such a situation to just set the `yas-expand` to t?

You mean `yas-minor-mode`? Yes, it should be.

> how can we make sure that we completely disable yas on TAB?

```elisp
(define-key yas-minor-mode-map [(tab)] nil)
(define-key yas-minor-mode-map (kbd "TAB") nil)
```

**Comment by fommil** [comment]
cool! Thanks, I guess we'll have to make it a local variable

**Comment by npostavs** [comment]
>> Is it safe in such a situation to just set the `yas-expand` to t?

> You mean `yas-minor-mode`? Yes, it should be.

I suppose we could just drop the check for `yas-minor-mode` in that assertion. The important part is the `post-command-hook` that checks for the user leaving the snippet. The hook and the mode are enabled together, so usually they should both be on or off, but there are some exceptional cases as you've found...

**Comment by ivanhjc** [comment]
For me the snippets fail to expand after creating and loading a new snippet with mini-buffer reporting `apply: [yas] ‘yas-expand-snippet’ needs properly setup ‘yas-minor-mode’`. Turning on `toggle-debug-on-error` get the following backtrace:

    Debugger entered--Lisp error: (cl-assertion-failed ((and yas-minor-mode (memq (quote yas--post-command-handler) post-command-hook)) "[yas] `yas-expand-snippet' needs properly setup `yas-minor-mode'"))
      cl--assertion-failed((and yas-minor-mode (memq (quote yas--post-command-handler) post-command-hook)) "[yas] `yas-expand-snippet' needs properly setup `yas-minor-mode'" nil nil)
      yas-expand-snippet(#s(yas--template :key "/*" :content "/**\n * ${1:documentation}\n */" :name "doc" :condition nil :expand-env nil :load-file "/home/ivanhjc/.emacs.d/elpa/yasnippet-snippets-20200425.1210/snippets/java-mode/doc" :save-file nil :keybinding nil :uuid "doc" :menu-binding-pair ((menu-item "doc" (lambda nil (interactive) (yas--expand-or-visit-from-menu (quote java-mode) "doc")) :keys "/* =>")) :group nil :perm-group nil :table #s(yas--table :name "java-mode" :hash #<hash-table equal 34/65 0x1285fbd> :uuidhash #<hash-table equal 34/65 0x1289459> :parents nil :direct-keymap (keymap))) 575 577)
      yas--expand-or-prompt-for-template((("doc" . #s(yas--template :key "/*" :content "/**\n * ${1:documentation}\n */" :name "doc" :condition nil :expand-env nil :load-file "/home/ivanhjc/.emacs.d/elpa/yasnippet-snippets-20200425.1210/snippets/java-mode/doc" :save-file nil :keybinding nil :uuid "doc" :menu-binding-pair ((menu-item "doc" (lambda nil (interactive) (yas--expand-or-visit-from-menu ... "doc")) :keys "/* =>")) :group nil :perm-group nil :table #s(yas--table :name "java-mode" :hash #<hash-table equal 34/65 0x1285fbd> :uuidhash #<hash-table equal 34/65 0x1289459> :parents nil :direct-keymap (keymap))))) 575 577)
      yas-expand()
      funcall-interactively(yas-expand)
      call-interactively(yas-expand nil nil)
      command-execute(yas-expand)
      recursive-edit()
      debug(error (cl-assertion-failed ((and yas-minor-mode (memq (quote yas--post-command-handler) post-command-hook)) "[yas] `yas-expand-snippet' needs properly setup `yas-minor-mode'")))
      cl--assertion-failed((and yas-minor-mode (memq (quote yas--post-command-handler) post-command-hook)) "[yas] `yas-expand-snippet' needs properly setup `yas-minor-mode'" nil nil)
      yas-expand-snippet(#s(yas--template :key "gs" :content "public ${1:String} get${2:$(upcase-initials yas-text)}() {\n    return ${2:field};\n}\n\npublic void set${2:$(upcase-initials yas-text)}($1 $2) {\n    this.$2 = $2;\n}\n" :name "getter and setter" :condition nil :expand-env nil :load-file nil :save-file nil :keybinding nil :uuid "getter and setter" :menu-binding-pair ((menu-item "getter and setter" (lambda nil (interactive) (yas--expand-or-visit-from-menu (quote java-mode) "getter and setter")) :keys "gs =>")) :group nil :perm-group nil :table #s(yas--table :name "java-mode" :hash #<hash-table equal 34/65 0x1285fbd> :uuidhash #<hash-table equal 34/65 0x1289459> :parents nil :direct-keymap (keymap))) 575 577)
      yas--expand-or-prompt-for-template((("getter and setter" . #s(yas--template :key "gs" :content "public ${1:String} get${2:$(upcase-initials yas-text)}() {\n    return ${2:field};\n}\n\npublic void set${2:$(upcase-initials yas-text)}($1 $2) {\n    this.$2 = $2;\n}\n" :name "getter and setter" :condition nil :expand-env nil :load-file nil :save-file nil :keybinding nil :uuid "getter and setter" :menu-binding-pair ((menu-item "getter and setter" (lambda nil (interactive) (yas--expand-or-visit-from-menu ... "getter and setter")) :keys "gs =>")) :group nil :perm-group nil :table #s(yas--table :name "java-mode" :hash #<hash-table equal 34/65 0x1285fbd> :uuidhash #<hash-table equal 34/65 0x1289459> :parents nil :direct-keymap (keymap))))) 575 577)
      yas-expand()
      funcall-interactively(yas-expand)
      call-interactively(yas-expand nil nil)
      command-execute(yas-expand)
    
* Emacs version: `GNU Emacs 26.3 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.11) of 2019-12-11`
* The snippet loaded:

        # -*- mode: snippet -*-
        # name: getter and setter
        # key: gs							
        # --
        public ${1:String} get${2:$(upcase-initials yas-text)}() {
            return ${2:field};
        }
        
        public void set${2:$(upcase-initials yas-text)}($1 $2) {
            this.$2 = $2;
        }

* Snippet creating steps:

   1. Run `M-x yas-new-snippet`.
   2. Paste the snippet onto the opened buffer.
   3. Type `C-c C-c` to save and load.

* Usage: Type `gs` and `TAB` in a Java source file buffer where lsp-java is properly set up.

The error is cleared by turning `yas-minor-mode` off and on again, and it doesn't occur afterwards, even when the afore mentioned steps are repeated. But it does occur several times and I'm just not sure what's the exact acts that cause it.

**Comment by npostavs** [comment]
>     * Usage: Type `gs` and `TAB` in a Java source file buffer where lsp-java is properly set up.

Do you mean `lsp-java` is needed to reproduce this problem? If you can come with a recipe starting from `emacs -Q` that would help to narrow down the cause. But you should open a separate issue for that.

**Comment by philippludwig** [comment]
> The error is cleared by turning yas-minor-mode off and on again, and it doesn't occur afterwards, even when the afore mentioned steps are repeated.
Not in my case, sadly. I get:

```
Error in post-command-hook (yas--post-command-handler): (wrong-type-argument markerp 1917)
```

**Comment by gui-salome** [comment]
> > The error is cleared by turning yas-minor-mode off and on again, and it doesn't occur afterwards, even when the afore mentioned steps are repeated.
> 
> Not in my case, sadly. I get:
> 
> ```
> Error in post-command-hook (yas--post-command-handler): (wrong-type-argument markerp 1917)
> ```

Did you find a fix to this problem? I have been having this issue in doomemacs and vanilla emacs with yasnippet all the time.

**Comment by philippludwig** [comment]
@gui-salome I did not use yas for a couple of months. Then, it started working again after I upgraded everything and deleted the `.yas-compiled-snippets.el` files.
