### ISSUE TITLE
`(insert "string")` not worked in snippets github HEAD (Earlier version worked)

### ISSUE THREAD

**Issue by zw963** [joaotavora/yasnippet#710]
## Commit
e21420a - (HEAD, origin/master, origin/HEAD, master) Separate parsing from evaluation of backquote lisp(5 days ago,Noam Postavsky)

### create a new snippets for ruby-mode
```cl
# -*- mode: snippet -*-
# name: def1
# key: def1
# binding: C-c a
# --
def method`(insert "abcd")`
  $0
end
```

### Start `emacs 1.rb` with only following config:
```cl
(require 'yasnippet)
(require 'popup)
(yas-reload-all)
(add-hook 'prog-mode-hook #'yas-minor-mode)
```

### Press C-c a, output result is:
```ruby
def methodbcdY
      
end
```

## Emacs version is 24.5.1 

Thanks.

**Comment by zw963** [comment]
Hi, maybe you surprise about why use `(insert "abcd")` in snippets.
Generally, I will set some condition to decide if insert some content in.

e.g. this snippets is trigger from `binding` or `key`.

**Comment by npostavs** [comment]
It works if you don't use `insert`. I'm inclined to say this is not a bug. Using backquotes to insert contents by side-effect is not the intended semantics.

```
# -*- mode: snippet -*-
# name: def1
# key: def1
# binding: C-c a
# --
def method`"abcd"`
  $0
end
```

**Comment by ReneFroger** [comment]
@npostavs  I use the insert method extensively in my snippets. But I think it's a bug. Previous week I had not the same problem. After a update of Yasnippet, I got bugged with this issue.

For example, I have the following snippet:

    Creation date: `(insert-date)`

And the function `insert-date` is defined as followed:

    (defun insert-date ()
        "Insert current date 1 jun yyyy."
        (interactive)
        (insert (format-time-string "%e %b %Y"))
    )

But I got the following after inserting the snippet:


    Creation date: 18 Jun 2016Y
    
Instead of 
    
    Creation date: 18 Jun 2016

**Comment by joaotavora** [comment]
For the record: I'm afree with @npostavs here, though I had implemented the backquote scheme to allow for these kinds of hackery, I don't think it should be supported anymore.

**Comment by npostavs** [comment]
> I use the insert method extensively in my snippets.

Then stop that ;)

> But I think it's a bug. Previous week I had not the same problem.

It is a change behaviour, but I think the bug is in the snippets (the bug was hidden up until now). Instead of
```
Creation date: `(insert (format-time-string "%e %b %Y"))`
```
Use
```
Creation date: `(format-time-string "%e %b %Y")`
```

I will consider backout out e21420a497c1d79edc6b36ffb1f3bf1bb70f6227 for now, and adding a warning when snippets do insert by side-effect.

**Comment by zw963** [comment]
I still remember ````(insert (format-time-string "%e %b %Y"))```` is worked not exact same as
```(format-time-string "%e %b %Y")``` in previous version ... 

What I say is: I need expand the actual(that is was eval) content to snippets before 
this snippet is parsed. I still clear remember in some case, if not use `insert`, is not 
worked as expect.

anywhy, don't remember the exact case what i means, maybe it worked well
in current HEAD version.

I will report here if I found the case must use `insert` if can reproduce it again.

**Comment by ReneFroger** [comment]
Thanks @npostavs for your suggestions, I implemented in the way as you suggested and it works fine. But I wonder what's wrong with supporting the `insert` method. Sometimes you would only evaluate the value of a function, instead inserting that value in a snippet.

And thanks @zw963  for reporting this issue, I thought I was alone on this.

**Comment by zw963** [comment]
Hi, i found the case must use `insert`.

write snippet is tired, so I write some wrapper methods  for simplify
the write process.

e.g, one snipipet like this:

```cl
def`${1:meth}`(def)`
```

def is:
```cl
(defun def ()
  (insert
   (concat "foo" "`(some_function)`" "bar")))
```

When this snippet is happen, `insert` is happen before `???` and expansion.
so, what yasnippet is see is: 
```cl
def${1:meth}foo`(some_function)`bar
```
And then, `(some_function)` is eval, then do the expansion. 

If not use insert, `(some_function)` is as string is insert into snippet.
it not what i want.

Enough clear? apologize for my english.

**Comment by zw963** [comment]
I have to restore to version 0.8.1

@ReneFroger , Do you know what the newest worked yasnippet version is?

**Comment by ReneFroger** [comment]
No unfortunately not, I don't know the version number. It didn't worked anymore after I updated it some days ago.

The last time I updated, was 3 months ago.

**Comment by npostavs** [comment]
> I have to restore to version 0.8.1

The latest stable release 0.10.0 (served by MELPA-stable and GNU ELPA) works with the example snippet in the first post here, as I deliberately avoided including e21420a in it. That commit reorganizes backquote handling so I wanted some testing before it entered a stable version.

**Comment by cslux** [comment]
For me https://github.com/joaotavora/yasnippet/commit/e21420a497c1d79edc6b36ffb1f3bf1bb70f6227 broke the use of insert. this is the latest commit.

**Comment by npostavs** [comment]
> ```cl
> def`${1:meth}`(def)`
> ```
> 
> def is:
> ```cl
> (defun def ()
>   (insert
>    (concat "foo" "`(some_function)`" "bar")))
> ```
> 
> When this snippet is happen, `insert` is happen before ````some_function```` and expansion.
> so, what yasnippet is see is: 
> ```cl
> def${1:meth}foo`(some_function)`bar
> ```
> And then, `(some_function)` is eval, then do the expansion. 
> 

Why not use this?
```elisp
(defun def ()
  (concat "foo" (some_function) "bar"))
```

**Comment by zw963** [comment]
> Why not use this?
> 
> (defun def ()
>   (concat "foo" (some_function) "bar"))

Following is not worked

```cl
(defun def ()
  (concat "foo" (some_function) "$0" "bar"))
```
In this case, `$0` is explain as string literal, What i want is expand it.

If use insert, I can exact know, what the content i inserted is same as I
create a snippet with same content, no any accident happen.

I think insert add a extra process before other two normal process.
That exactly what i want.

Thanks

**Comment by zw963** [comment]
More explain:

```cl
def${1:meth}`(def)`
```
Following is def definition:
```cl
(defun def ()
  (insert
  (concat "foo" "`(some_function)`" "$0" "bar")))
```

It know it exactly equal following completely snippet.
```cl
def ${1:meth}foo`(some_function)`$0bar
```

But following is not. 
```cl
(defun def ()
   (concat "foo" (some_function) "$0" "bar"))
```

**Comment by joaotavora** [comment]
@zw963: if you want to do such things, it's much better to use the `# snippet: command` directive. And then simply enter elisp in place of your snippet which eventually calls `yas-expand-snippet` with a custom-built template string as its argument.

**Comment by joaotavora** [comment]
In your case it could be

```
# -*- mode: snippet -*-
# name: zw963
# type: command
# --
(yas-expand-snippet (concat "foo" (some_function) "$0" "bar"))
```

I don't fully understand your case, but this should be enough. That said, I hope @npostavs goes ahead with the planned changes.

**Comment by npostavs** [comment]
> I will consider backing out e21420a for now, and adding a warning when snippets do insert by side-effect.

Done, see 655bda804b11269790c0b8a19aea75d7165ebc3c

**Comment by npostavs** [comment]
> I think insert add a extra process before other two normal process.
> That exactly what i want.

Yeah, that's exactly why I don't want to support this, extra processing brings more complications.

**Comment by zw963** [comment]
> if you want to do such things, it's much better to use the # snippet: command directive.

I think i need to read WIKI about what this `command` directive means.  Thanks,

**Comment by zw963** [comment]
> Done, see 655bda8

It worked, Thanks.

But, why when i expand a snippet, the warning message is popup from a new window. (right side)
instead of minibuffer when I press `TAB`? with this behavior, i think it serious impact the normally process

**Comment by zw963** [comment]
I setting this config: ``(setq yas-verbosity 3)``

**Comment by npostavs** [comment]
Ah, forgot to explain that. You can add `(yasnippet backquote-change)` to `warning-suppress-types` to stop it popping up. I've added this explanation to the warning message.

6b785e185f94fa768f04b6c4baea0b4bb575f9f1

**Comment by zw963** [comment]
worked. Thanks

**Comment by zw963** [comment]
@npostavs , Hi, I am so sorry for told you there still some weird things make my snippets not worked
as my expect. (at least 0.8 worked)

Following is detail, I hope I could describe clearly enough to let you understood. thanks.

### I have a snippets for ruby-mode and enh-ruby-mode
```cl
# -*- mode: snippet -*-
# name: ruby def
# key: d
# --
def ${1:meth}`(def)`
```

### This `def` function, basically is a function to handle some language `(def-begining)`
`(def-end)`, e.g. should i insert a newline? or special keyword as `(def-end)`, mostly
those things, wrapper some if condition.
Fine, you could skip those description, Following is code, You could skip those if you want.
```cl
(defun def (&optional def-begin def-end single-line-end-seperator)
  (insert
   (concat
    (def-begin def-begin)
    "`(yas-stripped-selected-text)`$0"
    (def-end def-end single-line-end-seperator)
    )))
```

### Problem is, when I expand this snippet, it get the correct result in ruby-mode

Press `<d>` => `<TAB>` =>  `<TAB>`
```rb
def meth
   |                # <= cursor is here, with correct indent.
end
```
But for enh-ruby-mode, I get following:
```rb
def meth
|                 # <= cursor is here, not indent correct.
end
```

This not worked exactly in `enh-ruby-mode` and with `(insert)`

**Comment by zw963** [comment]
A little confusing .... Forget previous reply please

Following is a snippet use `(insert)`.

```cl
# -*- mode: snippet -*-
# name: def1
# key: def1
# --
def ${1:meth}`(insert (concat "\n" "$0" "\n"  "end"))`
```

In `(ruby-mode)`, it work fine. will expand to:

```rb
def meth
  |
end
```

in `(enh-ruby-mode)`,  not worked good, will expand to:
```rb
def meth
|
end
```

**Comment by npostavs** [comment]
> In `(ruby-mode)`, it work fine. will expand to:

I don't see a difference, in both `ruby-mode` and `enh-ruby-mode` the middle line is not indented. This is because yasnippet no longer indents empty lines (#685). You can fix it by adding a space before the `$0`:
```
# -*- mode: snippet -*-
# name: def1
# key: def1
# --
def ${1:meth}`(insert (concat "\n" " $0" "\n"  "end"))`
```

**Comment by ReneFroger** [comment]
I have the following function:

    (defun web-mode-fixcommenttag ()
    (if (string= (web-mode-language-at-pos) "html")
        (insert "<!--")
        (insert "/* ")) 
    )


The recent upgrade breaks this function. How could I insert the tags, without the need to have call `insert` function inside `web-mode-fix-commenttag`?

**Comment by npostavs** [comment]
Literally just remove the `insert`:
```elisp
(defun web-mode-fixcommenttag ()
  (if (string= (web-mode-language-at-pos) "html")
      "<!--"
    "/* "))
```

**Comment by zw963** [comment]
Noam Postavsky writes:

>     In (ruby-mode), it work fine. will expand to:
>
> I don't see a difference, in both ruby-mode and enh-ruby-mode the middle line
> is not indented. This is because yasnippet no longer indents empty lines (#685
> ). You can fix it by adding a space before the $0:
>
> # -*- mode: snippet -*-
> # name: def1
> # key: def1
> # --
> def ${1:meth}`(insert (concat "\n" " $0" "\n"  "end"))`
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*

Is there exist a toggle to enable/disable this behavior?

Thanks

-- 
Geek, Rubyist, Emacsen.
程序员中的牛逼运维， 运维中的牛逼程序员。

**Comment by npostavs** [comment]
No, I don't see a need because you can always just add a space to make the line non-empty.

**Comment by zw963** [comment]
>>  I don't see a difference, in both ruby-mode and enh-ruby-mode the middle line is not indented. 

@npostavs , Thank for point out this, I think maybe some others auto-indent package cause my
empty line is indented, Anywhy, I under the key. thanks.

**Comment by aninePang** [comment]
This is not a Bug!  like (insert (insert variable)) , this is worse write!

**Comment by npostavs** [comment]
@aninePang I don't understand what you mean.
