### ISSUE TITLE
Support: how to add a snippet that begins with '#'?

### ISSUE THREAD

**Issue by jarmitage** [joaotavora/yasnippet#715]
Hey, I want to add a snippet that begins with a '#' symbol, but in the `yas-new-snippet` buffer the snippet is greyed out like a comment. Is that just highlighting or will the snippet not work? Any pointers? Example:
```
# -*- mode: tidal-mode -*-
# name: sustain
# key: #s
# --
# sustain "$0"
```

Thanks

**Comment by npostavs** [comment]
Doesn't happen here. Can you reproduce this from [`emacs -Q`][emacs-Q]?

[emacs-Q]: http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html

**Comment by jarmitage** [comment]
Ok, the snippet actually works so maybe it's just my syntax highlighting setup? This is how it appears to me which is why I was confused: 

<img width="201" alt="2016-07-06 at 00 44 42" src="https://cloud.githubusercontent.com/assets/2885827/16603309/e684dc5c-4312-11e6-9dfd-9f410d7a2b30.png">

**Comment by npostavs** [comment]
Oh, sorry, I misread. I thought you said it was greyed out in the menu. Yes, it's just a weakness of the syntax highlighting. It will still work to load and expand the snippet though.
