### ISSUE TITLE
Snippet mode: "[yas] elisp error: Wrong type argument: arrayp, nil"

### ISSUE THREAD

**Issue by jarmitage** [joaotavora/yasnippet#716]
When doing `M-x yas-new-snippet`, I get this warning:

> Warning (yasnippet): `Snippet' modified buffer in a backquote expression.
> 	To hide this warning, add (yasnippet backquote-change) to `warning-suppress-types'.

I hit 'q' to close the warning, and then the snippet looks like this

```
# -*- mode: snippet -*-
# name:
# key:
# --
[yas] elisp error: Wrong type argument: arrayp, nil
```

I put this in my emacs config which gets rid of the warning, but not the elisp error:

```
(unless (boundp 'warning-suppress-types)
  (setq warning-suppress-types nil))
(push '(yasnippet backquote-change) warning-suppress-types)
```

This occurs irrespective of what mode I'm in when I create a new snippet.

Any ideas?

Thanks

**Comment by npostavs** [comment]
I think I fixed this last night. Can you try updating?

42b0c269caa01d397446ddf4c3c6936158c757d6
7661dc161d44c5baf49773ac1a9f31d264caa1ab

**Comment by jarmitage** [comment]
Seems to be fixed, thanks @npostavs 👍
