### ISSUE TITLE
Support: how to change yas-prompt-functions in manually added minor mode

### ISSUE THREAD

**Issue by jarmitage** [joaotavora/yasnippet#717]
I am using yas with [Tidal](http://github.com/tidalcycles/Tidal), so to get yas to work I have this in my .emacs:
```
(defun my-tidal-mode-hook ()
  (push 'ac-source-yasnippet ac-sources))
(add-hook 'tidal-mode-hook 'my-tidal-mode-hook)
```
I am now trying to change the prompt function to dropdown-list, using something like this:
```
(setq yas/prompt-functions
  `(yas/dropdown-prompt
    yas/ido-prompt
    yas/x-prompt
    yas/completing-prompt
    yas/no-prompt))
```
However the changes do not take place in tidal-mode. Changing prompt function in this way works in other modes like html-mode. Is there a particular way I am supposed to change the prompt function for this additional mode?

**Comment by npostavs** [comment]
The `yas-prompt-functions` variable is only consulted if you expand from a snippet key and there are multiple snippets with the same key, or if you use `yas-insert-snippet`. If you are using autocomplete to expand snippets, it has no effect.

Unless you are talking about a snippet that itself contains prompting code, like `yas-choose-value`?

**Comment by jarmitage** [comment]
Right!! I knew that but somehow got confused between them. Thanks for clarifying.

What I actually want then, is for the auto-complete popup to show yasnippet information, like e.g. the name field which is more descriptive than just the snippet key. I guess that's more of an auto-complete or popup.el question, right? Any tips for how I'd grab the info from a snippet? (or another approach entirely?)

**Comment by npostavs** [comment]
> I guess that's more of an auto-complete or popup.el question, right?

Well, it's a matter of integration between those and yasnippet. Similar to #540.

> Any tips for how I'd grab the info from a snippet? (or another approach entirely?)

Currently you would have to delve into the internal structures of yasnippet. See `(cl-defstruct (yas--template ...` for the individual snippet info fields.

**Comment by jarmitage** [comment]
Ok, is #540 a priority for you at this time? Otherwise yes it looks like a deep dive

**Comment by npostavs** [comment]
> Ok, is #540 a priority for you at this time?

I'm not planning to tackle it before the next release.

> Otherwise yes it looks like a deep dive

Since yasnippet currently lacks suitable APIs, you might find that ac-yasnippet has already done the difficult parts and you just need to add a `(yas--template-name snippet)` call in the right place.

**Comment by jarmitage** [comment]
Yeah, it sounds doable but I'm still a beginner so you might still get there before me :) thanks
