### ISSUE TITLE
Recent change breaks dabbrev-expand with mirrored text

### ISSUE THREAD

**Issue by jacott** [joaotavora/yasnippet#720]
Pressing M-/ when on a mirror field causes the cursor to be in wrong position.

The problem appears to be with  commit https://github.com/joaotavora/yasnippet/commit/d218ed8b1bf95809edc148e609c59b124598695d  by @joaotavora ; reversing this commit seems to fix the problem.

GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9)
 of 2016-04-18 on lgw01-04, modified by Debian

**Comment by npostavs** [comment]
I see it too, reduced to this non-yasnippet test-case:
```elisp
(defun 720-modification-hook (&rest _args)
  (let ((inhibit-modification-hooks t))
    (indent-according-to-mode)))

(defun 720-test ()
  (interactive)
  (with-current-buffer (get-buffer-create "*720 test*")
    (erase-buffer)
    (pop-to-buffer (current-buffer))
    (insert "\n") ; Significant!
    (let* ((p1 (point))
           (p2 (progn (insert "yyy") (point)))
           (ov (make-overlay p1 p2)))
      (insert "...")
      (overlay-put ov 'modification-hooks '(720-modification-hook))
      (overlay-put ov 'face 'highlight) ; Just for visualization.
      (goto-char p2)
      (search-backward "yyy")
      (replace-match "xxx"))))
```
possible this is an Emacs bug.

**Comment by npostavs** [comment]
Aha, ran with Emacs 25, and got `Match data clobbered by buffer modification hooks`, so we're probably just missing a `save-match-data`.

@jacott can you confirm that #721 fixes the problem for you?

**Comment by jacott** [comment]
Yes @npostavs, that fixes it;  thanks!

**Comment by joaotavora** [comment]
Nice on @npostavs !
