### ISSUE TITLE
yas/submenu

### ISSUE THREAD

**Issue by mattfidler** [joaotavora/yasnippet#723]
When I start yasnippet, some of my old snippets use `yas/submenu`.  This was replaced by `yas-submenu`, but the backward compatibility has dropped for some reason.  However, backward compatibility for the rest of the `yas/` family seems to still be present.  Is there a reason for this?

**Comment by npostavs** [comment]
You mean the elements passed to `yas-define-menu`? It's just because `yas-submenu` is not a function or variable I think, i.e., it was an oversight.

**Comment by npostavs** [comment]
Does #724 fix your snippets?

**Comment by mattfidler** [comment]
I'll check by tomorrow.  thanks you for the rapid reply and patch

**Comment by mattfidler** [comment]
Yes.  If I apply your patch, yasnippet doesn't complain when loading the old snippets.
