### ISSUE TITLE
"Warning (bytecomp): the following functions are not known to be defined" on launch

### ISSUE THREAD

**Issue by computersarecool** [joaotavora/yasnippet#726]
The first time I install `yas` using `package-install` I get the following:

`Warning (bytecomp): the following functions are not known to be defined: yas-substr, yas-choose-value`

It seems harmless but I am wonder what I could be doing to cause this warning and if there is a way to get rid of it.

Thanks

**Comment by npostavs** [comment]
I'm not seeing this warning. What are your Emacs and yasnippet versions?

Does the warning say which file it's coming from?

**Comment by computersarecool** [comment]
I am using emacs 24.3.1 and yas `yasnippet-20160801.1142`
It doesn't say where that warning is coming from, it only says that exact message.  however, it only appears after I do my first initialization (the package is installed from my `init.el` file

**Comment by npostavs** [comment]
I cloned your [dotemacs repo](https://github.com/computersarecool/dotemacs) and I got this in `*Compile-Log*`:
```
Compiling file /home/npostavs/tmp/scratch/.emacs.d/elpa/yasnippet-20160801.1142/snippets/c++-mode/.yas-setup.el at Tue Aug  2 19:27:10 2016
Entering directory `/home/npostavs/tmp/scratch/.emacs.d/elpa/yasnippet-20160801.1142/snippets/c++-mode/'

In end of data:
.yas-setup.el:11:1:Warning: the following functions are not known to be defined: yas-substr,
    yas-choose-value
Leaving directory `/home/npostavs/tmp/scratch/.emacs.d/elpa/yasnippet-20160801.1142/snippets/c++-mode/'
```

I was a bit surprised to see the `.yas-setup.el` files get compiled, but I guess they should have `(require 'yasnippet)` to silence these warnings.

**Comment by computersarecool** [comment]
I guess this issue should be closed.  I don't think it is a show-stopping problem, it is just a warning after all.

**Comment by npostavs** [comment]
I made a pull request to add `(require 'yasnippet)` to `c++-mode/.yas-setup.el`. Not sure how come you don't see the filename in your warning, but I hopefully that will fix it.

**Comment by npostavs** [comment]
> Not sure how come you don't see the filename in your warning, but I hopefully that will fix it.

Actually, this is probably from something else. I suggest adding `(debug-on-entry 'display-warning)` at the top of your init, that will give a backtrace to help figure out where it comes from.

**Comment by npostavs** [comment]
Anyway, I'm closing, since I think it unlikely that it's a yasnippet bug (but do post back if you find some evidence to the contrary).
