### ISSUE TITLE
Convert snippets to your brace style

### ISSUE THREAD

**Issue by u8y7541** [joaotavora/yasnippet#728]
In languages with braces some of the snippets have different bracing styles than others. There should be an option to convert the snippets to your bracing style so you don't have to change them manually after inserting a snippet.

This could either be implemented by converting using a procedural method or typing all of the snippets in different brace styles.

**Comment by npostavs** [comment]
> In languages with braces some of the snippets have different bracing styles than others.

You should open a PR at https://github.com/AndreaCrotti/yasnippet-snippets to fix this.

> This could either be implemented by converting using a procedural method

That would obviously be the better way of doing it, but I'd like to avoid having to parse arbitrary languages in yasnippet...

**Comment by joaotavora** [comment]
> This could either be implemented by converting using a procedural method

You can write arbitrary lisp code in yasnippet snippets using the `# type: command` directive. In that code, you can call `yas-expand-snippet`. 

Here's an example: https://github.com/joaotavora/yasnippet/issues/532#issuecomment-61984048

**Comment by npostavs** [comment]
You can get whatever brace style you like by calling [GNU indent](https://manned.org/indent.1) on snippet exit. I think this is about as much support as yasnippet should reasonably give for this.
```elisp
(setq yas-after-exit-snippet-hook
      (lambda ()
	;; Use GNU indent to reformat to preferred brace style.
	(shell-command-on-region
	 yas-snippet-beg yas-snippet-end
	 "indent" nil t)
	;; Since we don't give a whole program, GNU indent may have
	;; chosen an incorrect indentation, so reindent afterwards.
	(indent-region yas-snippet-beg yas-snippet-end)))
```
