### ISSUE TITLE
Is it possible to have aliases?

### ISSUE THREAD

**Issue by jave** [joaotavora/yasnippet#730]
Years ago I used msf-abbrev, and then i got into the habit of having abbreviations like "forx".

typing forx SPACE, would expand to a template that was mode specific, like a yas template

Is it possible to recreate this behaviour with yasnippet? that is, create a "forx" alias for a yasnippet template, that would expand automatically like abbrev does?

I suppose i could use symlinks to begin with, anf figure out how to integrate the abbrew and yasnippet packages, but surely this has already been done.

/Joakim

**Comment by npostavs** [comment]
> I suppose i could use symlinks to begin with,

I don't understand what the symlinks would be for.

> how to integrate the abbrew and yasnippet packages, but surely this has already been done.

No, but if you bind `yas-expand` to `SPC` the effect is quite similar to abbrev mode.

**Comment by jave** [comment]
Thanks for the suggestion regarding binding yas-expand to spc!

The symlinks would be used to create a primitive alias function. 

Lets say there are yas snippets out of the box for the keyword 'for' in C, Java, and bash.
in elisp I'd rather use a loop construct, say.

so I would symlink 'forx' to 'for', in C, java and bash.  For elisp, forx would point to loop.

Rather than symlinks I would like to use a lisp construct.

**Comment by npostavs** [comment]
By "aliases" do you really mean multiple trigger keys for the same snippet? See #729 and #114.

**Comment by jave** [comment]
Probably, yes.
