### ISSUE TITLE
Is it possible to share snippet between different but similar modes?

### ISSUE THREAD

**Issue by eddeyang** [joaotavora/yasnippet#731]
I want to know is it possible to share snippets between different but similar modes. Like we have emacs-lisp-mode, lisp-mode, common-lisp-mode etc. Some snippets should work in all those modes. Is it possible?

**Comment by npostavs** [comment]
Yes, you can put all the snippets into a comment mode in your snippet collection and that mode to the [.yas-parents](http://joaotavora.github.io/yasnippet/snippet-organization.html#sec-3) file for each mode where you want it to be active.
