### ISSUE TITLE
second new created snippet can't save to new snippet file

### ISSUE THREAD

**Issue by stardiviner** [joaotavora/yasnippet#733]
I tested this issue in `emacs -q`:
Here are steps to repeat the situation.
1. `C-c & C-n` to create a new snippet.
2. `C-c C-c` to save to a new snippet file.
3. `C-c & C-n` again to create another new snippet.
4. `C-c C-c` to save, but it will save to previous snippet file without prompt
   for snippet file name.
5. the following steps happens always until I do =yas-reload-all=.

**Comment by npostavs** [comment]
Confirmed, thanks for reporting! I was thinking about making a release soon, would have been unfortunate to release with broken snippet saving.

**Comment by npostavs** [comment]
Should be fixed by #734.
