### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by DamienCassou** [joaotavora/yasnippet#736]
This has been a few months that the latest release went out. Is it time for a new release? Thanks.

**Comment by npostavs** [comment]
Yes, just about. Have to take care of #734 first.

**Comment by phst** [comment]
Hi, since https://github.com/joaotavora/yasnippet/pull/734 is now merged, just wanted to ask about the new release. Thanks!

**Comment by npostavs** [comment]
Assuming nothing comes up before then, I will make a new release on Sunday (see #740).

**Comment by npostavs** [comment]
Nothing came up in yasnippet, but the ralloc troubles in emacs sucked up my free coding time, so this will have to wait another day or two.
