### ISSUE TITLE
Inconrect indentation

### ISSUE THREAD

**Issue by PierreTechoueyres** [joaotavora/yasnippet#739]
I try to template some snippets for my use on SQL buffers but the result is always incorrectly indented.
The snippet is :

```
# -*- mode: snippet; coding: utf-8-unix -*-
# name: function ... return boolean
# key: fctb
# expand-env: ((yas-indent-line 'fixed) (yas-wrap-around-region nil))
# --
-------------------------------------------------------------------------------
-- NOM  : ${1:nom fonction}
-- CRE  : `(capitalize (format-time-string "%d/%m/%Y"))`
-- AUT  : `(and (boundp 'user-ngram) user-ngram)`
-------------------------------------------------------------------------------
-- ARG  :
-- - $3
-------------------------------------------------------------------------------
-- RET  : ${4:retours}
-------------------------------------------------------------------------------
-- DESC : ${5:description}
-------------------------------------------------------------------------------
FUNCTION $1(${3:param})
RETURN   BOOLEAN IS
  v_resultat BOOLEAN := TRUE;
BEGIN
  pck_trace.trc_add( '${2:nom paquetage}',
                        '$1 - Début' || lf
                     || '$3 => ' || $3);
  $0
  if v_resultat then
    pck_trace.trc_add('$2', '$1 - Fin' || lf
                   || 'v_resultat => TRUE');
  else
    pck_trace.trc_add('$2', '$1 - Fin' || lf
                   || 'v_resultat => FALSE');
  end if;
  return v_resultat;
END $1;
```

And the result after expansion is :

```
-------------------------------------------------------------------------------
-- NOM  : function_name
-- CRE  : 20/10/2016
-- AUT  : 
-------------------------------------------------------------------------------
-- ARG  :
-- - param1
-------------------------------------------------------------------------------
-- RET  : return
-------------------------------------------------------------------------------
-- DESC : description
-------------------------------------------------------------------------------
FUNCTION function_name(param1)
RETURN   BOOLEAN IS
  v_resultat BOOLEAN := TRUE;
BEGIN
  pck_trace.trc_add( 'package_name',
  'function_name - Début' || lf
  || 'param1 => ' || param1);

  if v_resultat then
  pck_trace.trc_add('package_name', 'function_name - Fin' || lf
                   || 'v_resultat => TRUE');
  else
  pck_trace.trc_add('package_name', 'function_name - Fin' || lf
                   || 'v_resultat => FALSE');
  end if;
  return v_resultat;
  END function_name;
```

any clues ?

[dummy.sql.txt](https://github.com/joaotavora/yasnippet/files/542860/dummy.sql.txt)

[Uploading dummy.sql.txt…]()

**Comment by npostavs** [comment]
Seems to be a bug, related to field mirrors, if I remove the `$2` and `$1` from those lines, then the indentation is correct.

**Comment by PierreTechoueyres** [comment]
What can I do to help ?

**Comment by npostavs** [comment]
If you want to try making a patch, I think the solution would be to make the `yas--indent-region` call in `yas--mirror-update-display` be condition on the value of `yas-indent-line`. Althought I'm not sure if the snippet's bindings remain in effect after the initial expansion, so there might be an addtional indentation problems when you modify the field values.

**Comment by npostavs** [comment]
> not sure if the snippet's bindings remain in effect after the initial expansion, so there might be an addtional indentation problems when you modify the field values.

It indeed only works for initial expansion, see #743. Figuring out how to fix this properly looks to be quite tricky.

**Comment by npostavs** [comment]
@PierreTechoueyres I've update the fix #743, can you try it out?

**Comment by PierreTechoueyres** [comment]
@npostavs Yeah it work ! Thanks !
I've just done one test. Will try it more hardly this week.
One minor thing : the expansion add spurious spaces on last line of the snippet. Anyway I can live with this.

**Comment by npostavs** [comment]
> One minor thing : the expansion add spurious spaces on last line of the snippet.

I don't see that here. Is it possible you left some spaces in the snippet text itself?

**Comment by PierreTechoueyres** [comment]
No, but the last line of the snippet has an extra line. This one get the extra spaces when the snippet is expanded on column > 1

**Comment by npostavs** [comment]
> No, but the last line of the snippet has an extra line. This one get the extra spaces when the snippet is expanded on column > 1

Ah, I think that's the expected behaviour of `(yas-indent-line 'fixed)`. Every line, including blank ones, gets indented by the initial column amount.

**Comment by PierreTechoueyres** [comment]
Oh, sorry, I missed that point.
My uses cases are special. I set `(yas-indent-line 'fixed)` because the auto-indent doesn't work well for `sql-mode`. I'll try without `(yas-indent-line 'fixed)` to see if you patch changed something for the other indent values.

**Comment by PierreTechoueyres** [comment]
I've used the modification and all seems to work as expected thanks a lot.

**Comment by npostavs** [comment]
> My uses cases are special. I set `(yas-indent-line 'fixed)` because the auto-indent doesn't work well for `sql-mode`. I'll try without `(yas-indent-line 'fixed)` to see if you patch changed something for the other indent values.

If you have any snippets that have trouble with auto-indent please post them, it might be fixed by #755, and it could make an interesting test case regardless.

**Comment by PierreTechoueyres** [comment]
The same snippets without the `(yas-indent-line 'fixed)` and I started emacs as `emacs -Q`, then
```
(add-to-list 'load-path (expand-file-name "~/.emacs.d/elpa-25/yasnippet-20161202.1700"))
(load-file "~/.emacs.d/elpa-25/yasnippet-20161202.1700/yasnippet-autoloads.el")
(yas-global-mode)
(yas-reload-all)
```
then create an sql buffer and choose Oracle product (Menu SQL->Product->Oracle)
The result is :
```
-------------------------------------------------------------------------------
-- NOM  : nom fonction
-- CRE  : 09/12/2016
-- AUT  : 
-------------------------------------------------------------------------------
-- ARG  :
-- - param
-------------------------------------------------------------------------------
-- RET  : VRAI si tout c'est bien passé FAUX sinon + alim pck_err
-------------------------------------------------------------------------------
-- DESC : description
-------------------------------------------------------------------------------
FUNCTION nom fonction(param)
RETURN   BOOLEAN IS
v_resultat BOOLEAN := TRUE;
BEGIN
pck_trace.trc_add( 'nom paquetage',
'nom fonction - Début' || lf
|| 'param => ' || param);

if v_resultat then
pck_trace.trc_add('nom paquetage', 'nom fonction - Fin' || lf
|| 'v_resultat => TRUE');
else
pck_trace.trc_add('nom paquetage', 'nom fonction - Fin' || lf
|| 'v_resultat => FALSE');
end if;
return v_resultat;
END nom fonction;
```

**Comment by npostavs** [comment]
Oh, the problem is that `sql-mode` doesn't have a mode-specific `indent-line-function`, it just uses `indent-relative` so auto indenting can't really work. 

If you take your nicely indented code and do <kbd>C-M-\\</kbd> (`indent-region`) on it, then you will see it all gets indented to the same column as you've shown above. It's nothing that can be fixed by yasnippet.

**Comment by PierreTechoueyres** [comment]
You're right (as always). So I'll keep using `(yas-indent-line 'fixed)` for my sql snippets.
Many thanks for solving this bug.
