### ISSUE TITLE
Importing vim-snippets

### ISSUE THREAD

**Issue by lpil** [joaotavora/yasnippet#741]
Hello!

For the last few years I've been using an maintaining a large collection of snippets for vim snippet plugins -> https://github.com/honza/vim-snippets

I'm now dipping my toe into the emacs world, and would love to be able to continue to use and maintain these snippets. Is there a way to import these snippets and use them with yasnippet?

Thanks,
Louis

**Comment by npostavs** [comment]
A web search turned up https://github.com/cartolari/snipmate_to_yas

> # SnipmateToYas
> 
> This gem converts [SnipMate](https://github.com/garbas/vim-snipmate) snippets
> into [YASnippet](https://github.com/capitaomorte/yasnippet) snippets.
> 
> _For a repository with already converted snippets please check
> [yasnippet-vim-snippets](https://github.com/cartolari/yasnippet-vim-snippets)._
> 
> This gem was built mostly to convert the
> [vim-snippets](https://github.com/honza/vim-snippets) library to a format
> compatible with Emacs but it works with any Snipmate snippet.

**Comment by lpil** [comment]
Ideally the plugin would be capable of reading the same format, otherwise I would have to re-transpile the snippets every time the vim format ones are updated.

**Comment by npostavs** [comment]
Looking at https://github.com/cartolari/snipmate_to_yas#how-the-snippets-get-converted, it doesn't look like the kind of conversion that can be handled 100% automatically anyway.

> 
> The mode names are not always equal, for example in Vim we have the cpp-mode while in Emacs we have the c++-mode. So the snippets from a file called cpp.snippets would be saved in a folder called c++-mode and not cpp-mode.
> 
> The snippet interpolations in SnipMate use vim-script, while the interpolations in YASnippet use Elisp. This is handled by this script in a extremely simple way, but most interpolations should work. If you found some error please let me know.

**Comment by lpil** [comment]
The vast majority of snippets don't use any code, and those that do could be discarded. Matching up names would be trickier.

It seems this is currently a non-trivial problem. Perhaps this could be my first elisp learning project :)

Thanks for the help!

**Comment by npostavs** [comment]
> It seems this is currently a non-trivial problem.

Indeed.

> Perhaps this could be my first elisp learning project :)

Sounds like a reasonable goal. I'm closing this issue now, but feel free to keep posting if you have any questions.
