### ISSUE TITLE
yas-minor-mode failes to load for html-mode

### ISSUE THREAD

**Issue by outsinre** [joaotavora/yasnippet#749]
Emacs:

    GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.20.9) of 2016-10-23

Yasnippet:

    0.11.0

```elisp
;; In *scratch* buffer:
(add-to-list 'load-path "~/.emacs.d/elpa/yasnippet-0.11.0/")
(require 'yasnippet)
;; per-buffer basis
(yas-reload-all)
(add-hook 'prog-mode-hook #'yas-minor-mode)
```

Reproduce:

1. `emacs -Q`;
2. M-x: `eval-buffer`;
3. Open a *.html* file;
4. *yas-minor-mode* does **NOT** load.

   Have to M-x: `yas-minor-mode` manually.

**Comment by npostavs** [comment]
> `(add-hook 'prog-mode-hook #'yas-minor-mode)`

`html-mode` doesn't derive from `prog-mode`, it derives from `text-mode` (via `sgml-mode`).

**Comment by outsinre** [comment]
@npostavs Many thanks. I will stick to the *yas-global-mode* instead.

**Comment by npostavs** [comment]
Was there a reason for not using `yas-global-mode` in the first place?

**Comment by outsinre** [comment]
@npostavs currently No. But if use `yas-global-mode`, *C-h m* on startup shows two Yasnippet modes, namely `yas` and `Yas-Global`. Why `yas` stick there since global mode is on?

**Comment by npostavs** [comment]
This seems to be a side effect of the `define-globalized-minor-mode`'s implementation.

**Comment by outsinre** [comment]
@npostavs Thanks. You tell me.
