### ISSUE TITLE
Uses obsolete `assoc' package

### ISSUE THREAD

**Issue by spwhitton** [joaotavora/yasnippet#751]
Dear maintainer,

yasnippet still uses `assoc`, which Emacs complains about when yasnippet is loaded:

    Package assoc is obsolete!

Thanks.

**Comment by npostavs** [comment]
Um, no it doesn't. Not as far as I know.

**Comment by npostavs** [comment]
Ah, looking at the [yasnippet Debian package page](https://packages.debian.org/search?keywords=yasnippet) I see you're still on 0.9.0. There was an accidental use of `aget` around that time. I recommend you upgrade to at least 0.9.1.

Refer: #344 and #242.

**Comment by spwhitton** [comment]
Thanks for looking into this.  We're actually on 0.11.0, but it's stuck in one of our archive upload queues so you wouldn't see it on that page.  On a system with the yasnippet 0.11.0 package installed, I saw `Package assoc is obsolete!` after I typed `M-x yas-global-mode`.

**Comment by npostavs** [comment]
> On a system with the yasnippet 0.11.0 package installed, I saw `Package assoc is obsolete!` after I typed `M-x yas-global-mode`.

Hmm, I don't think that's from yasnippet's code. Can you get a backtrace with `M-x debug-on-entry do-after-load-evaluation`?

**Comment by spwhitton** [comment]
Thanks for the debugging hint!  It is, indeed, not coming from yasnippet.

-- 
Sean Whitton
