### ISSUE TITLE
Uses obsolete `flet'

### ISSUE THREAD

**Issue by spwhitton** [joaotavora/yasnippet#752]
Dear maintainer,

yasnippet uses `flet` in `yas-doc-helper.el`.  This causes Emacs to complain:

    `flet' is an obsolete macro (as of 24.3); use either `cl-flet' or `cl-letf'.

Thanks.

**Comment by npostavs** [comment]
`yas-doc-helper.el` is only for maintainers, but that `flet` was pretty useless anyway.
