### ISSUE TITLE
yasnippet modifies buffer while inhibit-modification-hooks is t

### ISSUE THREAD

**Issue by phillord** [joaotavora/yasnippet#756]
The mechanism that yasnippet uses for changing fields means that it changes the buffer while `inhibit-modification-hooks` is `t`, if I am reading the code correctly. This means that any other code which depends on these hooks to identify change fails. This happens in the `yas--on-field-overlay-modification` function.

As an example, it causes a bad interaction with lentic mode https://github.com/phillord/lentic/issues/51.

I'm not sure what the obvious fix is -- probably using `post-command-hook` rather than "modification-hook" to trigger the changes,

**Comment by npostavs** [comment]
I think it's to avoid recursion. Possibly we should bind `yas--inhibit-overlay-hooks` instead of `inhibit-modification-hooks`, i.e., only stop ourselves from recursive modification, not others.

**Comment by phillord** [comment]
AFAICT, the `let` binding of `inhibit-modification-hooks` makes no difference, as it happens (I already tried removing it!). Emacs itself appears to be already binding this variable to t when it calling the overlay modification hooks. I am checking up that this is the case for sure.

Ironically, `let` binding `inhibit-modification-hooks` to nil solves my problem.

**Comment by npostavs** [comment]
Ah. Probably only recording the changes in the after-change function and then performing them in the post command hook is the best solution then.

**Comment by phillord** [comment]
Yes. You might not even need the modification-hook, to be honest -- you can use post-command-hook to check for the overlay.

I've submitted a bug to Emacs also. (bug#25111). Let's wait till and see whether there is a better solution in the response to that; switching `inhibit-modification-hooks` to `nil` is clearly the simplest solution, although the documentation says to do precisely the opposite.

If not, I'll be happy to send a PR using `post-command-hook`.

**Comment by npostavs** [comment]
> You might not even need the modification-hook, to be honest -- you can use post-command-hook to check for the overlay.

It's mostly an optimization to avoid unneeded mirror updates, but I think modification-hook would still be necessary for the `yas--skip-and-clear-field-p` part.

**Comment by npostavs** [comment]
> Probably only recording the changes in the after-change function and then performing them in the post command hook is the best solution then.

Turns out this breaks things, it's hard to say why exactly. Does the following work okay? (I tried installing lentic, but I couldn't figure out how to run the example)

```diff
--- w/yasnippet.el
+++ i/yasnippet.el
@@ -3533,9 +3533,10 @@ (defun yas--on-field-overlay-modification (overlay after? beg end &optional leng
   (unless (or (not after?)
               yas--inhibit-overlay-hooks
               (not (overlayp yas--active-field-overlay)) ; Avoid Emacs bug #21824.
               (yas--undo-in-progress))
-    (let* ((inhibit-modification-hooks t)
+    (let* ((inhibit-modification-hooks nil)
+           (yas--inhibit-overlay-hooks t)
            (field (overlay-get overlay 'yas--field))
            (snippet (overlay-get yas--active-field-overlay 'yas--snippet)))
       (save-match-data
         (yas--letenv (yas--snippet-expand-env snippet)
```

**Comment by phillord** [comment]
Apologies for the tardy reply. I missed the original notification.Yes, this patch does work. 

Sorry, you had problems with getting lentic to work. Easiest way is to open a buffer, and do M-x lentic-mode-create-new-view-in-selected-window. You get what looks like an indirect buffer with the same contents as the original file, but with different point and in which you can change mode freely.

**Comment by npostavs** [comment]
Thanks for confirming.

> M-x lentic-mode-create-new-view-in-selected-window.

Ah thanks, I can reproduce the original bug with the old yasnippet version following this.
