### ISSUE TITLE
yas--fallback: yasnippet fallback loop! 

### ISSUE THREAD

**Issue by xiaoxinyi** [joaotavora/yasnippet#763]
I setup with `emacs -q`.

The only configuration is as follows:
```
(use-package yasnippet
  :bind(:map
	yas-minor-mode-map ("<backtab>" . yas-expand))
  :config
  (yas-global-mode 1)
  (setq yas-snippet-dirs
	'("~/.emacs.d/snippets"))
  )
```
When I type `<backtab>` to expand snippet, message shows:
```
yas--fallback: yasnippet fallback loop!
This can happen when you bind ‘yas-expand’ outside of the ‘yas-minor-mode-map’.
```

**Comment by npostavs** [comment]
> The only configuration is as follows:

That can't be your only configuration, because that wouldn't activate yasnippet at all.

**Comment by xiaoxinyi** [comment]
@npostavs I setup emacs with `emacs -q` and only activate 
```
(package-initialize)

(eval-when-compile
  (require 'use-package))
```

Then I execute the `use-package` macro
```
(use-package yasnippet
  :bind(:map
	yas-minor-mode-map ("<backtab>" . yas-expand))
  :config
  (yas-global-mode 1)
  (setq yas-snippet-dirs
	'("~/.emacs.d/snippets"))
  )
```
That's what I've done with my configuration.

**Comment by npostavs** [comment]
I guess you must have some other packages doing something funny when they're initalized. Can you try with
```elisp
(setq package-load-list '((yasnippet t) (use-package t)))
(package-initialize)

(eval-when-compile
  (require 'use-package))

(use-package yasnippet
  :bind(:map
	yas-minor-mode-map ("<backtab>" . yas-expand))
  :config
  (yas-global-mode 1)
  (setq yas-snippet-dirs
	'("~/.emacs.d/snippets"))
  )
```

**Comment by xiaoxinyi** [comment]
@npostavs  Thanks.
I use following code enable `yas-snippet`.
```
(setq package-load-list '((yasnippet t)
			  (use-package t)
			  (bind-key t)
			  (diminish t)
			  ))
(package-initialize)
(eval-when-compile
  (require 'use-package))

(use-package yasnippet
  :bind(:map
	yas-minor-mode-map ("<backtab>" . yas-expand))
  :config
  (yas-global-mode 1)
  (setq yas-snippet-dirs
	'("~/.emacs.d/snippets"))
  )

```
I want to expand `kbd` in `*scratch*` buffer with `yas-expand` , but it does not work as expected.

**Comment by npostavs** [comment]
> but it does not work as expected.

What happens?

**Comment by xiaoxinyi** [comment]
> What happens?
It does not expand `kbd`.

**Comment by npostavs** [comment]
What happens instead? Where and what is the definition of `kbd`?

**Comment by xiaoxinyi** [comment]
> What happens instead? Where and what is the definition of kbd?

`kbd` is from `elpa/yasnippet-20161201.1520/snippets/emacs-lisp-mode/kbd`

```
 #name: kbd
 #key: kbd
 # --
 (kbd "$0")
```

**Comment by xiaoxinyi** [comment]
1. `yas-new-snippet`  `hk`
```
# name: hk
# key: hk
# --
hello kitty!
```
2. save this new snippet in `~/.emacs.d/snippets`.

3. `yas-reload-all`

4. In `*scratch*` buffer, type `hk`, but it didn't work.

**Comment by npostavs** [comment]
Please post the contents of `*Messages*` after you've done this.

**Comment by xiaoxinyi** [comment]
@npostavs In `*Messages*` buffer, it reports nothing.

All the snippets in `elpa/yasnippet-20161201.1520/snippets/emacs-lisp-mode/` works well in `*scratch*` buffer now.

Variable `yas-snippet-dirs`'s value  `("~/.emacs.d/snippets" yas-installed-snippets-dir)`.

**Comment by npostavs** [comment]
> In `*Messages*` buffer, it reports nothing.

There should at least be messages about saving the snippet file? Or else you didn't save the snippet, which would explain why it doesn't work...

**Comment by xiaoxinyi** [comment]
`*Messages*` buffer 
```
Saving file ~/.emacs.d/snippets/hk...
Wrote ~/.emacs.d/snippets/hk
Quit
Making completion list...
[yas] Snippets loaded successfully.

```

**Comment by npostavs** [comment]
Ah, you saved at the top level of snippets, so it's not active in any mode (the prompt should default to the mode you created the snippet from, e.g., `~/.emacs.d/snippets/lisp-interaction-mode/` if you did `yas-new-snippet` from `*scratch*`).

**Comment by xiaoxinyi** [comment]
If I want use this snippet anywhere globally , how to do it?

**Comment by npostavs** [comment]
Save the snippet under `~/.emacs.d/snippets/fundamental-mode/`, and also add a `~/.emacs.d/snippets/prog-mode/.yas-parents` file with contents `fundamental-mode`.

**Comment by xiaoxinyi** [comment]
@npostavs Thanks!
