### ISSUE TITLE
How can I use 'c-p c-n' to chose fields value from a list

### ISSUE THREAD

**Issue by swors** [joaotavora/yasnippet#764]
xxx ${1:$$(yas-choose-value '("yyy" "zzz"))};

By default, I can use arrow keys to chose fields. But can I use "c-p c-n" or "y z" to switch?

**Comment by npostavs** [comment]
It depends entirely on the prompting method you're using (as given by `yas-prompt-functions`).

**Comment by npostavs** [comment]
But assuming you don't have `dropdown-list` installed, the default is `yas-completing-prompt` which uses `completing-read`. That supports `M-p` and `M-n`.
