### ISSUE TITLE
No expansion below single " (double-quote) in Org mode

### ISSUE THREAD

**Issue by mankoff** [joaotavora/yasnippet#765]
If the following text is in an Org file, I can expand snippets above but not below.

    X"Y

Similar text, such as `X\"Y` is valid LaTeX code to produce `XŸ`, which means `X"Y` is also valid Org syntax, but it breaks yasnippet.

Emacs: 25.1.91.1 (`emacs-mac` version HEAD as of today).
yasnippet: 20161221.1953 via elpa.

**Comment by npostavs** [comment]
This is because `"` has string syntax in `org-mode` and the default `yas-buffer-local-condition` disables expansion. You can change it with `(setq yas-buffer-local-condition t)`.

Although it doesn't seem right `"` has string syntax.
