### ISSUE TITLE
Variadics snippets?

### ISSUE THREAD

**Issue by quicknir** [joaotavora/yasnippet#766]
Hello, my question is whether it is possible to have a snippet with a variadic number of mirrors. Consider for instance the following:

```
class Foo(Object):
    def __init__(self, bar, baz, qux):
        self.bar = bar
        self.baz = baz
        self.qux = qux
```

We can see that bar, baz and qux are repeated in 3 places and hence this thing would perhaps lend itself nicely to a snippet. However, the number of arguments to a python class is just arbitrary. Is there any way to write a snippet that lets you generate this code with arbitrary numbers of arguments?

**Comment by npostavs** [comment]
> whether it is possible to have a snippet with a variadic number of mirrors.

You might be able to that with a `# type: command` snippet (this let's you run arbitrary lisp, which could call `yas-expand` with a generated string). But instead you could use one mirror which handles any number of python arguments:

```
# name : class-766
# key : class
# --
class Foo (Object):
    def __init__(self, $1):
         ${1:$(mapconcat (lambda (f) (concat "self." f " = " f))
                         (split-string yas-text " *," t " *") "\n")}
```
