### ISSUE TITLE
automatically avoid extraneous newlines

### ISSUE THREAD

**Issue by holocronweaver** [joaotavora/yasnippet#767]
As per #365 and #192, a fairly generic Emacs setup with `mode-require-final-newline` set to 1 causes `snippet-mode` to include extra newlines, much to the chagrin of a new user like myself.

My understanding is the general workaround is to add a mode hook:
`(defun fix-snippet-mode()
    (setq require-final-newline nil))
  (add-hook 'snippet-mode-hook #'fix-snippet-mode)`

But why does snippet mode use `mode-require-final-newline` at all? Wouldn't it be better for `snippet-mode` set `require-final-newline` to `nil` by default and avoid the headache for new users?

**Comment by holocronweaver** [comment]
After looking at yasnippet source, it seems `snippet-mode` does try to set require-final-newline to nil, yet I am still getting extra newlines inserted at the end of my snippets. Is it the expansion of the snippet that is causing the issue, and not the snippet file?

**Comment by npostavs** [comment]
Do the files themselves end with newlines? Can you reproduce this starting from [`emacs -Q`][emacs-Q]?

[emacs-Q]: http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html

**Comment by holocronweaver** [comment]
Figured out what was happening! I was editing some of my snippets in `text-mode` because I accidentally left out the the mode file header. That mode respects `mode-require-final-newline`, which in my case is `t` and hence newlines were being inserted when I saved. Switching to `snippet-mode` did not help since it can't presume trailing newlines are accidental and thus can't trim them.

For anyone experiencing this problem in the future, be sure to only edit your snippets in `snippet-mode`! And if you use another mode, be sure to switch to `snippet-mode` (or locally set `require-final-newline` to `nil`) and then remove the trailing newlines by hand.

I thought I had removed all the trailing newlines, but when I saved in `text-mode` the `require-final-newline` flag was causing them to be added back, doh!

**Comment by holocronweaver** [comment]
Thanks to @npostavs for making me second guess myself about the file endings. That was the key.

**Comment by npostavs** [comment]
Hmm, I wonder if it's worth doing something like:
```elisp
(add-to-list
 'magic-fallback-mode-alist
 `(,(lambda () (when buffer-file-name
		 (member
		  (expand-file-name
		   ".."
		   (file-name-directory buffer-file-name))
		  (yas-snippet-dirs))))
   . snippet-mode))
```
to avoid this kind of thing.

**Comment by holocronweaver** [comment]
That would certainly help in a majority of these 'whoops' cases. I added it to my config and it worked as intended, even on files without the magic mode header. Seems worth adding to yasnippet.

**Comment by npostavs** [comment]
Done: 9abf842e356e7b42fa105fe6284fb5ebe58a7ed1

> it worked as intended, even on files without the magic mode header.

Yeah, I'm abusing `magic-fallback-mode-alist` because `auto-mode-alist` only supports regexp matchers. But it works to add this to `magic-fallback-mode-alist` even though it's actually checking the file name, and not any magic number.

**Comment by joaotavora** [comment]
`</lurk>` Hmmm, seems a bit too clever for me, but what the heck, I can't think of anything against this... :-) plus it has happened to me too... `<lurk>`

**Comment by azzamsa** [comment]
> Do the files themselves end with newlines?

removing the new line solve my problem.
