### ISSUE TITLE
Yas not expanding in Org mode

### ISSUE THREAD

**Issue by mankoff** [joaotavora/yasnippet#770]
I'm using Org 9.0.4 and the latest elpa yas version which is

    yas--version is a variable defined in ‘yasnippet.el’.
    Its value is "0.11.0"

in the folder `yasnippet-20170127.2128` in elpa.

Nothing expands! 

`<tab>` does run `yas-expand`. When I look at the help for that function, and explore, I find that `yas-fallback-behavior` but that function reports,
```
yas-fallback-behavior is a variable defined in ‘yasnippet.el’.
Its value is ‘return-nil’

  This variable is obsolete since 0.12;
  For `call-other-command' behavior bind to the conditional
command value `yas-maybe-expand', for `return-nil' behavior bind
directly to `yas-expand'.
```

I don't know if this has something to do with the bug I'm experiencing, but I'm using version `0.11`, yet the code is warning of variables obsolete in version `0.12`. If I revert to a backup version of yasnippet from a few weeks ago, everything works.

**Comment by npostavs** [comment]
> `<tab>` does run `yas-expand`.

Can you reproduce this from [`emacs -Q`][emacs-Q]? I think by default you wouldn't see that binding unless expansion was working. What Emacs version are you using?

[emacs-Q]: http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html

> I'm using version 0.11, yet the code is warning of variables obsolete in version 0.12

`yasnippet-20170127.2128` is a snapshot version between 0.11 and (the not yet released) 0.12.

**Comment by mankoff** [comment]
Not a bug w/ `emacs -Q`. I'll try to figure out what in my config is causing this. Sorry for the noise.

**Comment by npostavs** [comment]
It's likely that the recent changes in #760 broke your configuration.

**Comment by mankoff** [comment]
Oops! I was using the "working" yasnippet: 0.11. This bug does exist with the following config file:

`open --new -a Emacs.app --args -Q --load ~/.emacs.d/DEBUG.el` where `DEBUG.el` contains:

```
(package-initialize)

(use-package yasnippet
  :if (not noninteractive)
  ;;:diminish yas-minor-mode
  :config (progn
	    (yas-reload-all)
            (yas-global-mode t)
	    (yas-minor-mode)
	    (define-key yas-minor-mode-map (kbd "<tab>") 'yas-expand)
	    (define-key yas-minor-mode-map (kbd "TAB") nil)))
```

If I use a simpler config:

```
(require 'yasnippet)
(yas-global-mode 1)
```

Then it works. But my version worked until a few weeks ago, and it appears the issue is recent changes to yasnippet, not something else. I'll clean up my config for now, but any advice about why my config was/is incorrect will be much appreciated.

**Comment by npostavs** [comment]
> This bug does exist with the following config file:

I'm not able to reproduce, perhaps some other packages are causing this? Does it happen also if you use

```elisp
(setq package-load-list '((use-package t) (bind-key t) (diminish t) (yasnippet t)))
(package-initialize)
(use-package yasnippet
;;etc...
```

> I'll clean up my config for now, but any advice about why my config was/is incorrect will be much appreciated.

Your config has some redundancy, and `(define-key yas-minor-mode-map (kbd "<tab>") 'yas-expand)` will put you back to using the old 0.11 style of binding, but it shouldn't break things.

The simpler config below should do the same (I'm not sure why you need to unbind `"TAB"` though?)

```elisp
(use-package yasnippet
  :if (not noninteractive)
  :config (progn
            (yas-global-mode t)
	    (define-key yas-minor-mode-map (kbd "TAB") nil)))
```

**Comment by mankoff** [comment]
OK. Seems to be a config bug. Thanks for the advice on the config.
