### ISSUE TITLE
Some whitespace gets lost when snippet is inserted

### ISSUE THREAD

**Issue by kynnjo** [joaotavora/yasnippet#771]
Observed in `sh-mode`, but may be more general than that.

Minimal example:

    # -*- mode: snippet -*-
    # name: ws-bug
    # key: ws-bug
    # --
        #

        #

When the snippet is inserted, the result looks like this:

        #

    #

Emacs version: GNU Emacs 25.1.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.25) of 2016-02-14
yasnippet.el version: 0.11.0

**Comment by npostavs** [comment]
That's because the snippet gets indented after insertion. If you don't want that then bind `yas-indent-line` to `fixed` or `nil`. Or if you want the first line to be consistent with the others, set `yas-also-auto-indent-first-line` to `t`.

**Comment by kynnjo** [comment]
thanks; sorry for the false alarm
