### ISSUE TITLE
Not expand in ruby mode double quotes string. Thanks

### ISSUE THREAD

**Issue by zw963** [joaotavora/yasnippet#773]
Following snippets not worked when I update into new version.

```el
# -*- mode: snippet -*-
# name: ruby #{...}
# key: ruby string interpolated
# binding: #
# condition: (yas-in-interpolated-string-p)
# expand-env: ((yas-indent-line 'fixed))
# --
#`(key-field "1" "exp" "{" "}")`
```

What I expect is when I in following rb file
```rb
"|"
```

if I press `#`, will expand to
```rb
"#{}"
```
This should only worked when cursor in a string, not outside.

But, current, it expand only if I remove condition. (outside string was work)

**Comment by npostavs** [comment]
Could you post the definition of `yas-in-interpolated-string-p` and the value of `yas-buffer-local-condition?

**Comment by zw963** [comment]
> Could you post the definition of yas-in-interpolated-string-p and the value of yas-buffer-local-condition?

```el
(defun in-interpolated-string-p ()
  (member (fourth (syntax-ppss)) (list ?\" ?\` ?/)))

(yas-define-condition-cache yas-in-interpolated-string-p (in-interpolated-string-p))
```

**Comment by zw963** [comment]
@npostavs , Hi, I think it not relation to `condition:`, following snippet only expand
when not in string, in string, just output a `#`.

the condition just for not expand when outside a string, but, current issue is
not expand in a string.

```el
# -*- mode: snippet -*-
# name: ruby #{...}
# key: ruby string interpolated
# binding: #
# expand-env: ((yas-indent-line 'fixed))
# --
#`(key-field "1" "exp" "{" "}")`
```

ruby file:

```rb
#{exp}
"#"
```

**Comment by npostavs** [comment]
Does it work if you `(setq yas-buffer-local-condition t)`?

**Comment by zw963** [comment]
> Does it work if you (setq yas-buffer-local-condition t)?

Worked! Thanks very much. though, I don't know why this work. : (

**Comment by npostavs** [comment]
> Thanks very much. though, I don't know why this work. : (

The default value for `yas-buffer-local-condition` only allows expansion outside of strings and comments. However, there have been several reports already where users were confused by this, so I'm going to change it to `t`.

**Comment by zw963** [comment]
> However, there have been several reports already where users were confused by this, so I'm going to change it to t.

@npostavs ,  I reopen this issue, if you changed, please close it.

**Comment by zw963** [comment]
Cool, will try it now.

**Comment by zw963** [comment]
worked!
