### ISSUE TITLE
Is there a way to not download all of the snippets when downloading package?

### ISSUE THREAD

**Issue by computersarecool** [joaotavora/yasnippet#775]
Hi,

I currently install yasnippet from melpa or marmalade using package-install.  I noticed that, by default this downloads a ton of snippets into the `elpa/yasnippet-datestamp/snippets` folder, because these are included by default.

Is there any way to not include these as part of the installation when automatically installing (as opposed to manually downloading the source)?

**Comment by npostavs** [comment]
No. Currenty, all ELPA served yasnippet packages include snippets. The GNU ELPA version comes with fewer snippets, I've been thinking about removing those. @AndreaCrotti recently floated the idea of making yasnippet-snippets into a separate MELPA published package.

**Comment by computersarecool** [comment]
I think that would be awesome. I would prefer to have some choice.
