### ISSUE TITLE
conflict with org-mode

### ISSUE THREAD

**Issue by fommil** [joaotavora/yasnippet#777]
I use the recommendation at http://orgmode.org/manual/Conflicts.html

```lisp
(defun yas/org-very-safe-expand ()
  "WORKAROUND http://orgmode.org/manual/Conflicts.html yas conflict."
  (let ((yas/fallback-behavior 'return-nil)) (yas/expand)))
(add-hook 'org-mode-hook
          (lambda ()
            (make-variable-buffer-local 'yas/trigger-key)
            (setq yas/trigger-key [tab])
            (add-to-list 'org-tab-first-hook 'yas/org-very-safe-expand)
            (define-key yas/keymap [tab] 'yas/next-field)))
```

but it would be great if this were supported out of the box in yas.

**Comment by npostavs** [comment]
> I use the recommendation at http://orgmode.org/manual/Conflicts.html

That recommendation is very outdated (`yas/trigger-key` no longer exists).

> but it would be great if this were supported out of the box in yas.

As far as I know, the latest yasnippet does play nicely with org mode out of the box. Please add details if you find otherwise.

**Comment by fommil** [comment]
nope, it didn't work for me unfortunately, TAB insisted on doing org-mode only things. The above hack does work for me (if I want TAB back) but I also found that using company-mode yas is also great! (TAB no longer works, but RET does if I wait for the completion to appear)

I'm using this

```lisp
(add-hook 'org-mode-hook
          (lambda ()
            (setq company-backends '((company-yasnippet company-dabbrev)))))
```

**Comment by npostavs** [comment]
> nope, it didn't work for me unfortunately, TAB insisted on doing org-mode only things.

Could you please explain how to reproduce this starting from [`emacs -Q`][emacs-Q]?

[emacs-Q]: http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html

**Comment by fommil** [comment]
possibly, but it will have to be another time... I sat down to write a talk today and I've already burnt through an hour fiddling with my emacs config :smile:

I don't think there is anything special, it should just be a case of starting from a fresh emacs config, starting a .org file and enabling yas/org-mode only, then hitting TAB after typing one of the snippet names.

I'm setting up

```
(define-key yas-minor-mode-map [tab] #'yas-expand
```

so it is possible that the org-mode mapping takes precedence.

**Comment by npostavs** [comment]
I did `emacs -Q -l yasnippet.el -f yas-global-mode -f org-mode` entered `dot_` and hit `<tab>` the snippet is expanded:
```
#+begin_src dot :file file :cmdline -Tpdf :exports none :results silent
            
#+end_src

[[file:file]]
```

**Comment by fommil** [comment]
hmm, I'll close until I can reproduce. I must be talking nonsense.
