### ISSUE TITLE
smartparens in snippet fields

### ISSUE THREAD

**Issue by CeleritasCelery** [joaotavora/yasnippet#785]
I am using Spacemacs and was looking into their solution for #575, which basically entails disabling smartparens during `yas-before-expand-snippet-hook` and re-enabling during `yas-after-exit-snippet-hook`. This takes care of smartparens inserting unwanted characters, but leaves it disabled the entire time you are moving through the snippet fields. If I enable smartparens after the snippet has expanded it works fine even if I am still in "yasnippet-mode". Is there an applicable hook or someplace in the yasnippet code that I could insert `(smartparens-mode 1)` to enable smartparens while moving through snippet fields?

**Comment by npostavs** [comment]
You could try adding `:after` advice on `yas--snippet-create`.

**Comment by joaotavora** [comment]
1. @CeleritasCelery, if you're not aware of it already, alternatives such as Emacs own `electric-pair-mode` work well with yasnippet AFAIK. What snippet in particular is giving you trouble?

2. @npostavs, there is an interesting idea in this report, which I don't know if we ever considered, which is to put the buffer into a `yasnippet-navigation-minor-mode` for the duration of the snippet navigation. This would, I believe, bring some simplifications in the way we handle setup and teardown of these kinds of issues. It's not unlike `completion-in-region-minor-mode`

Just some thoughts, OAO

**Comment by npostavs** [comment]
> put the buffer into a `yasnippet-navigation-minor-mode` for the duration of the snippet navigation.

Hmm, that might be a good idea in itself. But for this issue, I would rather someone finally make a clear report on what exactly is the incompatibilty with `smartparens` so we could just fix it instead of adding more hacks.

**Comment by CeleritasCelery** [comment]
Thanks for the advice @npostavs but I tried to add the following code and it does not resolve the issue. It does enable smartparens, but manifests the original bug that we are trying to avoid. 
```
(defun my/smartparens-restore-after-create-snippet (&optional begin end)
 "Restore the initial state of smartparens."
    (smartparens-mode 1))
(advice-add 'yas--snippet-create :after 'my/smartparens-restore-after-create-snippet)
```
Smartparens completes pairs so when I type `(` it will automatically add `)`. The problem is if I have a snippet that contains a pair, such as 
```
if ($1) {
    $2
}
```
smartparens will translate that too
```
if ()) {
    
}
```
adding an extra closing parenthesis. 
syl20bnr/spacemacs#1512 describes more detail about the problem and the fix that has been implemented. I do not know enough about the implementation details to determine who's at "fault" and therefore needs to make the fix. I am just trying to make it work. 
@npostavs or @joaotavora, Is there another function further down the call chain I could try? It works if I manually enable smartparens after the snippet has expanded.

**Comment by npostavs** [comment]
I'm not able to reproduce the problem. I tried 
```
emacs -Q -L dash -L yasnippet -L smartparens -l yasnippet.el -l smartparens.el -f yas-global-mode -f smartparens-global-mode -f c-mode
```

Entered `if` pressed <kbd>tab</kbd>, I got 

```
if (condition) {
  
 }
```

Yasnippet: cddb8260a0d89cc0
smarparens: fuco1/smartparens@0c81107de5509314
Emacs: 24.5, and 25.1.

---

> Is there another function further down the call chain I could try?

Hmm, maybe `yas-expand-snippet`?

**Comment by CeleritasCelery** [comment]
I believe you need to use `hippie-expand` to expand the snippet key to reproduce the problem. Also `yas-expand-snippet` does not work, nor does `yas--move-to-field`.

**Comment by npostavs** [comment]
> I believe you need to use `hippie-expand` to expand the snippet key to reproduce the problem.

Aha, got it, thanks. Looks like the snippet is being exited early.

**Comment by CeleritasCelery** [comment]
Perhaps that is why none advice's work.

**Comment by npostavs** [comment]
Okay, so the triggering thing is this advice in smartparens.el:
```elisp
(defadvice hippie-expand (after sp-auto-complete-advice activate)
  (when smartparens-mode
    (sp-insert-pair)))
```
So re-enabling `smartparens-mode` in any yasnippet function is indeed too early. It should happen only after this advice runs. Can you advise advice?

**Comment by CeleritasCelery** [comment]
It would be nice if they were using the new advice system. Anyways, wouldn't another advice just be making the `sp-auto-complete-advice` ineffectual? could we just remove it with 
```
(ad-disable-advice hippie-expand after sp-auto-complete-advice) 
(ad-activate hippie-expand)
```
I tried that and it seems to work. I may have to go ask the smartparens guys why that advice is there.

**Comment by npostavs** [comment]
> I may have to go ask the smartparens guys why that advice is there.

There is some discussion about it here: https://github.com/Fuco1/smartparens/issues/479#issuecomment-165800346

**Comment by CeleritasCelery** [comment]
Well it seems like the correct solution would be for smartparens to update their code to be aware of balanced pairs (as you pointed out). In the mean time, Spacemacs has a variable `spacemacs--yasnippet-expanding` that we could check in a new advice and only run `sp-insert-pair` if it is `nil`.

**Comment by npostavs** [comment]
This seems to work for me, independently of Spacemacs code:
```elisp
(defvar smartparens-mode-original-value)

(defun disable-sp-hippie-advice (&rest _)
  (setq smartparens-mode-original-value smartparens-mode)
  (setq smartparens-mode nil)
  t) ; We should still return t.
;; This advice could be added to other functions that usually insert
;; balanced parens, like `try-expand-list'.
(advice-add 'yas-hippie-try-expand :after-while #'disable-sp-hippie-advice)

(defun reenable-sp-hippie-advice (&rest _)
  (when (boundp 'smartparens-mode-original-value)
    (setq smartparens-mode smartparens-mode-original-value)
    (makunbound 'smartparens-mode-original-value)))
(advice-add 'hippie-expand :after #'reenable-sp-hippie-advice
            ;; Set negative depth to make sure we go after
            ;; `sp-auto-complete-advice'.
            '((depth . -100)))
```

**Comment by CeleritasCelery** [comment]
That works for me as well. Thanks for you help @npostavs! I am going to close this since it looks like the right place to fix this is in smartparens and they already have an issue open for it. I may port your solution over the Spacemacs repo.
