### ISSUE TITLE
Can yas expand a abbrev in any major mode?

### ISSUE THREAD

**Issue by ding3my** [joaotavora/yasnippet#792]
For example: I have a general snippet 
```
# -*- mode: snippet -*-
# name: gen
# key: gen
# --
This is general.
```
I want to expand `gen` to `This is general.`, no matter what the major mode is.

**Comment by ding3my** [comment]
I found the answer from http://joaotavora.github.io/yasnippet/snippet-expansion.html
(yas-activate-extra-mode) can solve my problem

**Comment by npostavs** [comment]
I think you might also be able to put it under `fundamental-mode`.
