### ISSUE TITLE
Question: Is it possible to keep tab stop field's state?

### ISSUE THREAD

**Issue by FrancescElies** [joaotavora/yasnippet#793]
Supposing I define the following snippet ```db.${1:collection}.findOne(${2:filter-by-id})```

The first time I use the snippet I fill `$1` and `$2` and get ```db.myCollection.findOne({"field":"value"})``` so far so good. 

I was wondering if there is a way of keeping the value I used for `$1` the first time I inserted the snippet for the next time I insert the snippet again, so when I insert the snippet I get ```db.my-collection.findOne(-!-)``` (-!- representing the cursor)

All best and thanks in advance for your help.

**Comment by npostavs** [comment]
This gets almost what you asked for: (also add `(defvar db-collection nil)` to your init.el or `.yas-setup.el` file)
```
# -*- mode: snippet -*-
# name: db findOne
# key: db
# --
db.${1:collection$(or (if (not yas-modified-p) db-collection) (if yas-moving-away-p (setq db-collection yas-text)))}.findOne(${2:filter-by-id})
```

> the next time I insert the snippet again, so when I insert the snippet I get `db.my-collection.findOne(-!-)`

It will instead give you `db.my-collection-!-.findOne()`, then you can use `<backspace>` do delete "my-collection", or press `<tab>` to accept it. I don't think yasnippet can currently do exactly what you asked.

**Comment by FrancescElies** [comment]
Thanks for your reply! this helps a lot, closing
