### ISSUE TITLE
How to make certain snippets works in a certain mode?

### ISSUE THREAD

**Issue by moyotar** [joaotavora/yasnippet#795]
For example, I defined a major mode named `my-major-mode` and have several snippets which are expected to be loaded when entering `my-major-mode`. How to do this?  Or why those subdirs under `yas-installed-snippets-dir` can be loaded when entering corresponding major mode?

**Comment by notetiene** [comment]
You don't have to do anything except creating a directory named `my-major-mode` in your snippets directory. You can also include snippets from other modes by making a file named `.yas-parent` that will include its parents like so:
```
my-parent-mode
```
