### ISSUE TITLE
Moving between fields hides Eldoc message

### ISSUE THREAD

**Issue by cpitclaudel** [joaotavora/yasnippet#796]
Hi there,

In the following example, navigating between fields hides eldoc messages.  Showing eldoc messages would be convenient because Eldoc can sometimes show type information at point, which helps with figuring out what to put in holes generated by Yasnippet.

```
(setq-local eldoc-documentation-function (lambda () "Eldoc"))
(yas-minor-mode 1)
(yas-expand-snippet "${1:aaa} ${2:aaa} ${3:aaa}")
```

Let me know if I can provide a better example or any other information!
Thanks :)

**Comment by npostavs** [comment]
`(eldoc-add-command 'yas-next-field-or-maybe-expand 'yas-prev-field)` fixes this, right?

**Comment by cpitclaudel** [comment]
Yup, looks great.

**Comment by cpitclaudel** [comment]
Actually — it looks great after the first `TAB`.  The first field still doesn't show the docs.

**Comment by npostavs** [comment]
I think this should cover it:
```elisp
(eldoc-add-command 'yas-next-field-or-maybe-expand 'yas-prev-field
		   'yas-expand 'yas-expand-from-keymap
		   'yas-expand-from-trigger-key)
```

Not sure if we should have it by default; this could get in the way of warning messages. Although maybe the answer to that is to use `display-warning`/`lwarn` instead of `message` for warnings.

**Comment by cpitclaudel** [comment]
Hmm. Which warning messages do you have in mind?

**Comment by npostavs** [comment]
Stuff printed at verbosity level 1 or 2: (I'm not sure offhand which of these would be in "danger" of being hidden by eldoc)

```
yasnippet.el:1247:             (yas--message 1 "Error in condition evaluation: %s" (error-message-string err))
yasnippet.el:1859:               (push (yas--message 1 "Check your `yas-snippet-dirs': %s is not a directory" directory) errors)))))
yasnippet.el:1886:                (yas--message 1 "Aborted reload...")
yasnippet.el:2128:            (t (yas--message 1 "Don't know anything about menu entry %s" type)
yasnippet.el:2395:      (yas--message 1 "No snippets can be inserted here!"))))
yasnippet.el:2690:           (yas--message 1 "Cannot test snippet for unknown major mode")))))
yasnippet.el:4690:    (yas--message 1 msg)))

yasnippet.el:1392:       (yas--message 2 "warning: keybinding \"%s\" invalid since %s."
yasnippet.el:3375:     (yas--message 2 "Error running %s: %s" fun
yasnippet.el:3659:      (yas--message 2 "Committing snippets. Action would destroy a protection overlay.")
```

**Comment by cpitclaudel** [comment]
Thanks, I understand the issue now.

**Comment by npostavs** [comment]
> this could get in the way of warning messages

I've decided `eldoc-idle-delay` should mostly make this okay, we'll see if causes any problems in practice.
