### ISSUE TITLE
Not expand when cursor after a key which partial part of symbol

### ISSUE THREAD

**Issue by zw963** [joaotavora/yasnippet#805]
Following is a example:

I add a new snippets to ruby-mode which expand with: ``for``

```rb
forI  # <= expect expand to ruby for loop
```

```rb
attr_for # <= not expect to expand.
```

Current behavior is: 
``for`` as part of a symbol, it will be expand.

**Comment by npostavs** [comment]
Try `(setq yas-key-syntaxes '("w_"))`.

**Comment by zw963** [comment]
Cool, It worked!

I think the default of ``yas-key-syntaxes`` is some a little confuse...

the following idea is just for personal opinion:

1. if exist two snippets, one is ``for``, one is ``attr_for``, when cursor is follow
``attr_for``, I think it should expand ``attr_for``, not ``for``, because, in this case
``attr_for`` is more accuracy for my purpose

2. the same as this issue, if not ``attr_for``, we should not expand ``for`` of
``attr_for`` in this case.

Thanks

**Comment by zw963** [comment]
BTW: for the 1, it seem like the expect behavior for previous yasnippets, I remember I read document
about this some years ago, so, it is not bug, just the which is better correct behavior.

**Comment by npostavs** [comment]
Hmm, right, probably the default should be the reverse of what it is now: 
`(setq yas-key-syntaxes '(yas-try-key-from-whitespace "w_.()" "w_." "w_" "w"))`. 

I will make that change, but only after 0.12 is released, not before.

**Comment by zw963** [comment]
@npostavs , 

I change my personal `yas-key-syntaxs` to following:
```cl
(setq yas-key-syntaxes '(yas-try-key-from-whitespace "w_.()" "w_." "w_))
```

It seem like work well for me, following some describe:

exist two snippets, one key is `for`, another key is  `attr_for`.

case 1:  ` abcd for`__I__, will expand `for`

case 2 `abcd_for`__I__ nothing expand.

case 3  `abcd attr_for`__I__, will expand `attr_for`

case 4 `abcd_attr_for`__I__, nothing expand.

I think this is a better choice for myself. just for discuss. 

Thanks

**Comment by zw963** [comment]
Cool!
