### ISSUE TITLE
0.11 not worked with some self-defined condition.

### ISSUE THREAD

**Issue by zw963** [joaotavora/yasnippet#806]
Just update to the HEAD vesion of snippets (47f37f7), which broken I some snippets which is worked
in 0.10.

Following is a example:

```cl
# -*- mode: snippet -*-
# name: some snippet
# key: c
# binding: c
# condition: (yas-use-region-p)
# --
foo`(yas-select-text)`bar
```

I expect this snippets will expand in two condition:

1. when I press ``c``, and than ``TAB``
2. Add a mark to select some content in to region, and press ``c``, I expect ``yas-selected-text`` is 
replaced with content.

But, my condition ``(yas-use-region-p)`` is not worked anymore, caused this snippets not expanded.

following is function define:

```el
(defun expand-from-key-p ()
  "通过 TAB 来激活的 snippet."
  (equal (this-command-keys-vector) '[tab]))

(yas-define-condition-cache yas-use-region-p (or (expand-from-key-p) (use-region-p)))
```

Thanks

**Comment by npostavs** [comment]
I can confirm, works in 0.10.0 and 0.11.0, fails with HEAD. Specifically, this is broken by #760 (0311fe26191a713d4c2b8b0b5fe236eb2372c128). 

`yas--condition-cache-timestamp` isn't being bound in the key `:filter` functions. Should be fixed by #807.

**Comment by zw963** [comment]
worked!

**Comment by zw963** [comment]
@npostavs ,  here have another concerns need consider.

Suppose I have a snippets, which defined as key `tag`.
when cursor is after following tag, should we expand ?

```html
title_tagI
```

Current version, it could expand, But, I think it should only
expand when 
```html
tagI
```

because I think `title_tag` as a whole symbol.

**Comment by npostavs** [comment]
> because I think `title_tag` as a whole symbol.

You can change `yas-key-syntaxes` to get this behaviour (as I mentioned in #805), but I don't think we want that as a default.
