### ISSUE TITLE
R and J for 'yas-expand

### ISSUE THREAD

**Issue by bumbker** [joaotavora/yasnippet#808]
I have used yasnippet for quite some time and now after an O.S. change to linux mint 18.1 and a new yasnippet install   yasnippet  20170418.351  in Emacs24  I'm getting a different behavior which I need to fix.  
I use the following elisp expressions to define keys "R" and "J"  for yas-expand:
 (define-key yas-minor-mode-map (kbd "<tab>") nil)
 (define-key yas-minor-mode-map (kbd "TAB") nil)
 (define-key yas-minor-mode-map (kbd "r") 'yas-expand)
 (define-key yas-minor-mode-map (kbd "j") 'yas-expand)

this has always worked well and I could still type in an R or J  unless it was following a snippet expansion key sequence, in which case it would expand the snippet.  Now after the new install the R and J will only do yas-expand.  I cannot type in R's and J's at other places like before.  Please Help.  I really need it to work that way.

**Comment by npostavs** [comment]
Try `(define-key yas-minor-mode-map (kbd "r") yas-maybe-expand)` (note there is no quote there)

Note to self: I should updated the docs about this.

**Comment by bumbker** [comment]
Yes that works.  Great.  Thank you.  Yasnippet is excellent

**Comment by bumbker** [comment]
I found out the solution.    in the lines such as (define-key
yas-minor-mode-map (kbd "r") 'yas-expand)  I have to write
yas-maybe-expand (no quote mark)    instead of 'yas-expand

**Comment by npostavs** [comment]
> Note to self: I should have updated the docs about this.

Actually I had updated the docs, it's just that the web version is still from 0.11.

> EDIT: also check if we can support the old way.

The old behaviour could be restored by setting `yas-fallback-behavior` to `call-other-command`.
