### ISSUE TITLE
Insert a snippet without indentation

### ISSUE THREAD

**Issue by amosbird** [joaotavora/yasnippet#809]
How can I insert a snippet ( in my case `private:`) that starts in the head of current line if there are only blanks between head and the cursor point.

```
class foo {
public:
  void bar();
  |    <--- cursor point
}
```

**Comment by npostavs** [comment]
If you bind `yas/also-auto-indent-first-line` to `t` should work. It might seem a bit funny that I suggested enabling more indentation to get no indentation, but that just calls the standard mode indent on the snippet's first line, which should give the indent you want. You can also bind it just for a particular snippet with `expand-env`:
```
# -*- mode: snippet -*-
# name: private
# key: pr
# expand-env: ((yas-also-auto-indent-first-line t))
# --
private:
        $0
```

**Comment by amosbird** [comment]
Thanks!
