### ISSUE TITLE
How to expand the key before which there is a non-key string?

### ISSUE THREAD

**Issue by ding3my** [joaotavora/yasnippet#810]
For example, this is my snippet in python mode:

    # -*- mode: snippet -*-
    # name: (
    # key: (
    # --
    ($0)

I can expand `(`to `()`, but I can not expand `a(` to `a()`.

How to expand `a(` to `a()`? Thx in advance!

**Comment by notetiene** [comment]
While it may be a good question, I'm not sure the example you gave is a good candidate for YASnippet. It looks like `electric-pair-mode`, `paredit-mode` or `smartparens` would more suitable for you. I personally like the way `smartparens` works, but that's just preferences.

YASnippet is most useful when you got a repetitive snippet of code (usually several words) to automate or when you want to use functionality like snippet mirrors/fields.

As for your question, I fear there's no easy way to make that happen without the risk of breaking YASnippet (I may be wrong). Do you have any other example where you would like that to happen? This example is too short for me to think about a snippet.

**Comment by npostavs** [comment]
You can probably make this work by changing `yas-key-syntaxes`, see #805. But I agree with the suggestion to use `electric-pair-mode` or similar rather than yasnippet for this, see also https://emacs.stackexchange.com/a/19601/5296, #533.

**Comment by notetiene** [comment]
@npostavs great! I didn't know about that!

**Comment by ding3my** [comment]
@notetiene @npostavs Thx for your help!

I have tried `(setq yas-key-syntaxes '(yas-try-key-from-whitespace "w_.()" "w_." "w_" "w"))` from [#805](https://github.com/joaotavora/yasnippet/issues/805), but failed to expand `a(` to `a()` : (

Does it need a function like `yas-try-key-from-whitespace` to expand `a(` to `a()`?

**Comment by ding3my** [comment]
Is there more information about `w_.()` and `w_.`?

**Comment by npostavs** [comment]
The characters correspond to syntax classes, listed in [(elisp) Syntax Class Table](https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Class-Table.html). Your snippet key has syntax `(`, so you should do `(add-to-list 'yas-key-syntaxes  "(")`.
