### ISSUE TITLE
Can yas-lookup-snippet evaluate elisp code after expanding a snippet?

### ISSUE THREAD

**Issue by shackra** [joaotavora/yasnippet#811]
Hello!

I'm having this use case where I'm trying to use "heritage" between snippets, for instance I have a snippet called _greetings_, which may look like this:

```
Hello, [NAME]!

`(when (y-or-n-p "Did we meet before?") (insert "I know you!"))`
```

And in another snippet I have something, like say, this called _letter_:

```
`(yas-lookup-snippet "greetings")`

Now, regarding to your [ISSUE], there are a couple of stuff we can do to help you blah blah blah...
```

When trying to use the _letter_ snippet a issue I see right now are errors throw by company-mode:

```
company-call-backend-raw: Company: backend (company-files company-keywords company-capf company-yasnippet) error "Wrong type argument: char-or-string-p, (end-of-file)" with args (post-completion letter)
```

So I was wondering if what I'm doing is wrong and there is another way to do this or this feature is not supported by yasnippet at the moment.

**Comment by npostavs** [comment]
> When trying to use the letter snippet a issue I see right now are errors throw by company-mode:

I'm confused as to how company-mode fits into this, but I think the answer is that yasnippet doesn't support this yet (see #558).
