### ISSUE TITLE
(wrong-type-argument integerp nil)

### ISSUE THREAD

**Issue by xin-jin** [joaotavora/yasnippet#812]
Hi, I upgraded emacs24 to emacs25. However now yasnippet (latest from elpa) always reports
`(wrong-type-argument integerp nil)`
when it loads snippets. 

For instance, when opening a .el,
```
[yas] Loading for `emacs-lisp-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /home/xin/.emacs.d/yasnippet-master/snippets/emacs-lisp-mode) (quote emacs-lisp-mode)))!
[yas] Loading compiled snippets from /home/xin/.emacs.d/yasnippet-master/snippets/emacs-lisp-mode
Loading /home/xin/.emacs.d/yasnippet-master/snippets/emacs-lisp-mode/.yas-compiled-snippets.el (source)...
File mode specification error: (wrong-type-argument integerp nil)
```
And the emacs frame then breaks (opening the same file twice works, but no snippets expansion is available). 

And when switching to some major mode, say latex mode,
```
[yas] Loading for `latex-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /home/xin/.emacs.d/yasnippet-master/snippets/latex-mode) (quote latex-mode)))!
[yas] Loading compiled snippets from /home/xin/.emacs.d/yasnippet-master/snippets/latex-mode
Loading /home/xin/.emacs.d/yasnippet-master/snippets/latex-mode/.yas-compiled-snippets.el (source)...
Error in post-command-hook (yas-global-mode-check-buffers): (wrong-type-argument integerp nil)
```

Any idea how to fix it? I tried recompiling all packages and also package-reinstall yasnippet, but neither works.

Environment: Emacs 25.2.2 on Ubuntu 16.04

**Comment by npostavs** [comment]
Can you get a backtrace with `M-x toggle-debug-on-error`?

**Comment by xin-jin** [comment]
@npostavs  Hello. Thanks for the reply. I am not sure how the debug works? I toggle-debug-on-error, but when the error occurs, the *Backtrace* buffer is empty.

**Comment by npostavs** [comment]
Hmm, the error must be happening in a place where the debugger is suppressed. Do you get anything if you do `M-: (yas-global-mode-check-buffers)`?

**Comment by xin-jin** [comment]
@npostavs  This is what I got:
`(global-font-lock-mode-check-buffers global-linum-mode-check-buffers global-undo-tree-mode-check-buffers global-highlight-parentheses-mode-check-buffers smartparens-global-mode-check-buffers beacon--post-command sp--post-command-hook-handler mic-paren-command-hook eldoc-schedule-timer)`

**Comment by npostavs** [comment]
Hmm, no error when you call it that way it seems. I searched for `File mode specification error` and there is only one place where it shows up in `with-demoted-errors`, but that should not suppress the debugger, so perhaps you just toggled the debugger too late.

Could you try just putting `(setq debug-on-error t)` at the very top of your init.el?

**Comment by xin-jin** [comment]
@npostavs Same behavior. An empty *Backtrace* buffer is created.

**Comment by npostavs** [comment]
Perhaps some other packages you have installed are interacting badly with yasnippet somehow? Can you reproduce this starting from [`emacs -Q`][emacs-Q]?

[emacs-Q]: http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html

**Comment by xin-jin** [comment]
@npostavs I think you are right. I ran emacs -Q with yasnippet alone, and it does work without errors.

**Comment by npostavs** [comment]
Aha, can you figure out which part of your init causes this? (refer https://emacs.stackexchange.com/questions/28429/how-do-i-troubleshoot-emacs-problems)

**Comment by xin-jin** [comment]
hi, I retried a little bit, this is the error message I got. Do you notice anything wrong? It seems to me that some snippets cause the error, but I don't why they worked for emacs24.


> Debugger entered--Lisp error: (wrong-type-argument integerp nil)
  aset([cl-struct-yas--template nil nil nil nil nil nil nil nil nil nil nil nil] nil [cl-struct-yas--table "python-mode" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ( ...)) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ( ...)) nil (keymap)])
  (while args (aset template (position (intern (substring (symbol-name (car args)) 1)) (mapcar (function car) (get (quote yas--template) (quote cl-struct-slots)))) (car (cdr args))) (setq args (cdr (cdr args))))
  yas--populate-template([cl-struct-yas--template nil nil nil nil nil nil nil nil nil nil nil nil] :table [cl-struct-yas--table "python-mode" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ( ...)) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ( ...)) nil (keymap)] :key "super" :content "super`(elpy-snippet-super-form)`(${1:`(elpy-snippet-super-arguments)`})\n$0" :name "super()" :group ("Definitions") :condition nil :expand-env nil :file "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/super" :keybinding nil :uuid "super()")
  (let* ((file (seventh snippet)) (key (car snippet)) (name (or (car (cdr (cdr snippet))) (and file (file-name-directory file)))) (condition (car (cdr (cdr (cdr snippet))))) (group (fifth snippet)) (keybinding (yas--read-keybinding (eighth snippet))) (uuid (or (ninth snippet) name)) (template (or (gethash uuid (progn nil (or (progn nil ...) (signal ... ...)) (aref snippet-table 3))) (progn "Constructor for objects of type `yas--template'." nil (vector (quote cl-struct-yas--template) nil nil nil nil nil nil nil nil nil nil nil nil))))) (yas--populate-template template :table snippet-table :key key :content (car (cdr snippet)) :name (or name key) :group group :condition condition :expand-env (sixth snippet) :file (seventh snippet) :keybinding keybinding :uuid uuid) (yas--update-template snippet-table template) template)
  yas--define-snippets-1(("super" "super`(elpy-snippet-super-form)`(${1:`(elpy-snippet-super-arguments)`})\n$0" "super()" nil ("Definitions") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/super" nil nil) [cl-struct-yas--table "python-mode" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ( ...)) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ( ...)) nil (keymap)])
  (setq template (yas--define-snippets-1 snippet snippet-table))
  (while --dolist-tail-- (setq snippet (car --dolist-tail--)) (setq template (yas--define-snippets-1 snippet snippet-table)) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- snippets) snippet) (while --dolist-tail-- (setq snippet (car --dolist-tail--)) (setq template (yas--define-snippets-1 snippet snippet-table)) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((snippet-table (yas--table-get-create mode)) (template nil)) (let ((--dolist-tail-- snippets) snippet) (while --dolist-tail-- (setq snippet (car --dolist-tail--)) (setq template (yas--define-snippets-1 snippet snippet-table)) (setq --dolist-tail-- (cdr --dolist-tail--)))) template)
  (if yas--creating-compiled-snippets (progn (insert ";;; Snippet definitions:\n;;;\n") (let ((literal-snippets (list)) (print-length nil)) (let ((--dolist-tail-- snippets) snippet) (while --dolist-tail-- (setq snippet (car --dolist-tail--)) (let ((key ...) (template-content ...) (name ...) (condition ...) (group ...) (expand-env ...) (file nil) (binding ...) (uuid ...)) (setq literal-snippets (cons ... literal-snippets))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (insert (pp-to-string (list (quote yas-define-snippets) (list (quote quote) mode) (list (quote quote) literal-snippets)))) (insert "\n\n"))) (let ((snippet-table (yas--table-get-create mode)) (template nil)) (let ((--dolist-tail-- snippets) snippet) (while --dolist-tail-- (setq snippet (car --dolist-tail--)) (setq template (yas--define-snippets-1 snippet snippet-table)) (setq --dolist-tail-- (cdr --dolist-tail--)))) template))
  yas-define-snippets(python-mode (("super" "super`(elpy-snippet-super-form)`(${1:`(elpy-snippet-super-arguments)`})\n$0" "super()" nil ("Definitions") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/super" nil nil) ("py3" "from __future__ import division, absolute_import\nfrom __future__ import print_function, unicode_literals\n" "from __future__ import ..." nil ("Python 3") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/py3" nil nil) ("pdb" "import pdb; pdb.set_trace()\n" "pdb.set_trace()" nil ("Debug") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/pdb" nil nil) ("from" "from ${1:module} import ${2:symbol}\n$0" "from MOD import SYM" nil ("Header") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/from" nil nil) ("env" "#!/usr/bin/env python\n" "#!/usr/bin/env python" nil ("Header") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/env" nil nil) ("enc" "# coding: utf-8\n" "# coding: utf-8" nil ("Header") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/enc" nil nil) ("defs" "def ${1:methodname}(self, ${2:arg}):\n    ${3:pass}\n" "def method(self, ...):" nil ("Definitions") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/defs" nil nil) ("class" "class ${1:ClassName}(${2:object}):\n    \"\"\"${3:Documentation for $1}\n\n    \"\"\"\n    def __init__(self${4:, args}):\n        super($1, self).__init__($5)\n        ${4:$(elpy-snippet-init-assignments yas-text)}\n        $0\n" "class(parent): ..." nil ("Definitions") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/class" nil nil) ("asr" "with self.assertRaises(${1:Exception}):\n    $0\n" "Assert Raises" nil ("Testing") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/asr" nil nil) ("asne" "self.assertNotEqual(${1:expected}, ${2:actual})\n" "Assert Not Equal" nil ("Testing") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/asne" nil nil) ("ase" "self.assertEqual(${1:expected}, ${2:actual})\n" "Assert Equal" nil ("Testing") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/ase" nil nil) ("__xor__" "def __xor__(self, other):\n    return $0\n" "__xor__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__xor__" nil nil) ("__unicode__" "def __unicode__(self):\n    return $0\n" "__unicode__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__unicode__" nil nil) ("__truediv__" "def __truediv__(self, other):\n    return $0\n" "__truediv__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__truediv__" nil nil) ("__subclasscheck__" "def __subclasscheck__(self, instance):\n    return $0\n" "__subclasscheck__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__subclasscheck__" nil nil) ("__sub__" "def __sub__(self, other):\n    return $0\n" "__sub__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__sub__" nil nil) ("__str__" "def __str__(self):\n    return $0\n" "__str__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__str__" nil nil) ("__slots__" "__slots__ = ($1)\n$0\n" "__slots__" nil ("Class attributes") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__slots__" nil nil) ("__setitem__" "def __setitem__(self, key, value):\n    $0\n" "__setitem__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__setitem__" nil nil) ("__setattr__" "def __setattr__(self, name, value):\n    $0\n" "__setattr__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__setattr__" nil nil) ("__set__" "def __set__(self, instance, value):\n    $0\n" "__set__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__set__" nil nil) ("__rxor__" "def __rxor__(self, other):\n    return $0\n" "__rxor__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__rxor__" nil nil) ("__rtruediv__" "def __rtruediv__(self, other):\n    return $0\n" "__rtruediv__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__rtruediv__" nil nil) ("__rsub__" "def __rsub__(self, other):\n    return $0\n" "__rsub__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__rsub__" nil nil) ("__rshift__" "def __rshift__(self, other):\n    return $0\n" "__rshift__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__rshift__" nil nil) ("__rrshift__" "def __rrshift__(self, other):\n    return $0\n" "__rrshift__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__rrshift__" nil nil) ("__rpow__" "def __rpow__(self, other):\n    return $0\n" "__rpow__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__rpow__" nil nil) ("__ror__" "def __ror__(self, other):\n    return $0\n" "__ror__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__ror__" nil nil) ("__rmul__" "def __rmul__(self, other):\n    return $0\n" "__rmul__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__rmul__" nil nil) ("__rmod__" "def __rmod__(self, other):\n    return $0\n" "__rmod__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__rmod__" nil nil) ("__rlshift__" "def __rlshift__(self, other):\n    return $0\n" "__rlshift__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__rlshift__" nil nil) ("__rfloordiv__" "def __rfloordiv__(self, other):\n    return $0\n" "__rfloordiv__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__rfloordiv__" nil nil) ("__reversed__" "def __reversed__(self):\n    return $0\n" "__reversed__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__reversed__" nil nil) ("__repr__" "def __repr__(self):\n    return $0\n" "__repr__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__repr__" nil nil) ("__rdivmod__" "def __rdivmod__(self, other):\n    return $0\n" "__rdivmod__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__rdivmod__" nil nil) ("__rand__" "def __rand__(self, other):\n    return $0\n" "__rand__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__rand__" nil nil) ("__radd__" "def __radd__(self, other):\n    return $0\n" "__radd__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__radd__" nil nil) ("__pow__" "def __pow__(self, other, modulo=None):\n    return $0\n" "__pow__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__pow__" nil nil) ("__pos__" "def __pos__(self):\n    return $0\n" "__pos__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__pos__" nil nil) ("__or__" "def __or__(self, other):\n    return $0\n" "__or__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__or__" nil nil) ("__oct__" "def __oct__(self):\n    return $0\n" "__oct__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__oct__" nil nil) ("__nonzero__" "def __nonzero__(self):\n    return $0\n" "__nonzero__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__nonzero__" nil nil) ("__new__" "def __new__(cls${1:, args}):\n    \"\"\"$2\n\n    \"\"\"\n    ${1:$(elpy-snippet-init-assignments yas-text)}\n" "__new__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__new__" nil nil) ("__neg__" "def __neg__(self):\n    return $0\n" "__neg__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__neg__" nil nil) ("__ne__" "def __ne__(self, other):\n    return $0\n" "__ne__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__ne__" nil nil) ("__mul__" "def __mul__(self, other):\n    return $0\n" "__mul__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__mul__" nil nil) ("__mod__" "def __mod__(self, other):\n    return $0\n" "__mod__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__mod__" nil nil) ("__lt__" "def __lt__(self, other):\n    return $0\n" "__lt__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__lt__" nil nil) ("__lshift__" "def __lshift__(self, other):\n    return $0\n" "__lshift__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__lshift__" nil nil) ("__long__" "def __long__(self):\n    return $0\n" "__long__" nil ("Special methods") nil "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode/__long__" nil nil) ...))
  (progn (yas-define-snippets mode-sym snippet-defs))
  (if snippet-defs (progn (yas-define-snippets mode-sym snippet-defs)))
  (let* ((default-directory directory) (snippet-defs nil)) (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (let ((--dolist-tail-- ...) file) (while --dolist-tail-- (setq file ...) (if ... ...) (setq --dolist-tail-- ...)))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))) (if snippet-defs (progn (yas-define-snippets mode-sym snippet-defs))) (let ((--dolist-tail-- (yas--subdirs directory)) subdir) (while --dolist-tail-- (setq subdir (car --dolist-tail--)) (yas--load-directory-2 subdir mode-sym) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  yas--load-directory-2("/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode" python-mode)
  (if (and (progn (yas--message 2 "Loading compiled snippets from %s" directory) t) (load (expand-file-name ".yas-compiled-snippets" directory) (quote noerror) (<= yas-verbosity 3))) (yas--message 2 "Loading snippet files from %s" directory) (yas--load-directory-2 directory mode-sym))
  (if (file-exists-p (concat directory "/" ".yas-skip")) nil (if (and (progn (yas--message 2 "Loading compiled snippets from %s" directory) t) (load (expand-file-name ".yas-compiled-snippets" directory) (quote noerror) (<= yas-verbosity 3))) (yas--message 2 "Loading snippet files from %s" directory) (yas--load-directory-2 directory mode-sym)))
  (if yas--creating-compiled-snippets (let ((output-file (expand-file-name ".yas-compiled-snippets.el" directory))) (let ((temp-file output-file) (temp-buffer (get-buffer-create (generate-new-buffer-name " *temp file*")))) (unwind-protect (prog1 (save-current-buffer (set-buffer temp-buffer) (insert (format ";;; Compiled snippets and support files for `%s'\n" mode-sym)) (yas--load-directory-2 directory mode-sym) (insert (format ";;; Do not edit! File generated at %s\n" ...))) (save-current-buffer (set-buffer temp-buffer) (write-region nil nil temp-file nil 0))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))) (if (file-exists-p (concat directory "/" ".yas-skip")) nil (if (and (progn (yas--message 2 "Loading compiled snippets from %s" directory) t) (load (expand-file-name ".yas-compiled-snippets" directory) (quote noerror) (<= yas-verbosity 3))) (yas--message 2 "Loading snippet files from %s" directory) (yas--load-directory-2 directory mode-sym))))
  yas--load-directory-1("/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode" python-mode)
  (lambda nil (yas--load-directory-1 (quote "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode") (quote python-mode)))()
  funcall((lambda nil (yas--load-directory-1 (quote "/home/xin/.emacs.d/elpa/elpy-20170701.1412/snippets/python-mode") (quote python-mode))))
  (while --dolist-tail-- (setq fun (car --dolist-tail--)) (yas--message 3 "Loading for `%s', just-in-time: %s!" mode fun) (funcall fun) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- funs) fun) (while --dolist-tail-- (setq fun (car --dolist-tail--)) (yas--message 3 "Loading for `%s', just-in-time: %s!" mode fun) (funcall fun) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((funs (reverse (gethash mode yas--scheduled-jit-loads)))) (let ((--dolist-tail-- funs) fun) (while --dolist-tail-- (setq fun (car --dolist-tail--)) (yas--message 3 "Loading for `%s', just-in-time: %s!" mode fun) (funcall fun) (setq --dolist-tail-- (cdr --dolist-tail--)))) (remhash mode yas--scheduled-jit-loads))
  (while --dolist-tail-- (setq mode (car --dolist-tail--)) (let ((funs (reverse (gethash mode yas--scheduled-jit-loads)))) (let ((--dolist-tail-- funs) fun) (while --dolist-tail-- (setq fun (car --dolist-tail--)) (yas--message 3 "Loading for `%s', just-in-time: %s!" mode fun) (funcall fun) (setq --dolist-tail-- (cdr --dolist-tail--)))) (remhash mode yas--scheduled-jit-loads)) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- (yas--modes-to-activate)) mode) (while --dolist-tail-- (setq mode (car --dolist-tail--)) (let ((funs (reverse (gethash mode yas--scheduled-jit-loads)))) (let ((--dolist-tail-- funs) fun) (while --dolist-tail-- (setq fun (car --dolist-tail--)) (yas--message 3 "Loading for `%s', just-in-time: %s!" mode fun) (funcall fun) (setq --dolist-tail-- (cdr --dolist-tail--)))) (remhash mode yas--scheduled-jit-loads)) (setq --dolist-tail-- (cdr --dolist-tail--))))
  yas--load-pending-jits()
  (cond (yas-minor-mode (add-hook (quote emulation-mode-map-alists) (quote yas--direct-keymaps)) (add-hook (quote post-command-hook) (quote yas--post-command-handler) nil t) (let ((--dolist-tail-- (yas--modes-to-activate)) mode) (while --dolist-tail-- (setq mode (car --dolist-tail--)) (let ((name (intern ...))) (set-default name nil) (set (make-local-variable name) t)) (setq --dolist-tail-- (cdr --dolist-tail--)))) (yas--load-pending-jits)) (t (remove-hook (quote post-command-hook) (quote yas--post-command-handler) t) (remove-hook (quote emulation-mode-map-alists) (quote yas--direct-keymaps))))
  (let ((last-message (current-message))) (setq yas-minor-mode (if (eq arg (quote toggle)) (not yas-minor-mode) (> (prefix-numeric-value arg) 0))) (cond (yas-minor-mode (add-hook (quote emulation-mode-map-alists) (quote yas--direct-keymaps)) (add-hook (quote post-command-hook) (quote yas--post-command-handler) nil t) (let ((--dolist-tail-- (yas--modes-to-activate)) mode) (while --dolist-tail-- (setq mode (car --dolist-tail--)) (let ((name ...)) (set-default name nil) (set (make-local-variable name) t)) (setq --dolist-tail-- (cdr --dolist-tail--)))) (yas--load-pending-jits)) (t (remove-hook (quote post-command-hook) (quote yas--post-command-handler) t) (remove-hook (quote emulation-mode-map-alists) (quote yas--direct-keymaps)))) (run-hooks (quote yas-minor-mode-hook) (if yas-minor-mode (quote yas-minor-mode-on-hook) (quote yas-minor-mode-off-hook))) (if (called-interactively-p (quote any)) (progn nil (if (and (current-message) (not (equal last-message (current-message)))) nil (let ((local " in current buffer")) (message "yas minor mode %sabled%s" (if yas-minor-mode "en" "dis") local))))))
  yas-minor-mode(1)
  elpy-module-yasnippet(buffer-init)
  apply(elpy-module-yasnippet buffer-init nil)
  elpy-modules-run(buffer-init)
  elpy-modules-buffer-init()
  elpy-mode()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook python-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook python-mode-hook))
  run-mode-hooks(python-mode-hook)
  python-mode()
  set-auto-mode-0(python-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer test.py> "~/test.py" nil nil "~/test.py" (20188261 66308))
  find-file-noselect("/home/xin/test.py")
  #[1285 "\204\300!\204\301\302\"\207\303\304!\"\305!\242B\240\210\211q\210\242\306U\2043eb\210\242Sy\210\306\240\210\242\307W\204D\310\242S!\210\306\240\207" [file-name-absolute-p message "Ignoring relative file name (%s) due to nil default-directory" expand-file-name command-line-normalize-file-name find-file-noselect 0 1 move-to-column] 10 "\n\n(fn DISPLAYABLE-BUFFERS DIR LINE COLUMN NAME)"]((nil) "~/" (0) (0) "test.py")
  command-line-1(("test.py"))
  command-line()
  normal-top-level()

**Comment by npostavs** [comment]
> `yas--populate-template([cl-struct-yas--template nil nil...`

`yas--populate-template` has been removed a couple of years ago (d19ef74634ca7050c331971a7f9ee29211e08826). Perhaps you have an old version of `yasnippet.el` sitting somewhere in your `load-path`? What does `M-x list-load-path-shadows` tell you?

**Comment by xin-jin** [comment]
@npostavs Thanks a lot! That's exactly the cause. Somehow I've been keeping using a 0.80 version yasnippet installed long time ago instead of the one installed via elpa. I deleted the old version, then it's resolved.
