### ISSUE TITLE
Killing zombie snippet!

### ISSUE THREAD

**Issue by xianghx** [joaotavora/yasnippet#814]
write some code, snippet, 
 then press
`
    (define-key cargo-minor-mode-map (kbd "<C-return>") 'cargo-process-run)
`
but sometimes, kill all buffer,  yas say   Killing zombie snippet!

**Comment by npostavs** [comment]
Can you explain in more detail exactly what you did to trigger this?

**Comment by xianghx** [comment]
Saving file /home/xianghx/projects/hello_rust/src/main.rs...
Formatted buffer with rustfmt.
Wrote /home/xianghx/projects/hello_rust/src/main.rs
Cargo-Process finished
Cargo Process finished.
Saving file /home/xianghx/projects/hello_rust/src/main.rs...
[yas] Committing snippets. Action would destroy a protection overlay. [2 times]
Error: (buffer-read-only #<buffer *Warnings*>)
Wrote /home/xianghx/projects/hello_rust/src/main.rs

**Comment by xianghx** [comment]
# -*- mode: snippet -*-
# name: println!();
# key: pr
# type: snippet
# --
println!("$1"$2);$0

fn main() {
    println!("{}", "hello");
}

here:  println!("{}", "hello");    don't tab to $0  ,just press ctrl-return

**Comment by npostavs** [comment]
> here: println!("{}", "hello"); don't tab to $0 ,just press ctrl-return

Um, can you give instructions starting from [`emacs -Q`][emacs-Q]? This gives `<C-return> is undefined`.

[emacs-Q]: http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html

**Comment by xianghx** [comment]
```elisp
(use-package rust-mode
  :ensure t
  :defer t
  :mode ("\\.rs\\'" . rust-mode)
  :config
    (setq rust-format-on-save t)
    (add-hook 'rust-mode-hook #'cargo-minor-mode)
  )

(use-package cargo
  :ensure t
  :defer t
  :config
    (define-key cargo-minor-mode-map (kbd "<C-return>") 'cargo-process-run))

```

**Comment by xianghx** [comment]
```elisp
# -*- mode: snippet -*-
# name: println!();
# key: pr
# type: snippet
# --
println!("$1"$2);$0
```

**Comment by xianghx** [comment]
there are some code:
```elisp
;;;###autoload
(defun cargo-process-run ()
  "Run the Cargo run command.
With the prefix argument, modify the command's invocation.
Cargo: Build and execute src/main.rs."
  (interactive)
  (cargo-process--start "Run" "cargo run"))

(defun cargo-process--start (name command)
  "Start the Cargo process NAME with the cargo command COMMAND."
  (let* ((buffer (concat "*Cargo " name "*"))
         (path cargo-process--custom-path-to-bin)
         (path (and path (file-name-as-directory path)))
         (command (cargo-process--maybe-read-command (concat path command)))
         (project-root (cargo-process--project-root))
         (default-directory (or project-root default-directory)))
    (save-some-buffers (not compilation-ask-about-save)
                       (lambda ()
                         (and project-root
                              buffer-file-name
                              (string-prefix-p project-root (file-truename buffer-file-name)))))
    (setq cargo-process-last-command (list name command))
    (compilation-start command 'cargo-process-mode (lambda(_) buffer))
    (set-process-sentinel (get-buffer-process buffer) 'cargo-process--finished-sentinel)))

```

**Comment by npostavs** [comment]
Okay, I got it. `emacs -Q -l rust-mode.el -l yasnippet.el -f yas-global-mode -f rust-mode`
- Insert `pr` and `<tab>` to expand snippet above
- `C-c C-f` (`rust-format-buffer`)

`rust-format-buffer` works by erasing the whole buffer text, and somehow yasnippet gets confused about killing the snippets.

**Comment by npostavs** [comment]
Can you try out the patch in #819?

**Comment by xianghx** [comment]
Sorry,   I don't good at elisp.

**Comment by npostavs** [comment]
Ok, I've just merged it, if you're installing from MELPA the fix should be available in about 6 hours.

**Comment by xianghx** [comment]
Thanks.
