### ISSUE TITLE
Using yas-choose values on a line starting with #

### ISSUE THREAD

**Issue by kshenoy** [joaotavora/yasnippet#815]
I'm trying to define the following snippet in c++-mode:

    # -*- mode: snippet -*-
    # name: #include <...>
    # key: inc
    # --
    #include <${1:$$(yas-choose-value '("cassert" "cstdio" "cstdlib" "cstring" "iostream" "istream" "ostream"     "sstream" "array" "vector" "map"))}>

This doesn't work and it expands to

    #include <$(yas-choose-value '("cassert" "cstdio" "cstdlib" "cstring" "iostream" "istream" "ostream" "sstream" "array" "vector" "map"))}>

instead of showing the list. However, if I drop the `#` from `#include` then it works fine. What am I missing here?

**Comment by npostavs** [comment]
> What am I missing here?

You found a bug! Thanks. Should be fixed by #816.

**Comment by kshenoy** [comment]
Thank you! Glad I could help.
