### ISSUE TITLE
Why dose my yas work in cc-mode c-mode in php file?

### ISSUE THREAD

**Issue by machenchi0207** [joaotavora/yasnippet#817]
I do install php-mode and yas.But when i open a php file like main.php.I found that the yas worked in 'c-mode/cc-mode'.
Dose yas have php-mode ???

**Comment by npostavs** [comment]
Depends which php-mode you installed, but it probably derives from `c-mode`, e.g. https://github.com/ejmr/php-mode/blob/v1.18.2/php-mode.el#L982 `(define-derived-mode php-mode c-mode "PHP"...)`

> Dose yas have php-mode ???

The default snippet set doesn't come with php snippets, but you can write some. I found some by searching https://github.com/barendt/yasnippet-php-mode

**Comment by machenchi0207** [comment]
Thanks!
I just copy the php-mode folder to the yas snippets folder and it works!

**Comment by npostavs** [comment]
> I just copy the php-mode folder to the yas snippets folder and it works!

Just  a note: "yas snippets folder" should be `~/.emacs.d/snippets` and not `~/.emacs.d/elpa/yasnippet-xxxxxx/snippets`, the latter would be lost when you update the package.
