### ISSUE TITLE
ctrl-d should bypass all the surrounded placeholders

### ISSUE THREAD

**Issue by amosbird** [joaotavora/yasnippet#824]
```
# -*- mode: snippet -*-
# name: fn
# key: fn
# --
pub fn $1($2) ${3:-> $4} {
  $0
}
```
Type `ctrl-d` at ![](https://la.wentropy.com/296-.png) should delete `$4` as well and the cursor is expected to be at $0.

**Comment by npostavs** [comment]
Right, the problem is that parentage of "simple" fields like `$4` is never calculated. As a workaround, you can use `${4}`.

**Comment by amosbird** [comment]
hmm, `pub fn $1($2) ${3:-> ${4}} {` just generate a literal 4.

**Comment by npostavs** [comment]
Oops, I should have said `${4:}`.

**Comment by amosbird** [comment]
cool
