### ISSUE TITLE
snippet-mode should probably not derive from text-mode

### ISSUE THREAD

**Issue by yurikhan** [joaotavora/yasnippet#826]
To reproduce:

`M-x` yas-new-snippet `RET`

In the snippet body, type `${1:$(yas-subs|)}` and press `M-TAB`.

Ideal behavior: completion to `yas-substr`.

Acceptable behavior: completion fails, no effect.

Observed behavior: a huge list of aspell choices.

It’s not so clear cut — I can imagine a user wanting to use spell checking in snippets — but spell checking within code was unexpected.

**Comment by yurikhan** [comment]
The following hack works for me in Emacs 25.1:

```elisp
(defun yk-snippet-mode--elisp ()
  "Set up Elisp completion and Eldoc in snippet-mode."
  (add-function :before-until (local 'eldoc-documentation-function)
    #'elisp-eldoc-documentation-function)
  (setq-local completion-at-point-functions '(elisp-completion-at-point)))
(add-hook 'snippet-mode 'yk-snippet-mode--elisp)
(define-key snippet-mode-map (kbd "M-TAB") 'completion-at-point)
```

**Comment by npostavs** [comment]
> It’s not so clear cut — I can imagine a user wanting to use spell checking in snippets — but spell checking within code was unexpected.

Yes, it's the old multi-mode problem. I'm not going to be able to just magically come up with a perfect solution for that one, but it's probably worth switching `snippet-mode`'s parent to `prog-mode`. There might be some situations with `text-mode` snippets where the current `text-mode` parent is wanted, but they are the exception rather than the rule.

**Comment by joaotavora** [comment]
`<delurk>`

Ispell apparently has "region skipping" which could be added in snippet-mode's hook. From lisp/textmodes/ispell.el:

```
;; Region skipping:
;;  Place new regular expression definitions of regions you prefer not to
;;  spell check in `ispell-skip-region-alist'.  Mode-dependent features can
;;  be added to latex by modifying `ispell-tex-skip-alists'.
;;  `ispell-message' contains some custom skipping code for e-mail messages.
```

`</delurk>`
