### ISSUE TITLE
region active usage of yasnippet

### ISSUE THREAD

**Issue by amosbird** [joaotavora/yasnippet#827]
This is also asked in [SO](https://stackoverflow.com/questions/22735895/configuring-a-yasnippet-for-two-scenarios-1-region-is-active-2-region-is) . However the solution it mentioned doesn't work.
```
# -*- mode: snippet -*-
# contributor: lawlist
# key: bold
# name: bold
# binding: TAB <f6>
# --
`(if (region-active-p)
   (concat
     "{\\\\bf "
     yas-selected-text
     "}")
   "{\\\\bf $1}")`
```

I'm using emacs 25.2 . yasnippet 20170605.1940

**Comment by npostavs** [comment]
That solution seems a bit over-complicated, how about:
```
# -*- mode: snippet -*-
# contributor: lawlist
# key: bold
# name: bold
# expand-env: ((yas-wrap-around-region t))
# binding: TAB <f6>
# --
{\bf $0}
```

Reference: http://joaotavora.github.io/yasnippet/snippet-expansion.html#sec-1-2-1

**Comment by amosbird** [comment]
Thanks! but that won't differ from a non-region-active snippet. If I need `try-catch` snippet to behave differently according to region state, what should I do?

**Comment by npostavs** [comment]
> but that won't differ from a non-region-active snippet. If I need try-catch snippet to behave differently according to region state

I think that's what `yas-wrap-around-region` does, but maybe I don't understand what you mean...

**Comment by amosbird** [comment]
for active region, `$0` will be at `try` block while for non-active region, `$0` should be at `catch` block. Hmm, basicly, can we have `$*` instead of `$0` to replace the active region?

**Comment by npostavs** [comment]
Not quite sure I follow, does `yas-selected-text` help?

```
# -*- mode: snippet -*-
# key: bold
# name: bold
# binding: TAB <f6>
# --
{\bf `yas-selected-text`$1}
```

**Comment by amosbird** [comment]
ah, cool. works well with `# expand-env: ((yas-wrap-around-region nil))`
