### ISSUE TITLE
The correct way to resolve function conflict with auto-complete package

### ISSUE THREAD

**Issue by zw963** [joaotavora/yasnippet#828]
I use yasnippets with auto-complete with same binding `TAB`, it worked.

unless one case:

When I expand success a snippets, and when doing it, not finished, 
auto-complete's overelay complete function often make one key (e.g. ${1})
expand again.

So, I have to do is:

```cl
(defun ac/close () (interactive) (auto-complete-mode -1))
(defun ac/start () (interactive) (auto-complete-mode 1))
(add-hook 'yas-before-expand-snippet-hook 'ac/close)
(add-hook 'yas-after-exit-snippet-hook 'ac/start)
```

It worked, though, not so good.

I am wonder if exist more elegant way to do this.

Thanks

**Comment by zw963** [comment]
More explain;

After active yasnippets,  when i press `TAB` to try to switch to next  variable,
auto-complete is active... it use yasnippets as it source, and expand the key
in current cursor again ...

**Comment by npostavs** [comment]
I see that auto-complete uses priority 9999 for its overlays:
- https://github.com/auto-complete/auto-complete/blob/v1.5.1/auto-complete.el#L886
- https://github.com/auto-complete/auto-complete/blob/v1.5.1/auto-complete.el#L937

Perhaps increasing yasnippet's priority to 10000 would help?
```diff
--- i/yasnippet.el
+++ w/yasnippet.el
@@ -3500,7 +3500,7 @@ (defun yas--make-control-overlay (snippet start end)
                                nil
                                t)))
     (overlay-put overlay 'keymap yas-keymap)
-    (overlay-put overlay 'priority 100)
+    (overlay-put overlay 'priority 10000)
     (overlay-put overlay 'yas--snippet snippet)
     overlay))
 
@@ -3556,7 +3556,7 @@ (defun yas--make-move-active-field-overlay (snippet field)
           (make-overlay (yas--field-start field)
                         (yas--field-end field)
                         nil nil t))
-    (overlay-put yas--active-field-overlay 'priority 100)
+    (overlay-put yas--active-field-overlay 'priority 10000)
     (overlay-put yas--active-field-overlay 'face 'yas-field-highlight-face)
     (overlay-put yas--active-field-overlay 'yas--snippet snippet)
     (overlay-put yas--active-field-overlay 'modification-hooks '(yas--on-field-overlay-modification))
```

**Comment by zw963** [comment]
@npostavs , It worked! 

I want describe all process I do:

after change 100 to 10000, auto-complete overlay is still occur, 
e.g.
when I expand to `${1:id}`,  I change `id` to `head`, overlay is still pop,
show me `header`(head auto-complete to header)
(BTW:  if disabled auto-complete mode, overlay of cause is not happen, but that
not good too, anywhy.)

I have to say another issue which is disapper in current test maybe because some
my self-defined config is changed in auto-complete recently ... I am not very sure ...
this `header` is a key registered in yasnippets, in early version, when I press `TAB`
after `head`(with overlay `header`), will expand header recursively, it very anoise ..

OK, continue the current process,  When I press `TAB`, 

before 9999 change 10000, when press `TAB, `head`(with overlay `header`) is changed header,
and then press `TAB` again, then switch to next `${2:???}`.

after change 9999 to 10000, when press `TAB`, `head`(with overlay `header`) is ignore, and 
switch to next `${2:???}`, I personal prefer the second way, so, I close auto-complete-mode 
when expanding is happen ...

Thanks

**Comment by npostavs** [comment]
> It worked!

Great! I'm going to make the priority a custom option so you will be able to do `(setq yas-overlay-priority 10000)` in your init file.
