### ISSUE TITLE
If I chose a specfic one from yas-choose-value list, then trigger another snippet.

### ISSUE THREAD

**Issue by c02y** [joaotavora/yasnippet#830]
I have two snippets for org-mode

begin:

    # -*- mode: snippet -*-
    # name: begin
    # key: beg
    # --
    #+BEGIN_${1:$$(yas-choose-value '("SRC" "EXAMPLE" "QUOTE" "VERSE" "CENTER" "LaTeX" "HTML" "ASCII"))}
    $0
    #+END_$1

lang:

    # -*- mode: snippet -*-
    # name: lang
    # key: lang
    # --
    ${1:$$(yas-choose-value '("C" "C++" "emacs-lisp" "lisp" "latex" "python" "sh" "sqlite" "css" "haskell" "js" "plantuml" "ruby" "sql" "clojure"))}

So, my desire is, when I insert `beg` and hit `TAB` key, it will let me choose one from `SRC` and `EXAMPLE` et,. And if I choose `SRC`, I can continue to choose the language I need such as `C`, `emacs-lisp` et,.  Note that there is `$1` after `#+END_`, the `lang` part should affect the `#+END_` part.

Can I do that? I googled a while but didn't find the solution.

**Comment by npostavs** [comment]
You could try something like this:
```
# -*- mode: snippet -*-
# name: begin
# key: beg
# --
#+BEGIN${1:$$(let ((type (yas-choose-value '("_SRC" "_EXAMPLE"))))
               (if type (concat type (if (equal type "_SRC")
                                         (concat " " (yas-choose-value '("C" "C++" "emacs-lisp")))))))}
$0
#+END${1:$(car (split-string yas-text))}
```

**Comment by c02y** [comment]
Thanks. This is the my snippet if anyone needs it:

    # -*- mode: snippet -*-
    # name: begin
    # key: beg
    # --
    #+BEGIN_${1:$$(let ((type (yas-choose-value '("SRC" "EXAMPLE" "QUOTE" "VERSE" "CENTER" "LaTeX" "HTML" "ASCII"))))
                   (if type (concat type (if (equal type "SRC")
                                             (concat " " (yas-choose-value '("C" "C++" "emacs-lisp" "lisp" "latex" "python" "sh" "sqlite" "css" "haskell" "js" "plantuml" "ruby" "sql" "clojure")))))))}
    $0
    #+END${1:$(car (split-string yas-text))}
