### ISSUE TITLE
yasnippets shuns generic modes  

### ISSUE THREAD

**Issue by taurgal** [joaotavora/yasnippet#831]
The yasnippet table for generic modes (defined using define-generic-mode) does not seem to be loaded. However saving a snippet for this mode does load it (bu not the others) into he correct table. I trie to debug this and apparently fundamental mode seems to be triggered and yasnnipet actually loads the table for fundamental mode.
To reproduce:
-Step 1: define a generic mode
 `(define-generic-mode dummy-mode  nil nil nil nil nil nil)`
- Step 2: create a snippet for this mode in the right directory and do a
 `(yas-reload-all)`
- Step 3: open some buffer and do M-x dummy-mode
- Step 4: try to insert a snippet (<kbd>C-c & C-s</kbd>)

Now to be sure you dit not mistype anything:

- Step 5: goto the snippet you just create it, modify it and them save. You
  shoud sea a message telling you it's been loaded in the dummy-mode table
- Step 6: goto the buffer in dummy-mode and chack that you can insert the snippet (<kbd>C-c & C-s</kbd>)

**Comment by taurgal** [comment]
And If I crate a new snippet (<kbd>C-s & C-n</kbd>) in a buffer in dummy-mode
then yasnippet creates a buffer with file mymainsnipetdir/fundamental-mode/dummy-mode
but creating a snippet there does not work either (except when you modfy+save it, like in
mymainsnipetdir/dummy-mode)

**Comment by npostavs** [comment]
Hmm, works for me. What Emacs version? What does `M-x yas-describe-tables` show you?

What *exact* steps did you use? e.g., it seems your description misses one of `M-x yas-global-mode` or `M-x yas-minor-mode`. Can you reproduce this from [`emacs -Q`][emacs-Q]?

[emacs-Q]: http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html
