### ISSUE TITLE
Cannot tab out of field

### ISSUE THREAD

**Issue by mankoff** [joaotavora/yasnippet#832]
I'm having trouble tabbing out of a field that uses `completing-read` or `ido-completing-read`. I've tried to distill this to an MWE as below. I can recreate the bug with the following commands:

```
$ emacs --version
GNU Emacs 25.2.1

$ cd /tmp/
$ git clone https://github.com/joaotavora/yasnippet.git yasnippet-bug
$ cd yasnippet-bug
$ git log -1 --oneline
65952e3 (HEAD -> master, origin/master, origin/HEAD) Allow customizing overlay priority
$ HOME=$PWD emacs -L . debug.org
```

Where the contents of `debug.org` follow. In `debug.org` I do the following:

1. Press C-c C-c within the code blocks below to execute them.
2. Move cursor to "bc_".
3. Expand snippet. Enter a number for field $1, then <TAB> to move to field $2.
4. Try to select an account, and then press <TAB> to move to next field.
5. Issue: I cannot leave field $2.

```
#+BEGIN_SRC elisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '((emacs-lisp . t)   
   (sh . t)))
(setq org-confirm-babel-evaluate nil) ;; don't ask to eval code
#+END_SRC
#+RESULTS:

Set up beancount and snippet
#+BEGIN_SRC sh
# Fetch beancount-mode
wget https://bitbucket.org/blais/beancount/raw/1e21b27c0b0ecf2bf2e1a2cd5c3da3b1befc8152/src/elisp/beancount.el
# prep the snippets folder
mkdir -p snippets/org-mode
#+END_SRC
#+RESULTS:

Activate yasnippet and beancount mode
#+BEGIN_SRC elisp
(org-babel-tangle)    ; create the snippet from code block below
(require 'yasnippet)  ; load yasnippet
(yas-global-mode 1)
(load-file "beancount.el") ; load beancount
(beancount-mode)            ; enable beancount
#+END_SRC
#+RESULTS:
: t

bc_


2017-07-01 open Assets:Foo         USD
2017-07-01 open Assets:Bar         DKK
2017-07-01 open Assets:Baz         CHF


#+BEGIN_SRC sh :tangle ./snippets/org-mode/bc
# -*- mode: snippet; require-final-newline: nil -*-
# name: beancount
# key: bc_
# expand-env: ((yas-indent-line 'fixed) (yas-wrap-around-region 'nil))
# type: snippet
# binding: direct-keybinding
# --
`(format-time-string "%Y-%m-%d")` * "$1"
  ${2:$$(call-interactively 'beancount-insert-account)}    $3 USD
  ${4:$$(call-interactively 'beancount-insert-account)}   -$3 USD
#+END_SRC
#+RESULTS:
```

**Comment by mankoff** [comment]
On further investigation, I think this might be because fields $2 and $4 are getting text inserted. I don't actually want to type anything, just have the output of the selection. I can get things to mostly work by changing the snippet to:

```# --
`(format-time-string "%Y-%m-%d")` * "$1"
    `(call-interactively 'beancount-insert-account)` $2 USD
    `(call-interactively 'beancount-insert-account)` -$2 USD
```

However, the `(call-interactively` functions fire first. I'd like it to be the `(format-time-string)` first, then $1, then the first `(call-interactively)`, then $2 (and mirror), then the last function.

According to https://joaotavora.github.io/yasnippet/snippet-development.html#sec-3-2, 

> Emacs-Lisp code can be embedded inside the template, written inside back-quotes (`). The lisp forms are evaluated when the snippet is being expanded.

Can I select the order of evaluation? Or delay the evaluation until I hit `TAB`?

**Comment by npostavs** [comment]
You can't have that much control with a standard snippet, I think you will be better off with a `#type: command` snippet.

http://joaotavora.github.io/yasnippet/snippet-development.html#sec-2-7

**Comment by mankoff** [comment]
I saw the `command` option. I'm fairly new to Yasnippet and there are no examples of this feature. Any chance you can provide a basic example? I know how to insert text, but how would I implement tabbing through the $2 field (or equivalent), and/or mirroring?

**Comment by npostavs** [comment]
Currently the only thing you can easily do is generate snippet text and then expand it, which, now that I think about it, means you might not be able to get the order you want that way after all. But looking again, you said

> I don't actually want to type anything, just have the output of the selection.

Does it work if you use `(completing-read "Account: " #'beancount-account-completion-table nil t)` instead of `(call-interactively ...)`?

**Comment by mankoff** [comment]
With that change, I get the prompt, but the table is empty so I cannot select anything or type anything. When I press `Enter` though, the behavior appears correct. It leaves the (empty) field and moves on to the next '(completing-read)`, then to `$2`.

**Comment by mankoff** [comment]
Oddly, evaluating `(beancount-get-accounts)` returns a list of accounts in the modeline, but evaluating `(completing-read "Account: " (beancount-get-accounts))` does not seem to work. At this point, I'm not sure this is a yasnippet issue :(.

**Comment by npostavs** [comment]
I'm not sure how the completion candidates get setup by beancount-mode exactly, but using `beancount-accounds` seems to be working for me. I've remembered now there are some tricks you need to avoid re-evaluating the prompt every time the field is modified again (which is what is happening in your original problem report), these are all conveniently encapsulated in the `yas-choose-value` function:
```
# -*- mode: snippet; require-final-newline: nil -*-
# name: beancount
# key: bc_
# expand-env: ((yas-indent-line 'fixed) (yas-wrap-around-region 'nil))
# type: snippet
# binding: direct-keybinding
# --
`(format-time-string "%Y-%m-%d")` * "$1"
  ${2:$$(yas-choose-value beancount-accounts)}    $3 USD
  ${4:$$(yas-choose-value beancount-accounts)}   -$3 USD
```

http://joaotavora.github.io/yasnippet/snippet-development.html#sec-3-8

**Comment by mankoff** [comment]
Yes this works for me. Thank you! Not a yasnippet bug, just a programmer error as usual.

**Comment by npostavs** [comment]
Yeah, I probably would have figured it out sooner if I had just executed your execellent example right off the top. That org-babel stuff is quite convenient!

**Comment by mankoff** [comment]
If you use emacs, I think Org is a fundamental shift for good in almost any workflow.
