### ISSUE TITLE
Allow displaying a message when reaching a field

### ISSUE THREAD

**Issue by notetiene** [joaotavora/yasnippet#833]
I was wondering if it would be possible to display a message when reaching a placeholder field.  This should of course be user-interface agnostic (the message could be displayed in the minibuffer or a popup).

One way to do that right now is by adding mirror transformation:
```elisp
(declare ${1:declare_spec$(prog1 (when yas-modified-p yas-text) (message "Function or Macro specifications"))})
```
However, I found that the Lisp code can become quite large and it doesn't allow using many other user interface features.

**Comment by notetiene** [comment]
One way to implement that feature would be to use the directive section.  We could for example use a `field-messages` section.

```
# -*- coding: utf-8; mode: snippet -*-
# name: declare
# group: Definition
# key: declare
# field-messages: ("Function or Macro specifications" nil)
# --
(declare ${1:declare_spec})
${2:other_placeholder}
```

Of course the directive name could be an other one.

**Comment by npostavs** [comment]
> (the message could be displayed in the minibuffer or a popup).

I can't imagine anyone wanting a popup every time a field is entered, wouldn't that interfere with actually entering text and stuff?

> One way to implement that feature would be to use the directive section. We could for example use a `field-messages` section.

I think I would rather just allow binding some `yas-entered-field-hook` variable in the `expand-env` section.

**Comment by notetiene** [comment]
> I can't imagine anyone wanting a popup every time a field is entered, wouldn't that interfere with actually entering text and stuff?
I was actually thinking about the company-mode style popup.  It doesn't alter the way we enter text.  That also doesn't mean it could be disabled.

> I think I would rather just allow binding some `yas-entered-field-hook` variable in the `expand-env` section.
That's a good suggestion, but it means we would have to re-implement the same functions each times we write a snippet with messages.  Having a list of the messages would be a work-around.

Of  course, the functionality wouldn't be for experienced users (unless an obscure snippet).  I'm thinking about that for new comers as a didactic behavior.

**Comment by npostavs** [comment]
> we would have to re-implement the same functions each times we write a snippet with messages.

I don't think so, you could have something along the lines of
```elisp
(defun yas-print-field-messages (...)
  ...
  (mapc #'print yas-field-messages)
  ...)

;; Suggested .emacs setting for new comers wanting "didactic behavior"
(add-hook 'yas-entered-field-hook #'yas-print-field-messages)
;; Or we else we have that as default, and suggest experts do
(remove-hook 'yas-entered-field-hook #'yas-print-field-messages)
```
and then in the snippet
```
# expand-env: ((yas-field-messages '("a useful message...")))
```

**Comment by npostavs** [comment]
I don't see any movement on this, and I have no plans to implement it myself; closing.
