### ISSUE TITLE
Too many git sub-modules

### ISSUE THREAD

**Issue by eflanigan00** [joaotavora/yasnippet#834]
I understand sharing code but there are too many sub-modules in this project.
I think these should be dependencies of this project. If that is too much place them directly into the project.

**Comment by npostavs** [comment]
> here are too many sub-modules in this project.

Too many for what? Can you describe what the actual problem you encounter is?

**Comment by eflanigan00** [comment]
I frequently take these packages offline (or behind a firewall) and keep a local melpa. In order to clone them properly I have to change the repo so the sub-modules are pointing to the correct location. This makes it more difficult for me to update to your latest because I have to mess with the git submodules every single time.  

I understand yasnippet-snippets being a sub-module but the rest are less than ideal. 

I think making those sub-modules dependencies provides more transparency from a package installation perspective. Or simply add them to the project because the sub-modules don't appear to be changing.

**Comment by npostavs** [comment]
> I understand yasnippet-snippets being a sub-module but the rest are less than ideal.

By "the rest" you mean the yasmate submodule?

---

> I frequently take these packages offline (or behind a firewall) and keep a local melpa. In order to clone them properly I have to change the repo so the sub-modules are pointing to the correct location.

Perhaps you are missing [`submodule.alternateLocation `](https://git-scm.com/docs/git-config#git-config-submodulealternateLocation) or [`url.<base>.insteadOf`](https://git-scm.com/docs/git-config#git-config-urlltbasegtinsteadOf)?

Altough I'm a bit confused why you need to clone more than once...

> <dt class="hdlist1" id="git-config-submodulealternateLocation"> <a class="anchor" href="#git-config-submodulealternateLocation"></a>submodule.alternateLocation </dt>
> <dd>
> <p>Specifies how the submodules obtain alternates when submodules are
> cloned. Possible values are <code>no</code>, <code>superproject</code>.
> By default <code>no</code> is assumed, which doesn’t add references. When the
> value is set to <code>superproject</code> the submodule to be cloned computes
> its alternates location relative to the superprojects alternate.</p>

> <dt class="hdlist1" id="git-config-urlltbasegtinsteadOf"> <a class="anchor" href="#git-config-urlltbasegtinsteadOf"></a>url.&lt;base&gt;.insteadOf </dt>
> <dd>
> <p>Any URL that starts with this value will be rewritten to
> start, instead, with &lt;base&gt;. In cases where some site serves a
> large number of repositories, and serves them with multiple
> access methods, and some users need to use different access
> methods, this feature allows people to specify any of the
> equivalent URLs and have Git automatically rewrite the URL to
> the best alternative for the particular user, even for a
> never-before-seen repository on the site.  When more than one
> insteadOf strings match a given URL, the longest match is used.</p>
> <div class="paragraph">
> <p>Note that any protocol restrictions will be applied to the rewritten
> URL. If the rewrite changes the URL to use a custom protocol or remote
> helper, you may need to adjust the <code>protocol.*.allow</code> config to permit
> the request.  In particular, protocols you expect to use for submodules
> must be set to <code>always</code> rather than the default of <code>user</code>. See the
> description of <code>protocol.allow</code> above.</p>

**Comment by eflanigan00** [comment]
First I clone your repo, no problem there. Then I bring that clone behind a firewall with approval.
I then use a local melpa to build the packages. Melpa clones the repository. In order for this to work I have to change all of the git submodules to point to the correct location.  I will look at the options you provided above.

**Comment by npostavs** [comment]
> I frequently take these packages offline (or behind a firewall) and keep a local melpa. In order to clone them properly I have to change the repo so the sub-modules are pointing to the correct location. This makes it more difficult for me to update to your latest because I have to mess with the git submodules every single time.
[...]
> First I clone your repo, no problem there. Then I bring that clone behind a firewall with approval.

Ah, I wonder if it would be easier to bring in updates via [git bundle](https://git-scm.com/docs/git-bundle) instead of cloning anew every time.

---

Anyway, to the question of the submodules themselves, there is an idea to separate the snippets submodule, see #775. For the yasmate submodule, it's optional and written in ruby not elisp, so it would not work as a package dependency. We could drop the formal submodule pointer and just have a link to it in the README I suppose.

**Comment by eflanigan00** [comment]
I love the idea of snippets being a separate! That way it would be very clear what was being installed.  
The yasmate goes like this from what I see:
yasmate/bundles
There are 4 submodules:
html-tmbundle
objc-tmbundle
rails-tmbundle
ruby-tmbundle

This makes it a long process for me to update all of the submodules to point to my offline clone.

I'm not sure if git bundle or other would work because I'm using melpa which calls recursive clone.
