### ISSUE TITLE
`expand-env` not honored if snippet called from `(yas-expand-snippet)`.

### ISSUE THREAD

**Issue by mankoff** [joaotavora/yasnippet#835]
This can be seen by looking at the expansion of any snippet with `expand-env` in the body. For example:

    (yas-expand-snipped (yas-lookup-snippet "case : {...}" 'cc-mode))

returns

> "case ${2:constexpr}:${3: \\{}
>     $0
>     break;
> ${3:$(if (string-match \"\\{\" yas-text) \"\\}\" \"\")}"

not
```

# -*- mode: snippet -*-
# name : case : {...}
# key: case
# expand-env: ((yas-also-auto-indent-first-line t))
# --
case ${2:constexpr}:${3: \{}
    $0
    break;
${3:$(if (string-match "\{" yas-text) "\}" "")}
```

**Comment by npostavs** [comment]
Yeah, it's been in the back of my mind that I made a mistake by having `yas-lookup-snippet` return the snippet content instead of the `yas--template` struct. I will change this after the release.
