### ISSUE TITLE
expand and undo, then some characters are missing

### ISSUE THREAD

**Issue by sunwayforever** [joaotavora/yasnippet#839]
I have made a screen cast here:

https://asciinema.org/a/Q3u88yANnidkoqpjTokY1TMFX

generally, I input `for`, then press `tab` to expand it, after that, I press `C-/` to undo, then some chars are missing...

--- 
it seems that this snippet will cause the problem:

> for $1; $2; $3 {
>    $0
>}

while this one is ok:

> for $1; $2; $3 {
>
>}

**Comment by npostavs** [comment]
Which yasnippet version are you using? This sounds similar to #821 which should be fixed in the latest release (0.12.1).

**Comment by sunwayforever** [comment]
yeah, it is already fixed in the latest release, many thanks~
