### ISSUE TITLE
When  binding snippet is expanded, region keep active.

### ISSUE THREAD

**Issue by zw963** [joaotavora/yasnippet#840]
Following is a emacs lisp example:

```cl
# -*- mode: snippet -*-
# name: progn
# key: progn
# binding: M-c p
# condtion: (yas-use-region-p)
# --
(progn
`(yas-selected-text)`$0
)
```

Suppose exist a following code:

```cl
(forward-char)
(forward-char)
```

When I set mark, and select those two line, press `M-c p`,
what I expect is: 

```cl
(progn
  (forward-char)
  (forward-char)
)

current, it still worked, but, the mark still active, I have to press `C-g` again to
cancel that.
```

**Comment by npostavs** [comment]
Hmm, probably due to #799.

**Comment by zw963** [comment]
Yes, after delete that line, it worked!

Hope can add add regression test for protect those behavior not broken again.

**Comment by npostavs** [comment]
Please try #846 for this. Unfortunately, it seems very difficult to test for region (de)activation in automated tests, as it involves the command loop which normal functions don't get to run by themselves.

**Comment by zw963** [comment]
@npostavs , Cool, I tried, it worked.

**Comment by npostavs** [comment]
Thanks for testing, I'll have to think whether I should release 0.12.2 with this fix, or just leave it until 0.13

**Comment by zw963** [comment]
hmmm, @npostavs , I think you should release 0.12.2. :smile:

That is a big fix i think, good news is those bugs is very more few than ever for those mouths

**Comment by npostavs** [comment]
Yes, I think will release 0.12.2 within the next week or so (see #849). Hopefully it will be the last 0.12.x release.
