### ISSUE TITLE
whitespace-mode isn't turned on after yas-new-snippet

### ISSUE THREAD

**Issue by h-youhei** [joaotavora/yasnippet#842]
## Reproducing
emacs -Q
`(package-initialize)` C-j
`(global-whitespace-mode 1)` C-j
`(yas-global-mode 1)` C-j
M-x `find-file` RET some-file.html

M-x `yas-new-snippet`
There's no highlight

M-x `whitespace-mode`
highlight is coming

Additionally, while replace `yas-new-snippet` to `yas-visit-snippet-file`,
whitespace-mode is turned on.

## Environment
- OS: Arch Linux
- Emacs: 25.2.1 gtk
- yasnippet 20170723.1530
- whitespace-mode 13.2.2

**Comment by npostavs** [comment]
Hmm, turns out `global-whitespace-mode` doesn't like the leading `*` in the buffer name.
