### ISSUE TITLE
Counterintuitive behaviour of yas-expand-snippet

### ISSUE THREAD

**Issue by kskyten** [joaotavora/yasnippet#843]
When I run `(yas-expand-snippet "${a} ${b} nil nil '((a "foo")))` I expected to get "foo |b", where the pipe signifies the cursor. Instead, I got exactly the opposite (i.e. "|a b"). Am I using the function correctly?

**Comment by npostavs** [comment]
The first string argument should use snippet syntax, so something along the lines of:
```elisp
(yas-expand-snippet "`a` ${b}" nil nil '((a "foo")))
```

Refer:

[Writing snippets: Embedded Emacs-lisp code](http://joaotavora.github.io/yasnippet/snippet-development.html#sec-3-2)
[Writing snippets: Placeholder fields](http://joaotavora.github.io/yasnippet/snippet-development.html#sec-3-4)

**Comment by kskyten** [comment]
Thanks, that worked.
