### ISSUE TITLE
Default text is not deleted when new tex is inserted using another snippet

### ISSUE THREAD

**Issue by rrittwikc** [joaotavora/yasnippet#844]
Suppose I have two snippets
```
#name : (lambda)
#binding : M-l l
# --
\\lambda
```
and
```
#name : (Function)
# --
${1:f} \\colon ${2:\\mathbb\{R\}} \\to ${3:\\mathbb\{R\}}
```

I first invoke the second snippet and immediately after that press M-l l to invoke the first snippet.
What I get is
```
\lambdaf \colon \mathbb{R} \to \mathbb{r}
```
Notice the `f` after `lambda`.
The expected outcome would be
```
\lambda \colon \mathbb{R} \to \mathbb{r}
```

I have downloaded yasnippet from this repo and installed it manually.

My yasnippet settings is
```
(require 'yasnippet)
(setq yas-snippet-dirs '("~/.emacs.d/snippets"))
(setq yas-indent-line (quote fixed))
(yas-global-mode 1)
```

Also I added the following for `ido-completing-read+-mode`
```
(require 'ido-completing-read+)
(ido-ubiquitous-mode 1)
(setq ido-cr+-nil-def-alternate-behavior-list
   (quote
    ("\\`describe-\\(function\\|variable\\)\\'" "\\`wl-" "\\`ebal-" webjump where-is find-tag "\\`etags-select-" imenu--completion-buffer project--completing-read-strict bookmark-completing-read yas-completing-prompt)))
```

**Comment by npostavs** [comment]
Could you try out the patch in #845 please?

**Comment by rrittwikc** [comment]
Thanks. Now it works perfectly! So I am closing this issue.

Thanks again for this amazing template plugin! I use it every day.

**Comment by rrittwikc** [comment]
I am reopening this issue because the patch introduced a new bug in yasnippet.

Suppose I have two snippets

```
#name : (Choose value test)
#binding : M-l M-p
# --
\\${$$(yas-choose-value '("a" "b" "c"))}
```

and

```
#name : (alpha)
#binding : M-l a
# --
\\alpha
```

Now I first press `M-l M-p` to invoke the first snippet and press `Enter` to select `a`.
Immediately after that I press `M-l a` to invoke the second snippet.

Expected output
`a\alpha`

Actual output
`\aYASESCAPE92PROTECTGUARDalpha`

However after pressing `M-l M-p` and `Enter` if I press `Tab` before pressing `M-l a` everything is as expected.
So I think two things are happening
  1. Even after pressing Enter I am still in `yas-choose-value`.
  2. I can't expand a snippet when I am in `yas-choose-value`.

Without this patch this particular bug is not there.

So without the patch I get the expected output but the snippet insertion does not delete field content.
With this patch yasnippet deletes field content but does not work if snippet is inserted in the `yas-choose-value`.

Thanks

**Comment by npostavs** [comment]
> I am reopening this issue because the patch introduced a new bug in yasnippet.

Thanks for reporting this. Clearly that `yas--inhibit-overlay-hooks` is very much needed after all.

I wrote another patch, see #857.

**Comment by rrittwikc** [comment]
The previous two cases are now working as expected.
Thank you for your time and hard work.

However, I would like to report another problem which is related to the current problem and the `yas-selected-text`.

Consider two snippets

```
#name : (Snippet 1)
#key : fn
# --
${1:f}$0
```

and

```
#name : (Snippet 2)
#binding : M-l M-t
# --
\\${$$(yas-choose-value '("textbf{" "textit{"))}`yas-selected-text`}
```

I first invoke the Snippet 1 and immediately next I invoke Snippet 2 (by pressing `M-l M-t`).

`yas-selected-text` prevents the deletion of `f` in Snippet 1.

I think there are two expected outputs

Expected output 1:
`\textbf{|}`
`|` is the cursor.
This I get if `yas-selected-text` is not there in Snippet 2.

Expected output 2:
`\textbf{f}`
where if I press `a` immediately after invoking Snippet 2 then I should get
`\textbf{a}`

Currently I get
`\textbf{f}`
But if I press `a` immediately I get
`\textbf{af}`

So the default text of one snippet becomes permanent text due to the presence of `yas-selected-text` in another snippet.

**Comment by npostavs** [comment]
Hmm, I don't think that is a bug. Any text you put in that position becomes permanent, e.g., with `\\${$$(yas-choose-value '("textbf{" "textit{"))}some-text}` you get `\textbf{|some-text}`.

Could you explain why you want `yas-selected-text` there?

**Comment by rrittwikc** [comment]
In
```
\\${$$(yas-choose-value '("textbf{" "textit{"))}`yas-selected-text`}
```
I want `yas-selected-text` because then I can wrap a text which is already present in the file quickly.
In Latex if I want to bold a text quickly which is already present in the tex file, I just select the text and invoke the snippet.

I thought by _default text_ we mean a text which will be inserted **only if** the user does not do any further action on that particular place holder.

So in the above two snippets first I get the default text `f` then I immediately invoke another snippet there.
So should not it first delete the default text (because I did some further action) and then insert the content of the next snippet even if the next snippet has 'yas-selected-text'? I am talking about expected output 1 of my last comment.

You are absolutely correct that If I have `\\${$$(yas-choose-value '("textbf{" "textit{"))}some-text}` then I get `\textbf{|some-text}`.
But there is no _some-text_, if yasnippet deletes snippet 1's _default text_ (which is `f`) before inserting the content of snippet 2.
In this case `yas-selected-text` will not find `f` as that has already been deleted.

So what I am trying to say is that yasnippet is not deleting the default text when I invoke another snippet which has `yas-selected-text`.

If `f` is not a default text then everything is fine, but since `f` **is** a default text should not yasnippet delete it first before do any further action on that place holder?

**Comment by npostavs** [comment]
So there are a couple for things happening here:

1. The current patch in #857 sets the deleted snippet field text as `yas-selected-text`. It would be easy to just drop it instead, then you would get expected output 1.

2. Your snippet puts `yas-selected-text` outside of any field, therefore the deletion of field contents of course never works on it.

3. But even if you did put it into a field, it would still not work, because currently Yasnippet considers a computed initial value to be a modification to the default, and hence would not delete it. Changing that is tricky: e.g., in the case of `yas-choose-value` you probably wouldn't want that to be deleted. Perhaps some new notation for deleteable default value could be introduced, but I'm rather reluctant to add any new syntax, as the current parsing code is kind of a mess.

**Comment by rrittwikc** [comment]
Ok... after some thoughts I think the patch is perfectly fine.
In any case a user who needs to delete an arbitrary long default text can do that in two keystrokes.
However if a user needs the default text to be wrapped, the patch is automatically doing that.
I have tested a few other things... and everything is fine.

Thanks again for your time and efforts.
I am closing this issue.

**Comment by joaotavora** [comment]
>  as the current parsing code is kind of a mess.

*whistles*

That's certainly true. Unfortunately, I don't have time to work on the snippet-engine branch any time soon. But it was very close to being useful, @monnier was following along, and the implementation is a much nicer and more interesting thing to work with.

**Comment by npostavs** [comment]
> Ok... after some thoughts I think the patch is perfectly fine.
> In any case a user who needs to delete an arbitrary long default text can do that in two keystrokes.

Well, I'm still considering dropping the deleted field text rather than save it to `yas-selected-text`, the use cases are a bit obscure so it's hard to decide which way makes more sense.

**Comment by rrittwikc** [comment]
I think the case we are discussing is an edge case.
So as you said earlier as long as dropping the deleted field text does not add more complexities to the existing code, it is fine.

**Comment by npostavs** [comment]
Okay, I've merged a version of the patch which does drop the field text. We'll see how it goes.

---

> the [snippet-enging] implementation is a much nicer and more interesting thing to work with.

To be honest, I'm kind of skeptical of anything based on eieio working out. This is probably just personal bias, but I don't know of any really successful projects using it. On the other hand, magit's lead maintainer is planning on using it more, so perhaps I'll be persuaded...
