### ISSUE TITLE
Yasnpipet snippets finally packaged

### ISSUE THREAD

**Issue by AndreaCrotti** [joaotavora/yasnippet#848]
With this PR:
https://github.com/AndreaCrotti/yasnippet-snippets/pull/203

I finally packaged `yasnippet-snippets` properly.
It's not merged yet, but at the moment this snippets are set as a git submodule, I wonder if that should change after it's properly packaged.
Any thoughts about that?

**Comment by AndreaCrotti** [comment]
Actually to be precise, I suspect that as soon as I merge that the solution using the git submodule won't work anymore, since the snippets have been moved all into a subdirectory, is that correct?

I've already made yasnippet-snippets depend on yasnippet, would be good to have a way to do the reverse depedency at the package level but keep it optioinal somehow.

Any thoughts about this @joaotavora ? 
Thanks!

**Comment by npostavs** [comment]
I'm thinking to make a 0.12.2 release soon without changing anything about the snippets, then remove the submodule afterwards for what will become 0.13.x. The submodule points to a particular commit, so my hope is that old versions continue to work just fine. The melpa recipe might be a problem though, we'll see.

> I've already made yasnippet-snippets depend on yasnippet, would be good to have a way to do the reverse depedency at the package level but keep it optioinal somehow.

AFAIK, package.el has no concept of optional dependencies.

**Comment by AndreaCrotti** [comment]
Ok thanks a lot @npostavs 
so it's safe to merge my branch then right?

What do you think could be a problem with the melpa recipe by the way I'm not sure I understand?
And well ok if you can't declare optional dependency we can just point out in the Yasnippet docs, in the end it will be only one step in the same way as it currently is using the git submodule.

**Comment by joaotavora** [comment]
> The submodule points to a particular commit, so my hope is that old versions continue to work just fine. 

Yes i also expect it to be.

> The melpa recipe might be a problem though, we'll see.

Yes, how do you plan to organize dependencies? What should happen if I just install `yasnippet`? What about just `yasnippet-snippets`? 

In my view `yasnippet-snippets` should be a recommended package of snippets but not mandatory. I seem to read that that is the intention right now. But as you note package.el doesn't have that concept yet.

If that is indeed your intention, perhaps a little bit of code could be added to yasnippet that detects whether the snippet library is completely empty and warns the user.

**Comment by npostavs** [comment]
> so it's safe to merge my branch then right?

As far as I can tell, yes.

> What do you think could be a problem with the melpa recipe by the way I'm not sure I understand?

I'm not entirely sure. It currently references the `snippets/` directory, will it break if I delete that directory? If I remove the reference to `snippets/` does it break the recipe for older commits (thinking of melpa-stable here) that still have the `snippets/` directory?

> What should happen if I just install yasnippet?

You just get yasnippet, without any snippets.

> What about just yasnippet-snippets?

I think it should depend on `yasnippet`, so in this case you get yasnippet installed as well.

> If that is indeed your intention, perhaps a little bit of code could be added to yasnippet that detects whether the snippet library is completely empty and warns the user.

That seems sensible.

**Comment by AndreaCrotti** [comment]
Ok @npostavs @joaotavora I merged that branch, and it will soon be available on melpa:
https://github.com/melpa/melpa/pull/4904

From my understanding you could remove the git submodule but maybe just keep an empty `snippets` directory?
That would still make `yasnippet` happy, and if they will later on install `yasnippet-snippets` separately that will be automatically loaded anyway, right?

**Comment by npostavs** [comment]
Possibly we don't even need to remove `snippets` from the recipe, I'll need to dig up my melpa repo to test this...

**Comment by npostavs** [comment]
> Possibly we don't even need to remove snippets from the recipe, I'll need to dig up my melpa repo to test this...

This indeed seems to be the case, the non-existent `snippets` directory is simply ignored.
