### ISSUE TITLE
[Feature Request] make auto-indent configurable when expanding a snippets

### ISSUE THREAD

**Issue by zw963** [joaotavora/yasnippet#850]
Hi, this is a feature which discussed in another issue before.
I create a seprate issue for this, because I think this is a breaking change between
old version with new version.

Following is example snippets for ruby mode

``` cl
# -*- mode: snippet -*-
# name: def
# key: def
# --
def ${1:meth}
$0
end
```

When this snippets is expand, old version got:

``` rb
def meth
  |                   # <=  here is auto-indent according to current mode
end
```
But, new version, wo got.

``` rb
def meth
|
end
```
we have to press extra once TAB again to run `indent-according-to-mode`, to get same
effect as first.

@npostavs, I know what you thought about this is: https://github.com/joaotavora/yasnippet/issues/710#issuecomment-228335386

But i think add a variable to permit fallback old behavior is more good, anywhy,
we have so many snippets which not add space, for every snippets, we have to
press extra once TAB.

Thanks

**Comment by npostavs** [comment]
Hmm, I guess it would be pretty easy to add that.

**Comment by zw963** [comment]
@npostavs , from my point of view, i think

```rb
def meth
  |                   # <=  When cursor is onto this position ($0) the next step always
                      # <=  input somethings or remove this empty line entirely, 
                      # <= why just keep a empty line like this?
                      # <=  we can always autoremove leading whitespaces in `afer-save-hook`
end
```
I think better default is old behavior, though, an toggle is enough for me if you think new
behavior is better.

**Comment by zw963** [comment]
remember that. about #685 

for my local yasnippets.el, I always revert this commit myself.

and, when I replace with new yas version, I forget to modified it again ...

**Comment by zw963** [comment]
@npostavs , seem like revert #685, this hack not worked any more.
code base is changed.

**Comment by npostavs** [comment]
Okay, #851 should cover it. Since is for backwards compatibility I will probably include it in 0.12.2.

**Comment by zw963** [comment]
@npostavs , worked. following is my config for this:

```sh
(setq yas-indent-line 'auto)
(setq yas-also-auto-indent-first-line t)
(setq yas-also-indent-empty-lines t)
```

I doubt, another two config is necessory?

**Comment by npostavs** [comment]
`(setq yas-indent-line 'auto)` is the default, so you don't need it, but it doesn't hurt.  `(setq yas-also-auto-indent-first-line t)` is only needed if you want the first line to be indented, it is an independent setting. The `yas-also-indent-emty-lines` setting will also work without it.

**Comment by zw963** [comment]
> The yas-also-indent-empty-lines setting will also work without it.

What this means? if not set it, the default value is nil, which not indent empty line.

**Comment by npostavs** [comment]
I meant if you do

```elisp
(setq yas-indent-line 'auto)
(setq yas-also-auto-indent-first-line nil) ; <- this has no effect on `yas-also-indent-empty-lines'.
(setq yas-also-indent-empty-lines t)
```
it should still work. I extended the test in #851 to check this.

**Comment by zw963** [comment]
@npostavs , Thanks, I only left one line, it worked too.

**Comment by npostavs** [comment]
Thanks for testing.

**Comment by zw963** [comment]
Hi, @npostavs ,  this hack is not working after update to 9f51cf2

When i fallback to old version, it work.

Thanks.

**Comment by zw963** [comment]
My current working version is: 0.12.1, hi, 

@npostavs , does you missing my previous reply?

Thanks. :smile:

**Comment by npostavs** [comment]
@zw963 Works for me, does the `yas-also-indent-empty-lines` test pass for you?

**Comment by zw963** [comment]
@npostavs , i never run this test myself.
Following is my attempt:

```sh
 ╰─ $ /usr/bin/emacs -nw -Q -L . -l yasnippet-tests.el --batch -e ert
Symbol’s value as variable is void: lisp-el-font-lock-keywords-for-backtraces
 ╰─ $ emacs --version
GNU Emacs 26.1
Copyright (C) 2018 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```
```sh
 ╰─ $ 130  ls *.el
backtrace.el  ert.el  ert-x.el  yasnippet-debug.el  yasnippet.el  yasnippet-tests.el
```

`backtrace.el`  `ert.el`  `ert-x.el` is download from github mirrors

**Comment by zw963** [comment]
After some hack, test is running.

It seem like all test is passed.

```sh
╭─ 21:00  zw963 ⮀ ~/Git/yasnippet ⮀ ⭠ (9f51cf2) master % u=  ➦ ruby-2.5.1 
 ╰─ $ /usr/bin/emacs -nw -Q -L . -l yasnippet-tests.el --batch -e ert
Run tests (default t): t

[yas] Prepared just-in-time loading of snippets successfully.


[yas] Prepared just-in-time loading of snippets successfully.


[yas] Prepared just-in-time loading of snippets successfully.
[yas] Prepared just-in-time loading of snippets successfully.


[yas] Prepared just-in-time loading of snippets successfully.
[yas] Error in condition evaluation: Symbol’s value as variable is void: yas--barbaz

Mark set

[yas] Prepared just-in-time loading of snippets successfully.


[yas] Prepared just-in-time loading of snippets successfully.


[yas] Prepared just-in-time loading of snippets successfully.


[yas] Prepared just-in-time loading of snippets successfully.


[yas] Prepared just-in-time loading of snippets successfully.


[yas] Prepared just-in-time loading of snippets successfully.


[yas] Prepared just-in-time loading of snippets successfully.


[yas] Prepared just-in-time loading of snippets successfully.


[yas] Prepared just-in-time loading of snippets successfully.


[yas] Prepared just-in-time loading of snippets successfully.


[yas] Snippets loaded successfully.


[yas] Prepared just-in-time loading of snippets successfully.


[yas] Snippet "foo" loaded for .
[yas] Snippet "foo" loaded for .
[yas] Snippet "bar" loaded for .
[yas] Snippet "bar" loaded for .


[yas] Don't know anything about menu entry yas-ignore-item
[yas] Snippets loaded successfully.


[yas] Don't know anything about menu entry yas-ignore-item
[yas] Snippets loaded successfully.
[yas] Don't know anything about menu entry yas-ignore-item
[yas] Snippets loaded successfully.
[yas] Don't know anything about menu entry yas-ignore-item
[yas] Snippets loaded successfully.

[yas] Prepared just-in-time loading of snippets (but no snippets found).

[yas] Prepared just-in-time loading of snippets successfully.


[yas] Don't know anything about menu entry yas-ignore-item
[yas] Snippets loaded successfully.


[yas] Prepared just-in-time loading of snippets successfully.


[yas] Prepared just-in-time loading of snippets successfully.


[yas] Prepared just-in-time loading of snippets successfully.
Undo!


[yas] Prepared just-in-time loading of snippets successfully.
Undo!


[yas] Prepared just-in-time loading of snippets successfully.
Undo!


[yas] Prepared just-in-time loading of snippets successfully.
Undo!


[yas] Prepared just-in-time loading of snippets successfully.
Undo!
Undo!
Redo!


[yas] Snippets loaded successfully.


[yas] Prepared just-in-time loading of snippets successfully.


[yas] Prepared just-in-time loading of snippets successfully.


[yas] Prepared just-in-time loading of snippets successfully.

Ran 84 tests, 84 results were as expected
```

**Comment by zw963** [comment]
@npostavs , Wired, it worked for me now when i retry again when use 9f51cf2

Thanks very much.

**Comment by zw963** [comment]
Hi, sorry for confusing ... after try again, i found,  `yas-also-indent-empty-lines` is not worked for [enh-ruby-mode](https://github.com/zenspider/enhanced-ruby-mode), which is a ruby mode `uses Ripper in ruby 1.9+ to highlight and indent the source code `, not use regexp (like original ruby-mode, i guess),

And, empty line indent feature worked with builtin ruby-mode.

Thanks

**Comment by zw963** [comment]
I will create another issue for this.
