### ISSUE TITLE
multi keys

### ISSUE THREAD

**Issue by avelino** [joaotavora/yasnippet#853]
Today used `tr` to start `import pdb;...`, idea would be to have `tr` and put another key as  `pdb`

example:
```
# -*- mode: snippet -*-
# name: trace
# key: tr, pdb
# group: debug
# --
import pdb; pdb.set_trace()
```

or

```
# -*- mode: snippet -*-
# name: trace
# key: tr
# key: pdb
# group: debug
# --
import pdb; pdb.set_trace()
```

ref: https://github.com/AndreaCrotti/yasnippet-snippets/issues/214

**Comment by npostavs** [comment]
Indeed, this is long-standing request, see #114.
