### ISSUE TITLE
inconvenience in yas-with-comment if comment-end is existing

### ISSUE THREAD

**Issue by Dickby** [joaotavora/yasnippet#854]
Comment snippets like `FIXME` or `TODO` in a  major-mode with a comment-end like c-mode, insert  `/*  FIXME:   */`  but the cursor ends up behind the comment-end.

**Comment by npostavs** [comment]
See https://github.com/AndreaCrotti/yasnippet-snippets/pull/221

**Comment by Dickby** [comment]
Thanks.
