### ISSUE TITLE
Some snippets not expanded

### ISSUE THREAD

**Issue by HeinrichGit** [joaotavora/yasnippet#855]
Emacs 24.3.1

~/.emacs
....
(require 'auto-complete-config)
(ac-config-default)
(add-to-list 'load-path
	     "/home/git/yasnippet-snippets")
(require 'yasnippet)
(yas-global-mode 1)

Emacs will expand **autocomplete**, but **it wont** **some snippets**, e.g. while, typedef, function description, include, ifdef, math, Member description, struct, switch, ternary ... Nothing from yasnippet-snippets\c-mode ...

**Comment by npostavs** [comment]
Does it work if you change `(require 'yasnippet)` to `(require yasnippet-snippets)`?

**Comment by HeinrichGit** [comment]
@npostavs Unfortunately, not 
`File error: Cannot open load file, yasnippet-snippets`

**Comment by npostavs** [comment]
Then I'm confused, what do you have in `"/home/git/yasnippet-snippets"`?

> (add-to-list 'load-path
> "/home/git/yasnippet-snippets")
