### ISSUE TITLE
`yas-with-comment` is not documented in reference

### ISSUE THREAD

**Issue by Wagk** [joaotavora/yasnippet#856]
I noticed that `yas-with-comment` wasn't documented inside the reference https://joaotavora.github.io/yasnippet/snippet-reference.html and was wondering what else wasn't documented

**Comment by npostavs** [comment]
`yas-with-comment` isn't part of yasnippet. See https://github.com/AndreaCrotti/yasnippet-snippets/blob/master/snippets/prog-mode/.yas-setup.el

**Comment by npostavs** [comment]
`yas-with-comment` has been removed from yasnippet-snippets too, see AndreaCrotti/yasnippet-snippets#221
