### ISSUE TITLE
Multi-choice menu for snippet parameters

### ISSUE THREAD

**Issue by biocyberman** [joaotavora/yasnippet#859]
This is a feature request, because I don't think it is possible at the moment.

Suppose I have a snippet like this:

```
# -*- mode: snippet -*-
# name:codeblock
# key:codeblock
# author: someone
# --

#+NAME: ${1:name}
#+BEGIN_SRC ${2:<sh,java,D,C,R>} :exports ${3:<source,result,both>}
${0:code body}
#+END_SRC
```
Notice on the fields $2 and $3, I put the default text in `<>` separated by commas. I would like to be able to `Tab` and select one of those values. For example, when at $2, `Tab` then a autocompletion menu appear to let me choose `java` by typing `j`, or I can use `Ctrl+j/k`  to move up or down.

**Comment by Dickby** [comment]
http://pragmaticemacs.com/emacs/multiple-choices-in-yasnippets/

**Comment by biocyberman** [comment]
@Dickby That works exactly the way I want. Thanks
