### ISSUE TITLE
comment is included when expanding

### ISSUE THREAD

**Issue by casouri** [joaotavora/yasnippet#862]
I added this snippet for org-mode:

```
# -*- mode: snippet -*-
#key : pycode                                     
#name : #+BEGIN_SRC python ... #+END_SRC
#contributor: Yuan Fu                           
# --                                                                        
#+BEGIN_SRC python
$0
#+END_SRC
```

when I type pycode and expand it in org-mode,  instead of ignoring comments, yasnippet shows the whole file. Such as:

<img width="182" alt="screen shot 2017-10-09 at 1 48 11 pm" src="https://user-images.githubusercontent.com/13118647/31351329-aa52a59c-acf8-11e7-8200-3ba8643c01ed.png">
<img width="326" alt="screen shot 2017-10-09 at 1 48 15 pm" src="https://user-images.githubusercontent.com/13118647/31351338-afc5c6f8-acf8-11e7-9649-877c74d31616.png">

**Comment by npostavs** [comment]
This is due to the trailing space after `# --`. Since it is kind of confusing to have trailing have semantic meaning, I will probably change the code to ignore it, see #864.

**Comment by casouri** [comment]
Thank you!
