### ISSUE TITLE
`yas-choose-value` is ignoring empty strings

### ISSUE THREAD

**Issue by redcap1** [joaotavora/yasnippet#865]
I'm not sure if this is a bug or working as intended.
I have the following snippet for c++ code:

`${1:Foo}($1 const & other)${2:$$(yas-choose-value '("" " = default;" " = delete;"))}$0`

During the expansion of the snippet the empty string is ignored, only `" = default;"` and `" = delete;"` are offered for completion. If this is intended, what would be a sensible way to optionally choose a field value from a list?

The value of `yas-prompt-functions`

`(yas-dropdown-prompt yas-completing-prompt yas-maybe-ido-prompt yas-no-prompt)`

Here are the versions that I'm using:

yasnippet-0.12.1
GNU Emacs 25.2.1

I'm also using

helm-2.8.1

Thanks in advance for any help and the great work :-)

**Comment by npostavs** [comment]
Seems to work for me, although since `""` is invisible you might just be overlooking that it is being offered as a completion. If I hit <kbd>tab</kbd> at the the `Choose: ` prompt, I get ` [Complete but not unique]`, indicating that the empty string is a candidate.

**Comment by redcap1** [comment]
Hi there,

my apologies for taking so much time to reply. I debugged this issue and it seems that it is indeed helm that discards the empty string option, so this doesn't seem to be a yasnippet issue :-)

**Comment by npostavs** [comment]
Thanks for checking that.
