### ISSUE TITLE
Personal snippets with latex beamer header are not populated

### ISSUE THREAD

**Issue by cryoguy** [joaotavora/yasnippet#868]
I have a few personal snippets for org-mode.  Those with beamer header does not get populated, whereas others are ok.  This one is working:
```
# -*- mode: snippet -*-
# name: meeting
# key: meeting
# --

\#+TODO: TODO(t) | CANCELED(c) DONE(d) HOLD(h) WAITING(w)
\#+OPTIONS: tasks:todo
```

This one with latex beamer header does not show:
```
# -*- mode: snippet -*-
# name: beamerTitle
# key: BeamerTitle
# --

#+TITLE:     $1
#+AUTHOR:    ${2:Bao Haojun}
#+EMAIL:     ${3:baohaojun@gmail.com}
#+DATE:      ${4:$$(shell-command-to-string "today | tr -d '\n'")}
#+LATEX_CLASS_OPTIONS: [${5:presentation,CJKbookmarks}]
#+DESCRIPTION: 
#+KEYWORDS: 
```

I have to open the snippet file, C-c C-c, add it to org-mode, then it will show.  

any idea how to get this work?

**Comment by npostavs** [comment]
Works for me. Can you reproduce this from [`emacs -Q`][emacs-Q]?

[emacs-Q]: http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html
