### ISSUE TITLE
kill-whole-line on yas-skip-and-clear-or-delete-char

### ISSUE THREAD

**Issue by zhammer** [joaotavora/yasnippet#874]
I wanted to setup an add-on to python mode where if I have:

```
my_function(a=$1,
            b=$2,
            c=$3)
```

I would add advice to ```python-mode```'s ```yas-skip-and-clear-or-delete-char``` such that if a user inputs ```C-d``` on a line that matches the regex ```^\s+\w+=\.*,$```, that line is considered an optional keyward arg (not at the start or end of list) and will be killed.

I realize this may not be intended use for ```yasnippet``` (side effects on non-marked fields in the template during insertion) but I was curious if there is a way to do this. Currently I've played around with a few options but none works as intended.

Example (sans regex check logic):
```elisp
(defadvice yas-skip-and-clear-or-delete-char (before kill-empty-line
						     activate compile)
  (kill-whole-line))
```

**Comment by zhammer** [comment]
Actually will try to build this using nested fields -- seems smarter. Going to look into ways to trim leading whitespace chars from active region highlighting to make it visually clearer. Let me know if you have any suggestions! ([my yasnippets repo](https://github.com/zhammer/hammermacs/blob/master/snippets/python-mode/experimental))
```
# -*- mode: snippet -*-
# name: experimental
# key: exp
# --
my_object.do(a=$1,${2:
             b=${3:},}
             c=$4,
             d=$5)

$0
```

**Comment by npostavs** [comment]
`yas-triggers-in-field` might of interest. But yeah, this is probably a bit beyond yasnippet's current capabilities. You can also make a `#type: command` snippet which means you run arbitrary lisp. In that case you can handle whatever use case you want, though yasnippet doesn't help you much beyond triggering via the abbrev key.
