### ISSUE TITLE
why have no shell-mode in snippets folder?? help to collect  cmd snippets

### ISSUE THREAD

**Issue by sosoeo** [joaotavora/yasnippet#876]
I like yasnippet very much, but it's looks here are no  'shell-mode'  to collect  personal cmd snippets,I can't remember many useful cmd and it's format. why not? Then we can auto complete the cmds.

**Comment by npostavs** [comment]
You can add whatever snippet folder you like under `~/.emacs.d/snippets/`. Yasnippet does not come with any snippets.
