### ISSUE TITLE
why here are no "common-mode" or like this, to hold snippets for all mode or public ?

### ISSUE THREAD

**Issue by sosoeo** [joaotavora/yasnippet#877]
here are always some snippets can be used in many different mode at the same time, why here are such a folder  in snippets/ to hold some snippets for all? I try to create a folder name Fundamental-mode in snippets folder and place some snippets in it,but it's looks like not work. any advise? thanks very much.

**Comment by npostavs** [comment]
The reason putting stuff in `fundamental-mode` doesn't work is because of this:

```elisp
(defmacro define-derived-mode (child parent name &optional docstring &rest body)
  [...]
  (when (eq parent 'fundamental-mode) (setq parent nil))
```

You can work around it by adding `snippets/prog-mode/.yas-parents` and `snippets/text-mode/.yas-parents` with contents `fundamental-mode`.
