### ISSUE TITLE
yasnippet key `=` could not be trigger after a `>` for web-mode

### ISSUE THREAD

**Issue by zw963** [joaotavora/yasnippet#879]
Please see following link. thanks
https://github.com/fxbois/web-mode/issues/953

I think maybe it relative to my config.

```cl
(setq yas-key-syntaxes '(yas-try-key-from-whitespace "w_.()" "w_." "w_"))
```

Infact, even not add this line, it not worked too.

**Comment by npostavs** [comment]
How about this:
```elisp
(setq yas-key-syntaxes '(yas-longest-key-from-whitespace "w_.()" "w_." "w_"))
```

(or use `yas-shortest-key-from-whitespace` if you prefer)

**Comment by zw963** [comment]
@npostavs , worked like a charm!

```cl
(setq yas-key-syntaxes '(yas-longest-key-from-whitespace "w_.()" "w_." "w_"))
```

Thanks.

**Comment by zw963** [comment]
@npostavs , Hi, this issue cause another issue happen. following is a example:

I have a `t` snippets, which suppose expand to `T { ... }`
But, i never exist  `charset`, which is just a word, not yas key.

```rb
charsetI
```
Above example when press `TAB`,  will expand to `charseT { .... }`,
which is not expected, what we expect is:  `t only expand when before t
is a whitespace or very special symbol, e.g. `(` etc.

I try  ``(setq yas-key-syntaxes '(yas-longest-key-from-whitespace "w_.()" "w_." "w_"))``
and ``(setq yas-key-syntaxes '(yas-shortest-key-until-whitespace "w_.()" "w_." "w_"))``,
all not work

**Comment by zw963** [comment]
for convinience, Following is my previous issue:

following cursor after the =,  which is defined as a key  in yasnippet,
will expand to ```<%= %>```

<div>=|</div>

after press TAB, what i expect is expand to: <div><%= %></div>, but it not work.

I have to add a space before = like following:

<div> =|</div>

It worked now.

**Comment by npostavs** [comment]
Hmm, so you want whitespace delimited keys, but for word characters only; symbol character keys should not need whitespace delimiting. Have I understood correctly?

```elisp
(defun yas-longest-symbolkey (start-point)
  "As `yas-key-syntaxes' element, look for longest key made of symbol characters."
  (if (= (point) start-point)
      (skip-syntax-backward "_.()")
    (forward-char))
  (unless (<= start-point (1+ (point)))
    'again))

(setq yas-key-syntaxes '(yas-longest-symbolkey yas-try-key-from-whitespace "w_.()" "w_." "w_"))
```

**Comment by zw963** [comment]
> Hmm, so you want whitespace delimited keys, but for word characters only; symbol character keys should not need whitespace delimiting. Have I understood correctly?

I never use whitespace delimited key,  even for word. I think.
What i care about is, the expand order if some key is matched partly.
so, `"w_.()" "w_." "w_"` is worked basiclly like what i expect.
or more accurately: ``(setq yas-key-syntaxes '("w_.()" "w_." "w_" "w"))`` is what i want.

But,  only in special mode and some special char, in some special case, it not worked.

As example from previous reply.  the `equal sign` is worked when equal sign not follow
by others char, e.g. `<div>....<div> =`, this `equal sign` will expand correct.
(there is a whitespace between `>` and `=`), But, when use in `<div>...<div>=`, this `equal sign` 
will not expand.

And after a try, i found `some content=`, this `equal sign` work as expected too.
maybe this is not a yasnippets issue? `>=` is recognize as a `great than sign`,
so `=` is not expand?

**Comment by zw963** [comment]
those example is tried in web-mode https://github.com/fxbois/web-mode

**Comment by npostavs** [comment]
> I never use whitespace delimited key, even for word. I think.

If you don't want the `t` in `charset` to expand, I guess that you want the `t` to expand only if it's separated by whitespace, e.g., `charse t`, or if not by whitespace then some other kind characters, e.g., `charse,t`. Whereas, if the key is `=` you always want to expand: e.g., `charse=` should expand the `=` snippet. Right?

**Comment by zw963** [comment]
> If you don't want the t in charset to expand, I guess that you want the t to expand only if it's separated by whitespace, e.g., charse t

Yes, this is what i means, `t` as a part of a word, i just want to expand when `t` is space delimited.

> or if not by whitespace then some other kind characters, e.g., charse,t

Yes, i think in this case, t should be expand,  because `,` not a valid
word char in most programming language, right?

**Comment by zw963** [comment]
>  Whereas, if the key is = you always want to expand: e.g., charse= should expand the = snippet. Right?

Yes! i think this maybe not a bad idea, because `=` self look like separate with the word `charse`, do you think? but, i think if i have a key like: `charse=`, i will prefer always trigger most longest first,
That is to say, will always expand `charse=` if it exists, only not exist, it will trigger `=`. don't consider
`charse`.

**Comment by npostavs** [comment]
So does my suggestion in https://github.com/joaotavora/yasnippet/issues/879#issuecomment-362060683 not do what you want?

**Comment by zw963** [comment]
So does my suggestion in #879 (comment) not do what you want?

@npostavs , sorry for confuse, your's answer worked!

i tried with `(setq yas-key-syntaxes '(yas-longest-nonwordkey "w_.()" "w_." "w_"))`,  missing `yas-try-key-from-whitespace`, so it not work. : (

**Comment by zw963** [comment]
Thank you very much!

**Comment by zw963** [comment]
@npostavs ,  i remember we discuss in some place for change `yas-key-syntaxes` order
and add `yas-longest-nonwordkey` into syntax in 0.13.0 right?

after i update to 0.13.0, i am not see this feature is builtin ... :smile:

**Comment by zw963** [comment]
My current working version is:  0.12.1

**Comment by npostavs** [comment]
>  i remember we discuss in some place for change `yas-key-syntaxes` order

Yes, in #805.

> and add `yas-longest-nonwordkey` into syntax in 0.13.0 right?

Hmm, I hadn't really planned on adding it, not sure how useful it is.
