### ISSUE TITLE
yas-expand-snippet sets empty yas-selected-text to snippet key on expansion

### ISSUE THREAD

**Issue by hlissner** [joaotavora/yasnippet#883]
### Steps to reproduce

+ Type `if`
+ Press <kbd>Tab</kbd>
+ `if` expands into `(if |t if)`, where `|` is the cursor. Notice the extra `if`.

+ Other examples:
  + `progn` expands to `(progn progn|)`
  + `defun` expands to `(defun |name () defun)`

### Observations

+ A git-bisect shows this issue was introduced in https://github.com/joaotavora/yasnippet/commit/e200a3b9b18a2d7bbd4773bd4ef001dc6f69f0e8.
+ Tested on Emacs 25.3, 26.1 and 27.0.50, on Arch Linux 4.14.9-1
+ Issue occurs when any snippet that uses `yas-selected-text` is expanded **without** an active selection. yas-expand-snippet works as expected when a selection _is_ active.

### Test templates

```emacs-lisp
# name: if
# --
(if ${1:t} `yas-selected-text`$0)
```

```emacs-lisp
# name: progn
# --
(progn `yas-selected-text`$0)
```

```emacs-lisp
# name: defun
# --
(defun ${1:name} ($2) `yas-selected-text`$0)
```

### Test config

`emacs -Q -l setup.el`

```emacs-lisp
;; setup.el
(push "~/temp/yasnippet" load-path)
(require 'yasnippet)
(setq yas-snippet-dirs '("~/work/conf/emacs-snippets"))
(yas-global-mode +1)
```

**Comment by npostavs** [comment]
Thank you for this thorough report! Should be fixed by #884.
