### ISSUE TITLE
after recent update I am unable to use any snippets

### ISSUE THREAD

**Issue by yilkalargaw** [joaotavora/yasnippet#885]
I am using emacs 25.3 on a linux system and a recent update left me unable to use any of my templates or the default ones. Can't figure out where to start to debug the issue

 Details:
   Status: Installed in ‘yasnippet-20180101.1211/’ (unsigned).
   Version: 20180101.1211
   Summary: Yet another snippet extension for Emacs.
   Requires: cl-lib-0.5
   Required by: elpy-20171228.1239, company-auctex-20161025.24
   Homepage: http://github.com/joaotavora/yasnippet
   Keywords: convenience emulation 
   Other versions: 0.12.2 (gnu).

**Comment by npostavs** [comment]
Where have you installed the ones you call "my templates"? Is that directory listed in `yas-snippet-dirs`?

The "default" ones must now be installed as a separate package, see [README](https://github.com/joaotavora/yasnippet#where-are-the-snippets):

> # Where are the snippets?
>
> Yasnippet no longer bundles snippets directly, but it's very easy to
> get some!
> 
> 1. [yasnippet-snippets] - a snippet collection package maintained by
>     [AndreaCrotti](https://github.com/AndreaCrotti).
> 
>     It can be installed with `M-x install-package RET yasnippet-snippets` if you have added MELPA to your package sources.
>

**Comment by yilkalargaw** [comment]
thanks i solved it. The separation of the packages was new to me.

**Comment by yilkalargaw** [comment]
thanks i solved it. The separation of the packages was new to me.

**Comment by npostavs** [comment]
> ugly of you starting with "Where have you installed the ones you call "my templates"? "

What do you mean?
