### ISSUE TITLE
The `snippets` folder not removed

### ISSUE THREAD

**Issue by seagle0128** [joaotavora/yasnippet#886]
Hi,

I noticed this commit (https://github.com/joaotavora/yasnippet/commit/b1ca2197062340d4c9e78442ea38957a96f968d4) has removed the `snippets` folder from the `yas-snippets-installed-dirs`, but it still exists in the package from melpa. Will it be removed?

**Comment by npostavs** [comment]
Hmm, not sure why that's happening. I've opened melpa/melpa#5225 for this.

**Comment by seagle0128** [comment]
Thanks a lot!

**Comment by npostavs** [comment]
yasnippet-20180111.1533 no longer has a `snippets` directory.
