### ISSUE TITLE
Cannot tab out of field (again)

### ISSUE THREAD

**Issue by mankoff** [joaotavora/yasnippet#889]
I think this is closely related to #832. I've reviewed the solution there but cannot get it to work for what is, I think, a simpler example. I'd like to choose a directory within a yasnippet. I can, but I can't leave the field after I've chosen it. An MWE:

```
# -*- mode: snippet; require-final-newline: nil -*-
# name: rsync
# key: rsync_
# --
#+BEGIN_SRC sh :var SRC="${1:$$(read-directory-name \"SRC:\")}"
$0ls \$\{SRC\}
#+END_SRC
#+RESULTS:
```

**Comment by npostavs** [comment]
I think it's just a matter of checking `yas-modified-p` like `yas-choose-value` does (otherwise you get `read-directory-name` re-evaluated on every command), so something like:

```
# -*- mode: snippet; require-final-newline: nil -*-
# name: rsync
# key: rsync_
# --
#+BEGIN_SRC sh :var SRC="${1:$$(unless yas-modified-p (read-directory-name \"SRC:\"))}"
$0ls \$\{SRC\}
#+END_SRC
#+RESULTS:
```

See also http://joaotavora.github.io/yasnippet/snippet-development.html#sec-3-8

**Comment by mankoff** [comment]
Yes that fixes it. Thank you!
