### ISSUE TITLE
slows down emacs startup a lot

### ISSUE THREAD

**Issue by adrianstaniec** [joaotavora/yasnippet#904]
It adds 1s to emacs startup, see esup results:

```
Total User Startup Time: 1.617sec     Total Number of GC Pauses: 0     Total GC Time: 0.000sec

config.el:396  1.070sec   66%
(use-package yasnippet)
```

Is that normal?

**Comment by npostavs** [comment]
Do you have yasnippet-snippets installed? Same issue as AndreaCrotti/yasnippet-snippets#249 perhaps? Does the patch in AndreaCrotti/yasnippet-snippets#252 help?

**Comment by adrianstaniec** [comment]
Thanks for the response!

1. Yes, of course, I have yasnippet-snippets installed.

2. Yes, I think it's the same issue as AndreaCrotti/yasnippet-snippets#249, at least his solution works.
But I think I found a cleaner way to fix it:
```
(use-package yasnippet
  :hook (prog-mode . yas-minor-mode))

(use-package yasnippet-snippets
  :after (yasnippet))
```

3.I didn't try to patch (not sustainabe in my config).
