### ISSUE TITLE
Placeholders are not expanded when code is incuded in code snippets

### ISSUE THREAD

**Issue by Nelsonlittle** [joaotavora/yasnippet#905]
When I use the following snippet everything works as expected
```
# -*- mode: snippet -*-
# name: test
# key: test1
# --

#+HEADER: :var path="./images/fig_$1.png"
#+BEGIN_SRC python 
$0
#+END_SRC
```
whereas when i insert one line of python code
```
# -*- mode: snippet -*-
# name: test
# key: test1
# --

#+HEADER: :var path="./images/fig_$1.png"
#+BEGIN_SRC python 
import numpy as np
$0
#+END_SRC
```
the cursor does not jump to the first placeholder but stays at the beginning of the first line.

**Comment by npostavs** [comment]
This is in org-mode, I presume? What Emacs and org-mode versions are you running?
What are your settings for `org-src-tab-acts-natively` and `org-src-fontify-natively`?

**Comment by Nelsonlittle** [comment]
I am sorry... somehow now it does work.. by the way both variables are `t` for me
