### ISSUE TITLE
Error for snippets for org-mode code blocks with when yas-choose-value is present

### ISSUE THREAD

**Issue by AttilaVM** [joaotavora/yasnippet#907]
I have the following snippet for org-mode

```
# -*- mode: snippet -*-
# name: code
# key: c
# expand-env: ((yas-indent-line nil))
# --
#+begin_${1:$(yas-choose-value '("sh" "python"))} ${2:options}
$0
#+end_$1
```

When I  expand it, the text will be indented like this:

```
	#+begin_sh options

	#+end_
```

Which is strange, because [yas-indent-line](http://joaotavora.github.io/yasnippet/snippet-reference.html#yas-indent-line) is set to `nil` so `org-indent-line` should not be called.

**Comment by npostavs** [comment]
What Yasnippet, Emacs and org-mode versions are you running?
What are your settings for `org-src-tab-acts-natively` and `org-src-fontify-natively`?

**Comment by AttilaVM** [comment]
emacs-version is 25.3.1
org-version is  8.2.10
yas--version is 0.12.2
org-src-tab-acts-natively is nil
org-src-fontify-natively is t


Interesting: I made a mistake in the snippet text, after I fixed it:

```
# -*- mode: snippet -*-
# name: code
# key: c
# expand-env: ((yas-indent-line nil))
# --
#+begin_src ${1:$$(yas-choose-value '("sh" "python"))} ${2:options}
$0
#+end_src
```

The auto indentation is stopped, so it works now as expected. It is strange, because I only changed the textual parts of the snippet body.

**Comment by npostavs** [comment]
I can't reproduce the problem even with your mistaken snippet, using same versions and settings: Emacs 25.3, builtin org (8.2.10), latest yasnippet (`M-x yas-about`: version 0.12.2-34-g3d7cafc), `(list org-src-tab-acts-natively org-src-fontify-natively) => (nil t)`.
