### ISSUE TITLE
how can I retain <tab> when inserting snippets

### ISSUE THREAD

**Issue by amosbird** [joaotavora/yasnippet#909]
I have a `makefile` snippet that contains `<tab>` characters. Inserting this snippet doesn't retain any `<tab>`s thus breaks the makefile.

**Comment by npostavs** [comment]
Set `yas-indent-line` to `nil` perhaps?

**Comment by amosbird** [comment]
um, how can I limit that setq local to current snippet only?

**Comment by npostavs** [comment]
Add a `# expand-env: ((yas-indent-line nil))` header to it.

**Comment by amosbird** [comment]
ah, thanks!
