### ISSUE TITLE
yasnippet is an obsolete package?

### ISSUE THREAD

**Issue by parhamdoustdar** [joaotavora/yasnippet#910]
Hi,

When I look at the yasnippet information in `package-list` by focusing on it and pressing `?`, I see this line at the top of the package description:

```
yasnippet is an obsolete package.
```

Is this true? If so, how can I get the package that is not obsolete?

I'm using GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-09-12, and the version of yasnippet I have installed is 20180218.459.

**Comment by npostavs** [comment]
I think it means that yasnippet-20180218.459 is obsolete and there should be a newer version available to install from `package-list`.

**Comment by parhamdoustdar** [comment]
Oh, you're right. Sorry for wasting your time.
