### ISSUE TITLE
wrong indentation when setting is fixed

### ISSUE THREAD

**Issue by it6** [joaotavora/yasnippet#912]
I have this setting globally in init```  (setq yas-indent-line 'fixed)``` 

but I see the following behavior, indentation is off in the new release.

![indent-yasnippet](https://user-images.githubusercontent.com/5510191/37135926-6d802ee2-226d-11e8-9329-ebc3eee4bee9.gif)

**Comment by npostavs** [comment]
Oh right, I noticed that bug for `auto` indentation, but it usually doesn't matter in that case because the auto indentation is usually a nop for the first line anyway. Now that I've started using the same machinery for the `fixed` case, it shows up more obviously. Should be fixed in #913.

**Comment by it6** [comment]
can you please merge  #913
