### ISSUE TITLE
Sharing `yas-expand` with `emmet-expand-line`

### ISSUE THREAD

**Issue by Wagk** [joaotavora/yasnippet#914]
Hello,

I would like to be able to configure `yas-expand` such that if it matches no snippet, it falls back to `emmet-expand-line` (or any other command really).

Is there a simple way to do this?

**Comment by npostavs** [comment]
It should already do this, if there is no snippet abbrev key before point, `TAB` will do whatever else you've bound it to.

**Comment by Wagk** [comment]
Yes it does look that way.

I was keying in a bad snippet trigger. Whoops
