### ISSUE TITLE
snippets with elisp code modifying buffer breaks undo

### ISSUE THREAD

**Issue by amosbird** [joaotavora/yasnippet#915]
Hi, I have this snippet that might add a header file if not exist.
```
`(+amos/add-include "abmb.h")`cout << ab::mb<`(yas/choose-value '("std::chrono::milliseconds" "std::chrono::seconds" "std::chrono::microseconds" "std::chrono::nanoseconds"))`, ${1:1}, ${2:1}>(
    [&]() {
        $0
    }
) << endl;
```

It breaks undo (line is offset by one). Is there a way to mitigate that? thanks!

**Comment by joaotavora** [comment]
> Is there a way to mitigate that?

Obviously, I don't know what `(+amos/add-include "abmb.h")` does, but if `+amos/add-include` is purely functional (i.e. returns a string and has no side effects), this shouldn't happen.

**Comment by joaotavora** [comment]
> So is it possible to fix undo in this senario?

I think so, if you make `+amos/add-include` return those newlines in the return value instead of inserting them directly with `insert` (or functions that call `insert`).

**Comment by amosbird** [comment]
Um, can I let yasnippet run `(+amos/add-include "some-header-file")` after given snippet expansion?

**Comment by npostavs** [comment]
> I think so, if you make `+amos/add-include` return those newlines in the return value instead of inserting them directly with `insert` (or functions that call `insert`).

I assume the new lines are meant to go at the top of the file though.

> Um, can I let yasnippet run `(+amos/add-include "some-header-file")` after given snippet expansion?

I think you can sneak it in with `expand-env`:
`# expand-env: ((_ (+amos/add-include "some-header-file")))`

(there is also `yas-before-expand-snippet-hook`, but you can't make that snippet-specific)

**Comment by amosbird** [comment]
I tried `# expand-env: ((_ (+amos/add-include "some-header-file")))`, however it messed up the expanding position of the snippet.

**Comment by npostavs** [comment]
Actually, it occurs to me, that if you do it that way, you probably end up with the include statement inserted multiple times, so you would want
`# expand-env: ((included nil) (_ (unless included (save-excursion (+amos/add-include "some-header-file") (setq included t)))))`

**Comment by amosbird** [comment]
it still doesn't work. `+amos/add-include` handles duplication. It won't insert headers if exists.

**Comment by npostavs** [comment]
> it still doesn't work.

I guess that's it then. Can't be done.

**Comment by joaotavora** [comment]
> I assume the new lines are meant to go at the top of the file though.

Ah that makes sense; and it makes my suggestion to use the return value useless.

> I guess that's it then. Can't be done.

A curious use case though. @npostavs shoudn't a snippet-local pre-hook solve this here? I mean something that runs outside the `buffer-undo-list` bubble that is setup somewhere in `yasnippet.el`.

**Comment by npostavs** [comment]
> shoudn't a snippet-local pre-hook solve this here?

Yeah, there isn't such a thing at the moment though. Actually, I guess a command snippet should work too, something like:

```
# key: mb
# name: mb
# type: command
# --
(+amos/add-include "abmb.h")
(yas-expand-snippet (concat "cout << ab::mb<" (yas/choose-value '("std::chrono::milliseconds" "std::chrono::seconds" "std::chrono::microseconds" "std::chrono::nanoseconds"))
                            ", ${1:1}, ${2:1}>(
    [&]() {
        $0
    }
) << endl;"))
```

**Comment by amosbird** [comment]
Wow it works. Thanks!

**Comment by joaotavora** [comment]
cool!
