### ISSUE TITLE
how yas-expand-snippet works

### ISSUE THREAD

**Issue by vinursme** [joaotavora/yasnippet#925]
Hi,
  I create a file test.el, and add the content in  it:
`hello
(yas-expand-snippet (buffer-string) (point-min) (point-max))
`
then C-x C-e, but the file's content become:
![image](https://user-images.githubusercontent.com/37489300/38164684-9b607e36-353a-11e8-9cd7-13dacdafc3eb.png)

does yas-expand-snippet replace all the buffer content? it seem that it insert the output before the content

**Comment by npostavs** [comment]
I can't reproduce this. The buffer content remains unchanged. What versions of Emacs and yasnippet are you using? Can you reproduce this from `emacs -Q`?

**Comment by vinursme** [comment]
@npostavs I try with any configuration, and the action is right, this maybe caused by spacemacs' develope branch, I checkout to master branch, then it works corecctly
