### ISSUE TITLE
Ability to specify within a file the sets of snippets to use with that file

### ISSUE THREAD

**Issue by edgimar** [joaotavora/yasnippet#936]
I realize that yasnippet organizes snippets based on the emacs mode in use, but this still leaves something to be desired in terms of customization.  For example, I use org-mode for a large variety of purposes -- sometimes I might be working on org-mode files that track finances, and some files might be for keeping notes on books.  In a books file, I don't want or need finance-related snippets, and in the finance file, I don't need book-review template snippets.

What I propose is to make it possible for snippets to have a specific "project-types" property associated with them, which can contain identifiers that associate the snippet w/ one or more types of projects.  Within a given file, there should be a means of specifying within that file (e.g. as a file-local variable) what project-types it represents (also one or more).  Upon loading the file, yasnippet would check for the existence of this file-local variable, and if it exists, all snippets associated with the indicated project-types would be loaded.

One might argue that another way this could be implemented is by having a local `.yasnippets` folder alongside the file(s) you want to use the snippets with (see, for example, [this solution](https://www.reddit.com/r/emacs/comments/57i41t/projectlocal_snippets/daw67dd/)).  While I'm not opposed to the idea of allowing local snippets to be defined in local folders, unless some kind of "project-type" attribute matching system is in place, this would suffer the same weakness mentioned above:  if I have both an accounting and a book-review org-file in the same folder, do both files need to use all the snippets defined in the `.yasnippets` local subfolder?

**Comment by npostavs** [comment]
I think existing features should already make this possible: the [condition system](http://joaotavora.github.io/yasnippet/snippet-expansion.html#sec-2-2) is probably the most relevant. `yas-activate-extra-mode` could also be used for groupings which are not really modes.

**Comment by edgimar** [comment]
@npostavs, fair enough, conditions could be used, but the code required in the condition directive would be bordering on too complex (to have to copy/paste/type for all snippet definitions), and would make (human) parsing of any additional conditions that are anded with the "project-type selection" condition a pain.

In other words, yes, I (and other elisp hackers) could implement a project-type system based on a complex condition expression, but many users might be unable or unwilling to use this feature due to its complexity.

Maybe having `yas-file-in-project-types-p` function defined (that takes a list of project-type identifiers) within `yasnippet.el` could be a good solution?

**Comment by npostavs** [comment]
Hmm, I was going to say that having `# condition: foo-project` in the snippet should work out, but looking at `yas-buffer-local-condition` it looks like there isn't a way of choosing those snippets without disabling snippets without a `# condition` header.

> Maybe having yas-file-in-project-types-p function defined (that takes a list of project-type identifiers) within yasnippet.el could be a good solution?

I'm not sure how yasnippet could know how to identify a project though. Wouldn't that have to depend on what your project system is?

**Comment by edgimar** [comment]
The hypothetical `yas-file-in-project-types-p (types-list)` function would need to assume that a file can optionally have a file-local `yas-project-types` variable defined which is a list of project types.  If the variable isn't defined, then `yas-file-in-project-types-p` returns `t` ; if `yas-project-types` is defined, then it is parsed and iff any of the types in _types-list_ are in `yas-project-types`, then it returns `t`.

**Comment by npostavs** [comment]
So just
```elisp
(defun yas-file-in-project-types-p (types)
  (cl-intersection types (bound-and-true-p yas-project-types)))
```

**Comment by edgimar** [comment]
@joaotavora Though that's possible, it requires that snippets be divided into mutually exclusive project-types.  Ideally you could have a single snippet that belongs to multiple project-types.

**Comment by joaotavora** [comment]
@edgimar ar, but you can, I think, see http://joaotavora.github.io/yasnippet/snippet-organization.html#sec-3


> It's very useful to have certain modes share snippets between themselves. To do this, choose a mode subdirectory and place a .yas-parents containing a whitespace-separated list of other mode names. When you reload those modes become parents of the original mode.

**Comment by edgimar** [comment]
Yes, `.yas-parents` allows modes (i.e. a set of snippets) to be able to be included in other modes.  But the way it works isn't as flexible as might be useful:

Consider a 3-set Venn-diagram where you have sets A, B, and C.  Let's assume that each set represents a specific project-type, and elements of each set are snippets.  Some snippets are common to A and B (i.e. in the set A∩B), some are in B∩C, some in A∩C, and some in A∩B∩C.

The `.yas-parents` scheme is only able to represent situations where, for example, A⊆B.  But if A and B both have elements unique to them not shared by the other, the only way to use `.yas-parents` is by the 'workaround' of creating another mutually exclusive set of snippets, say X, moving the A∩B elements to X, and then adding X to the `.yas-parents` files in A and B.  This isn't too much work if you are working with only two sets, but it quickly becomes unsustainable/unscalable when working with 3 or more sets.  With 3 sets, you need to create potentially 4 auxiliary sets, and move snippets accordingly into these auxiliary 'mode' folders.  Every time I realize I want to add a new set (i.e. project-type), then I need to refactor all my other sets again, moving around snippets and creating new auxiliary sets.

Does that all make sense?

**Comment by edgimar** [comment]
@npostavs Your function looks like a good start, but I can't get it to work - maybe it isn't able to see the file-local list?

My snippet contains "# condition: (yas-file-in-project-types-p '(test))"
and my file contains "# -*- yas-project-types: '(foo test bar); -*-" on the first line.

When I try executing the snippet, it is not expanded.

**Comment by npostavs** [comment]
> and my file contains `# -*- yas-project-types: '(foo test bar); -*-` on the first line.

Ah, you shouldn't have a quote there, i.e., just

    # -*- yas-project-types: (foo test bar); -*-

**Comment by joaotavora** [comment]
> Does that all make sense?

Maybe :) I confess I got lost through the middle. Sorry for the low effort. I don't use yasnippet much for 
these kinds of things, but I remember I once did and I designed this (almost 10 years ago) with use cases like yours in mind. Anyway, use @npostavs's solution if you find it more suitable.

**Comment by edgimar** [comment]
The solution from @npostavs is fine, however it needs one other puzzle-piece to work:  a way to load "global" snippets.  I know these have been brought up in the past, but I don't think there's been a "standard" solution provided in yasnippet for this (apart from some hacky workarounds).  Could there be a generic `yas-load-snippets-in-dir` function that forces the loading of all snippets in the specified directory and makes these active in any mode?  Or alternatively, modify yasnippet.el to hard-code a `GLOBAL` snippets subfolder which contains scripts that should be loaded in all modes.

**Comment by npostavs** [comment]
I think the most obvious solution for global snippets is defining them for `fundamental-mode`. Currently this requires adding `.yas-parents` in a few places because `prog-mode`, `text-mode`, etc don't explicitly declare `fundamental-mode` as a parent mode. I think it would make sense for yasnippet to pretend this parent link exists, so then it would work without any need for `.yas-parents` additions.

**Comment by edgimar** [comment]
Or to prevent any confusion to those who understand the nuances of how `fundamental-mode` relates to `text-mode`, etc., it may be better to have a 'pseudo-mode' called `global` which is more or less an alias to `fundamental-mode` (e.g. has an implicit parent link to `fundamental-mode`), and the other implicit parent-links for `text-mode`, etc. could specify `global` as the parent instead of `fundamental-mode`.

These are all implementation details, though -- the important thing would be to have a clear and unique 'pseudo-mode' whose behavior (i.e. scope of snippet-applicability) is clearly specified/understood.

**Comment by npostavs** [comment]
> I'm going with `fundamental-mode` (see #949).

That's done, I think that concludes the issue so I'm closing.
