### ISSUE TITLE
Feature Request:  Automatically advance to next field after `yas-choose-value`.

### ISSUE THREAD

**Issue by lawlist** [joaotavora/yasnippet#937]
I launched a question on https://emacs.stackexchange.com/questions/41411/yasnippet-how-to-automatically-advance-to-next-field-after-yas-choose-value and it appears that there is no simple solution.  Here is how I ended up implementing the feature, but there may be a better way to accomplish the goal:

* I set up an extra slot in the defstruct for `yas-snippet`; i.e., the field is called `expand-env`

* I set up a global variable `yas-auto-exit` with a default value of `nil`.

* In the header of a snippet, I put `# expand-env: ((yas-auto-exit t))`

* When the snippet is being initially created in the buffer, I put the `expand-env` from the snippet headers into the above-mentioned slot.

* `yas--move-to-field` gets a new section added to the tail end which checks to see if `(yas-auto-exit t)` is a member of `expand-env` that is stored in the above-mentioned slot, and also whether the next field is `0`.  If that is satisfied, then call `yas-next-field`.

**Comment by npostavs** [comment]
> Here is how I ended up implementing the feature, but there may be a better way to accomplish the goal:

I think the extra snippet slot should not be needed, as the bindings from `expand-env` will already be in effect. It might be that we want a per-field setting for this though.

----

By the way, I tried just now adding a call to `yas-next-field` inside the snippet field transform, but it doesn't work because the move happens too early.

```
<div align="${2:$$(let ((val (yas-choose-value '("right" "center" "left"))))
                    (when val
                      (yas-next-field)
                      val))}">
  $0
</div>
```

**Comment by lawlist** [comment]
Thank you for letting me know about the expected behavior of the `expand-env` being active throughout the duration of the snippet execution.  This is what I get for using a very old version of yasnippet, which did not yet have the slot for `expand-env` in the struct setup.  After reviewing the current version of yasnippet, I see that you added it too (as the first slot) -- probably years ago.  I was also missing `yas--letenv` and all of the applications throughout the various functions.  The environmental variables now work as expected.

I agree that this prospective new feature would be much more useful as a per-field setting than only the second to the last field.  Based on my experimentation yesterday, `yas--move-to-field` is a possible location to apply the magic.  I'll continue to brainstorm in the coming days/weeks regarding how this feature might be enabled on a per field basis ...

**Comment by joaotavora** [comment]
> doesn't work because the move happens too early.

A long time ago I added a (horrible) `yas-moving-away-p` var to circumvent this use case, I think.

**Comment by npostavs** [comment]
> A long time ago I added a (horrible) `yas-moving-away-p` var to circumvent this use case, I think.

I think it would only help if yasnippet paid attention when the snippet code changes that variable, but currently it's effectively read-only from the snippet writer's point of view.

**Comment by lawlist** [comment]
Here is an idea which works (at least in so far as a few preliminary tests are concerned) for each field *if* the there is a `$` after the `}`; e.g., 

    <div align="${2:$$(yas-choose-value '("right" "center" "left"))}$">
      $0
    </div>

It could be changed a different symbol than a dollar sign, e.g., a unicode section symbol `§` is less common.

___

    diff --git a/yasnippet.el b/yasnippet.el
    index d478073..86c3a9b 100644
    --- a/yasnippet.el
    +++ b/yasnippet.el
    @@ -556,7 +556,7 @@ override bindings from other packages (e.g., `company-mode')."
       "List of characters which *might* need to be escaped.")
     
     (defconst yas--field-regexp
    -  "${\\([0-9]+:\\)?\\([^}]*\\)}"
    +  "${\\([0-9]+:\\)?\\([^}]*\\)}\\(\\$\\)?"
       "A regexp to *almost* recognize a field.")
     
     (defconst yas--multi-dollar-lisp-expression-regexp
    @@ -3087,7 +3087,7 @@ other fields."
       previous-active-field
       force-exit)
     
    -(cl-defstruct (yas--field (:constructor yas--make-field (number start end parent-field)))
    +(cl-defstruct (yas--field (:constructor yas--make-field (number start end parent-field &optional advance)))
       "A field.
     
     NUMBER is the field number.
    @@ -3104,7 +3104,8 @@ NEXT is another `yas--field' or `yas--mirror' or `yas--exit'.
       (mirrors '())
       (transform nil)
       (modified-p nil)
    -  next)
    +  next
    +  advance)
     
     
     (cl-defstruct (yas--mirror (:constructor yas--make-mirror (start end transform)))
    @@ -3351,7 +3352,9 @@ Also create some protection overlays"
           (unless (yas--field-modified-p field)
             (if (yas--field-update-display field)
                 (yas--update-mirrors snippet)
    -          (setf (yas--field-modified-p field) nil))))))
    +          (setf (yas--field-modified-p field) nil)))
    +      (when (yas--field-advance field)
    +        (yas-next-field)))))
     
     (defun yas-prev-field ()
       "Navigate to prev field.  If there's none, exit the snippet."
    @@ -4552,6 +4555,7 @@ When multiple expressions are found, only the last one counts."
           (let* ((real-match-end-0 (yas--scan-sexps (1+ (match-beginning 0)) 1))
                  (number (and (match-string-no-properties 1)
                               (string-to-number (match-string-no-properties 1))))
    +             (advance (equal (match-string 3) "$"))
                  (brand-new-field (and real-match-end-0
                                        ;; break if on "$(" immediately
                                        ;; after the ":", this will be
    @@ -4564,10 +4568,11 @@ When multiple expressions are found, only the last one counts."
                                        (yas--make-field number
                                                        (yas--make-marker (match-beginning 2))
                                                        (yas--make-marker (1- real-match-end-0))
    -                                                   parent-field))))
    +                                                   parent-field
    +                                                   advance))))
             (when brand-new-field
               (goto-char real-match-end-0)
    -          (push (cons (1- real-match-end-0) real-match-end-0)
    +          (push (cons (1- real-match-end-0) (if advance (1+ real-match-end-0) real-match-end-0))
                     yas--dollar-regions)
               (push (cons (match-beginning 0) (match-beginning 2))
                     yas--dollar-regions)

**Comment by npostavs** [comment]
> It could be changed a different symbol than a dollar sign, e.g., a unicode section symbol § is less common.

Hmm, that's already quite few dollar signs, it's looking kind of hard to read. Although typing unicode symbols is a bit difficult. Maybe a modifier after the field number? E.g.,

    <div align="${2!:...}">

Alternatively, we could add some way of doing it via lisp which would probably be clearer, although it can be a bit verbose.

>     + (advance (equal (match-string 3) "$"))

If you use `(advance (match-beginning 3))` then you don't need to have two places which rely on the choice of syntax.

**Comment by lawlist** [comment]
I like the idea of using `!` and I also like the idea of the modifier location.  That is much better than placing something to the immediate right of the `}`.  I'll work on an updated draft.

Thank you for helping me to simply matching the appropriate field -- greatly appreciated!  :)

**Comment by lawlist** [comment]
Here is the next draft that uses `!` as a modifier following the field number.  The regexp could be changed to create an additional group for the `!`, but it may not be necessary since the number still seems to be extracted okay so long as `!` follows the number in the snippet.

    diff --git a/yasnippet.el b/yasnippet.el
    index d478073..7007604 100644
    --- a/yasnippet.el
    +++ b/yasnippet.el
    @@ -556,7 +556,7 @@ override bindings from other packages (e.g., `company-mode')."
       "List of characters which *might* need to be escaped.")
     
     (defconst yas--field-regexp
    -  "${\\([0-9]+:\\)?\\([^}]*\\)}"
    +  "${\\([0-9!]+:\\)?\\([^}]*\\)}"
       "A regexp to *almost* recognize a field.")
     
     (defconst yas--multi-dollar-lisp-expression-regexp
    @@ -3087,7 +3087,7 @@ other fields."
       previous-active-field
       force-exit)
     
    -(cl-defstruct (yas--field (:constructor yas--make-field (number start end parent-field)))
    +(cl-defstruct (yas--field (:constructor yas--make-field (number start end parent-field &optional advance)))
       "A field.
     
     NUMBER is the field number.
    @@ -3104,7 +3104,8 @@ NEXT is another `yas--field' or `yas--mirror' or `yas--exit'.
       (mirrors '())
       (transform nil)
       (modified-p nil)
    -  next)
    +  next
    +  advance)
     
     
     (cl-defstruct (yas--mirror (:constructor yas--make-mirror (start end transform)))
    @@ -3351,7 +3352,9 @@ Also create some protection overlays"
           (unless (yas--field-modified-p field)
             (if (yas--field-update-display field)
                 (yas--update-mirrors snippet)
    -          (setf (yas--field-modified-p field) nil))))))
    +          (setf (yas--field-modified-p field) nil)))
    +      (when (yas--field-advance field)
    +        (yas-next-field)))))
     
     (defun yas-prev-field ()
       "Navigate to prev field.  If there's none, exit the snippet."
    @@ -4552,6 +4555,7 @@ When multiple expressions are found, only the last one counts."
           (let* ((real-match-end-0 (yas--scan-sexps (1+ (match-beginning 0)) 1))
                  (number (and (match-string-no-properties 1)
                               (string-to-number (match-string-no-properties 1))))
    +             (advance (save-match-data (string-match "!" (match-string-no-properties 1))))
                  (brand-new-field (and real-match-end-0
                                        ;; break if on "$(" immediately
                                        ;; after the ":", this will be
    @@ -4564,7 +4568,8 @@ When multiple expressions are found, only the last one counts."
                                        (yas--make-field number
                                                        (yas--make-marker (match-beginning 2))
                                                        (yas--make-marker (1- real-match-end-0))
    -                                                   parent-field))))
    +                                                   parent-field
    +                                                   advance))))
             (when brand-new-field
               (goto-char real-match-end-0)
               (push (cons (1- real-match-end-0) real-match-end-0)

**Comment by joaotavora** [comment]
@npostavs, but the use back then used to be precisely that the field code would read the var on every run but only yas-next-field when it became t. I don't know if this has become broken in the meantime, or if it ever worked stably, but I do remember designing it with precisely this case in mind.

**Comment by npostavs** [comment]
Oh, I misunderstood what you were saying. Not sure it could have ever worked though, I see that the `save-excursion` in `yas--eval-lisp` was added in 2008; before your time, I think. e48806e04faf6c6c6e18c9b213815ba692acc367

**Comment by joaotavora** [comment]
I might have been doing some `post-command-hook` tomfoolery, which reminds me I think the cleanest thing here wold be a per field hook

**Comment by joaotavora** [comment]
> I think the cleanest thing here wold be a per field hook

Nonsense, the cleanest thing here would be a `yas-auto-next` macro hiding the implementation away. The user would wrap the `yas-choose-values` in it. As to the implementation, `post-command-hook` is probably not that bad for now.

**Comment by joaotavora** [comment]
@npostavs any objections to  6656964?

**Comment by npostavs** [comment]
Just a [minor comment](https://github.com/joaotavora/yasnippet/commit/6656964d714041fb380e6581095b4ec6445c115c#r29130220), but it looks good to me.
