### ISSUE TITLE
how to set expand key for a only a special snippet

### ISSUE THREAD

**Issue by huhuang03** [joaotavora/yasnippet#943]
I want set  expand key `enter` for just one snippet(don't effect others):
```
# -*- mode: snippet -*-
# name: comment
# key: /**
# --
/**
 * $0
 */
```
After read the doc, I still can't do this. Can you help me?

**Comment by npostavs** [comment]
I'm not sure I understand what "set expand key `enter`" means.

I guess you mean, that if you type `/**` and then hit <kbd>return</kbd> you want the `comment` snippet you've posted to be expanded, but <kbd>return</kbd> shouldn't expand any other snippet.

This is possible, but it's a bit complicated, and currently requires using an "internal" function.

```elisp
(defun yas-expand-ret-snippet ()
  (interactive)
  (let ((yas-buffer-local-condition
         '(quote (require-snippet-condition . on-ret))))
    (yas-expand)))

(defun yas-maybe-expand-ret-filter (cmd)
  (let ((yas-buffer-local-condition
         '(quote (require-snippet-condition . on-ret))))
    (yas--maybe-expand-key-filter cmd)))

(define-key yas-minor-mode-map (kbd "RET")
  '(menu-item "" yas-expand-ret-snippet
	      :filter yas-maybe-expand-ret-filter))
```

With a `#condition:` on the snippet:
```
# -*- mode: snippet -*-
# name: comment
# key: /**
# condition: (quote on-ret)
# --
/**
 * $0
 */
```

**Comment by huhuang03** [comment]
Yes! It's what I mean, sorry for my poor English! I will try and learn the config, thanks!

**Comment by npostavs** [comment]
Okay, I'm going to leave this open, since doing this requires the internal function `yas--maybe-expand-key-filter`, which means that yasnippet code should probably be adjusted to make this easier.
