### ISSUE TITLE
insert-in-front-hooks can't be called

### ISSUE THREAD

**Issue by chengyi** [joaotavora/yasnippet#944]
I use `company-irony-c-headers` for header file completion.
it use yasnippet for expand candidate.

when it expand `#include <|header>` which header is the overlay,
but when you type char before `header`, the overlay does not disappear.

By using edebug, i found the it seems `insert-in-front-hooks` doesn't be called.

is there any solution to this?

**Comment by npostavs** [comment]
Is this related to #588? I'm not sure I really follow what's going on from you description. Can you give precise instructions to reproduce it starting from `emacs -Q`?

As a wild guess, maybe `inhibit-modification-hooks` should be bound to `nil` somewhere?

**Comment by chengyi** [comment]
@npostavs yes, `inhibit-modification-hooks` is be bound to `nil`.

**Comment by npostavs** [comment]
Can you explain how to reproduce the problem please?
