### ISSUE TITLE
Is there any way to deal with a very long line in snippets?

### ISSUE THREAD

**Issue by yeonghoey** [joaotavora/yasnippet#945]
As starting to use `yas-choose-value`, it is really enjoyable using snippets.
However, the line containing `yas-choose-value` becomes really long.
I want to split that line into multiple lines in the snippet file for manageability while keeping the resulting string a single line.
I googled how to deal with this for hours, but I was not able to find anything.
Is there any way to do this?

**Comment by npostavs** [comment]
Newlines within lisp expressions have no effect:
```
# -*- mode: snippet -*-
# name: foo
# key: foo
# --
`(yas-choose-value "a"
                   "b"
                   "c")` ok
```

**Comment by yeonghoey** [comment]
Actually, I have more than three `(yas-choose-value)` on a line, and I wanted to place each `(yas-choose-value)` separately. If this is the only way to do this, the resulting snippet will look like following:

```
#+BEGIN_SRC $1 :results ${2:output$(
yas-choose-value '("output" "value"))} :exports ${3:both$(
yas-choose-value '("both" "code" "none"))}
$0
#+END_SRC
```
I tested, and I worked as expected.

However, it is complicated because of dangling problems.
What I really want to do is a kind of following(with an imaginary line break `\\`):

```
#+BEGIN_SRC $1 \\
:results ${2:output$(yas-choose-value '("output" "value"))} \\
:exports ${3:both$(yas-choose-value '("both" "code" "none"))}
$0
#+END_SRC
```

Note: I can't currently use `#+HEADER:` to separate org-babel header args to separated lines in this specific case, because I'm using Pandoc to export my org-document, and it seems that `Pandoc` does read options only on `#+BEGIN_SRC` line.

**Comment by npostavs** [comment]
You can sort of fake that with `` `nil` ``, that is, there is still "dangling", but it's confined to a dedicated token rather than the actual fields you are using:
```
#+BEGIN_SRC $1 `nil
`:results ${2:output$(yas-choose-value '("output" "value"))} `nil
`:exports ${3:both$(yas-choose-value '("both" "code" "none"))}
$0
#+END_SRC
```

**Comment by yeonghoey** [comment]
Thanks. it would be workable.

By the way, do you have any plans to support a feature like this? I know the escaping could make things complicated, but how might yasnippet provide another function like `(yas-lb)`:
```
#+BEGIN_SRC $1 `(yas-lb)`
:results ${2:output$(yas-choose-value '("output" "value"))} `(yas-lb)`
:exports ${3:both$(yas-choose-value '("both" "code" "none"))}
$0
#+END_SRC
```

**Comment by npostavs** [comment]
There is no function which could do it. We could add a syntax like your proposed `\\`, although I'm somewhat reluctant to make syntax changes.

**Comment by yeonghoey** [comment]
I understand. Anyway, thank you for your quick response, and the wonderful project 👍
