### ISSUE TITLE
yas-load-snippet-buffer doesn't respect users input

### ISSUE THREAD

**Issue by maximvl** [joaotavora/yasnippet#948]
Hi, I have some snippets in my `.emacs.d` directory and when I try to load them with `yas-load-snippet-buffer` it asks me for a table "Choose or enter a table" and I type `perl-mode` but it seems to be ignored and loaded for `.emacs.d`: 

```
[yas] Snippet "dbg" loaded for .emacs.d.
```

Expected: snippet is loaded for `perl-mode`.

**Comment by npostavs** [comment]
Can you describe in more detail exactly what files you created, and what actions you took? I tried creating a `~/.emacs.d/foo.snippet` with contents:
```
# name: foo
# key: foo
# --
this is foo
```
And then did `M-x yas-load-snippet-buffer`, answered `perl-mode` at the prompt and got the message

```
[yas] Snippet "foo" loaded for perl-mode.
```

----
PS you should create your perl snippets under `~/.emacs.d/snippets/perl-mode/`, if you want them to be loaded automatically for the correct mode.

**Comment by maximvl** [comment]
@npostavs You are right, I checked with raw emacs, it does work. I'll check with my other plugins, thanks!
