### ISSUE TITLE
Spurious match in clojure-mode keywords

### ISSUE THREAD

**Issue by vemv** [joaotavora/yasnippet#954]
Given a yasnippet called `t` which expands to `true`, if the cursor (`|`) is placed at the end of the keyword `:foo.t|`, then  `M-x yas-expand` will result in `:foo.true`.

Which doesn't make sense: in Clojure, `.` is just yet another character that can go inside a keyword. It doesn't delimit two different tokens/words.

Thanks - Victor

**Comment by vemv** [comment]
This fixed it https://github.com/joaotavora/yasnippet/issues/805#issuecomment-294510531

Perhaps worth adding it to the FAQ.

**Comment by jojojames** [comment]
Isn't that already in the key syntaxes?

```
(setq yas-key-syntaxes '("w_"))
```

**Comment by vemv** [comment]
The default is has more members than that, which was the confusing part

**Comment by npostavs** [comment]
Specifically, the problematic entry is `"w"` (currently the last one). It probably makes sense to remove it by default.

**Comment by npostavs** [comment]
I've updated the FAQ to mention this; I won't change the default `yas-key-syntaxes` for now.
