### ISSUE TITLE
Specify expansion predicate for subdirectory of snippets

### ISSUE THREAD

**Issue by nverno** [joaotavora/yasnippet#956]
Is it possible to specify a expansion condition that applies to
all the snippets in a subdirectory.  For example, I have  javadoc 
subdirectory where the condition clause is the same for all the snippets.
Is there a configuration available to just specify the condition once?

Thanks for the excellent work.

**Comment by npostavs** [comment]
No, the condition is independent of subdirectory. I would be hesitant to add such a feature, since it moves back in the direction of snippets depending on their filename/location (e.g., abbrev key based on filename, which is now deprecated).
