### ISSUE TITLE
Auto yas-expand Mode for Different Modes? [Custom Snippets Not Loading]

### ISSUE THREAD

**Issue by Dentrax** [joaotavora/yasnippet#963]
I just created a few snippets for go-mode. When I type `for` or `func` command and press <kbd>TAB</kbd> key, auto-expand mode won't works. I always have to enter these commands:

```
M-x yas-minor-mode
M-x yas-reload-all
```
I don't want to enter through these commands every time. Exactly what I request:

- When the `.go` file is opened, the snippets in the `go-mode` folder should be automatically load and be active. For other modes, snippets should be turned off automatically.

- When the `.py` file is opened, the snippets in the `python-mode` folder should be automatically load and be active. For other modes, snippets should be turned off automatically.

How can i do that? Thanks!

**Comment by npostavs** [comment]
What you are asking about should be standard behaviour, so I don't why it's not working for you. Please provide more detail on your setup, starting from `emacs -Q`.

**Comment by Dentrax** [comment]
I don't understand what should i do with `emacs -Q`

I got the snippet files from here: https://github.com/AndreaCrotti/yasnippet-snippets/tree/master/snippets

I'm calling the `yasanippet.el` file with the `.emacs` file as follows:

`(load "~/.emacs.d/custom.rc/yasnippet.el")`

My `yasnippet.el` file:

```
(rc/require 'yasnippet)

(require 'yasnippet)

(setq yas/triggers-in-field nil)
(setq yas-snippet-dirs '("~/.emacs.d/snippets/"))
(setq yas-indent-line (quote none))

(defconst yasnippet-snippets-dir
  (expand-file-name
   "~/.emacs.d/snippets/"
   (file-name-directory
    ;; Copied from ‘f-this-file’ from f.el.
    (cond
     (load-in-progress load-file-name)
     ((and (boundp 'byte-compile-current-file) byte-compile-current-file)
      byte-compile-current-file)
     (:else (buffer-file-name))))))

(defun yasnippet-snippets-initialize ()
  (add-to-list 'yas-snippet-dirs 'yasnippet-snippets-dir t)
  (yas-load-directory yasnippet-snippets-dir t))

(eval-after-load 'yasnippet
   '(yasnippet-snippets-initialize))

(provide 'yasnippet-snippets)

(yas-global-mode 1)
(yas-reload-all)

(global-set-key (kbd "<C-tab>") 'company-yasnippet)
(define-key yas-minor-mode-map (kbd "<tab>") 'yas-expand)
(define-key yas-minor-mode-map (kbd "TAB") 'yas-expand)
```

After that, when I start server Emacs with: `emacsclient -a '' -nqc "$@"`

Console output:

```
...
Loading /home/dentrax/.emacs.d/custom.rc/yasnippet.el (source)...
[yas] Prepared just-in-time loading of snippets successfully.
[yas] Prepared just-in-time loading of snippets successfully.
Loading /home/dentrax/.emacs.d/custom.rc/yasnippet.el (source)...done
...
```
Result:

yas-global-mode = on
yas-recompile-all
yas-reload-all

<kbd>Ctrl-x Ctrl-f</kbd> -> `~/test.cpp` or `~/test.c` or `~/test.go`
Write -> `main`, `if`, `switch`, etc...
Press <kbd>TAB</kbd> -> Not works

**Comment by npostavs** [comment]
Try `emacs -Q -L ~/.emacs.d/elpa/yasnippet-* -l yasnippet -f yas-global-mode  -L ~/.emacs.d/elpa/go-mode-* -f go-mode`, then type in `for` and hit <kbd>TAB</kbd>.

**Comment by Dentrax** [comment]
> Try `emacs -Q -L ~/.emacs.d/elpa/yasnippet-* -l yasnippet -f yas-global-mode -L ~/.emacs.d/elpa/go-mode-* -f go-mode`, then type in `for` and hit TAB.

Not works. The <kbd>TAB</kbd> key behave a normal 4-space.

**Comment by npostavs** [comment]
If you add `-l go-mode` before `-f go-mode` (I've edited the post accordingly) does it work?

**Comment by Dentrax** [comment]
> @npostavs 

Yes, it works when i type in `for` (Not works: `if`, `main`, etc. Only `for` works.)

Also, How can i setup that for C/C++ environment?

**Comment by npostavs** [comment]
> Thanks, it works when i type in `for` (Not works: `if`, `main`, etc. Only `for` works.)

It sounds like you don't have as many snippets as you think you do.

> Also, How can i setup that for C/C++ environment?

If you have a buffer in `c-mode`, then the snippets from the `~/.emacs.d/snippets/c-mode` will be enabled, likewise for `c++-code`.

**Comment by Dentrax** [comment]
@npostavs I don't know why but when i open simpe `test.cpp` file and when I type `for`, `if`, `main`, etc. That's not working.. I use it as I mentioned in my second comment.

**Comment by Dentrax** [comment]
> Can you show the output from running `M-x yas-describe-tables` in the `test.cpp` buffer?

Oh, now i understand.

`M-x yas-describe-tables` output for `test.cpp` buffer:

`YASnippet tables:`

It looks like null. But I don't understand why my c++-mode snippets not loading but c-mode loads.

`M-x yas-describe-tables` output for `test.c` buffer:

```
YASnippet tables:

Snippet table `c-mode'
----------------------------------------------------------------------------------------------------
group                   state name                                    key             binding
----------------------------------------------------------------------------------------------------
(top level)               (a) assert                                  ass
                          (a) compile                                 compile
                          (a) define                                  d
                          (a) malloc                                  malloc
                          (a) packed                                  packed
                          (a) printf                                  printf
                          (a) scanf                                   scanf
                          (a) stdio                                   io
                          (a) stdlib                                  std
                          (a) string                                  str
                          (a) struct ... { ... }                      struct
                          (a) ternary                                 ?
                          (a) union                                   union
                          (a) unistd                                  uni
----------------------------------------------------------------------------------------------------
doxygen                   (a) Function Doxygen Doc                    doxy

Snippet table `cc-mode'
----------------------------------------------------------------------------------------------------
group                   state name                                    key             binding
----------------------------------------------------------------------------------------------------
(top level)               (a) case : {...}                            case
                          (a) do { ... } while (...)                  do
                          (a) else { ... }                            else
                          (a) for                                     for
                          (a) for_n                                   forn
                          (a) if (...) { ... }                        if
                          (a) if (...) { ... } else { ... }           ife
                          (a) printf                                  printf
                          (a) struct ... { ... }                      struct
                          (a) switch (...) { case : ... default: .... switch
                          (a) ternary                                 ?
                          (a) while                                   while

Snippet table `c-lang-common'
----------------------------------------------------------------------------------------------------
group                   state name                                    key             binding
----------------------------------------------------------------------------------------------------
(top level)               (a) FILE *fp = fopen(..., ...);             fopen
                          (a) ifdef                                   ifdef
                          (a) math                                    math
                          (a) #include <...>                          incs
                          (a) #include "..."                          incl
                          (a) main                                    main
                          (a) #ifndef XXX; #define XXX; #endif        once
                          (a) typedef                                 typedef

```

Note: For my Go problem: Yes i have only 2 snippet. `if` and `func`

**Comment by npostavs** [comment]
Can you put this at the top of your init file, restart Emacs again, open a C++ file, and show the contents of `*trace-output*`?
```elisp
(dolist (fun '(yas-load-directory
               yas--load-directory-1
               yas--load-directory-2
               yas--load-snippet-dirs
               yas-reload-all
               yas--load-pending-jits))
  (trace-function fun))
```

**Comment by Dentrax** [comment]
@npostavs 

Output:

```
======================================================================
1 -> (yas-load-directory "/home/dentrax/.emacs.d/elpa/yasnippet-snippets-20181020.1423/snippets" t)
1 <- yas-load-directory: nil
======================================================================
1 -> (yas-load-directory "/home/dentrax/.emacs.d/elpa/yasnippet-snippets-20181020.1423/snippets" t)
1 <- yas-load-directory: nil
======================================================================
1 -> (yas-load-directory "/home/dentrax/.emacs.d/elpa/yasnippet-classic-snippets-1.0.2/snippets" t)
1 <- yas-load-directory: nil
======================================================================
1 -> (yas-load-directory "/home/dentrax/.emacs.d/snippets/" t)
1 <- yas-load-directory: nil
======================================================================
1 -> (yas--load-pending-jits)
1 <- yas--load-pending-jits: nil
======================================================================
1 -> (yas--load-pending-jits)
1 <- yas--load-pending-jits: nil
======================================================================
1 -> (yas--load-pending-jits)
1 <- yas--load-pending-jits: nil
======================================================================
1 -> (yas--load-pending-jits)
1 <- yas--load-pending-jits: nil
======================================================================
1 -> (yas--load-pending-jits)
1 <- yas--load-pending-jits: nil
======================================================================
1 -> (yas--load-pending-jits)
1 <- yas--load-pending-jits: nil
======================================================================
1 -> (yas--load-pending-jits)
1 <- yas--load-pending-jits: nil
======================================================================
1 -> (yas-reload-all)
| 2 -> (yas--load-snippet-dirs nil)
| | 3 -> (yas-load-directory "/home/dentrax/.emacs.d/snippets/" t)
| | 3 <- yas-load-directory: nil
| | 3 -> (yas-load-directory "~/.emacs.d/snippets/" t)
| | 3 <- yas-load-directory: nil
| 2 <- yas--load-snippet-dirs: nil
1 <- yas-reload-all: "[yas] Prepared just-in-time loading of snippets successfully."
======================================================================
1 -> (yas-reload-all)
| 2 -> (yas--load-snippet-dirs nil)
| | 3 -> (yas-load-directory "/home/dentrax/.emacs.d/snippets/" t)
| | 3 <- yas-load-directory: nil
| | 3 -> (yas-load-directory "~/.emacs.d/snippets/" t)
| | 3 <- yas-load-directory: nil
| 2 <- yas--load-snippet-dirs: nil
1 <- yas-reload-all: "[yas] Prepared just-in-time loading of snippets successfully."
======================================================================
1 -> (yas--load-pending-jits)
1 <- yas--load-pending-jits: nil
======================================================================
1 -> (yas--load-pending-jits)
1 <- yas--load-pending-jits: nil
======================================================================
1 -> (yas--load-pending-jits)
| 2 -> (yas--load-directory-1 "/home/dentrax/.emacs.d/snippets/c++-mode" c++-mode)
| 2 <- yas--load-directory-1: !non-local\ exit!
1 <- yas--load-pending-jits: !non-local\ exit!
======================================================================
1 -> (yas--load-pending-jits)
| 2 -> (yas--load-directory-1 "/home/dentrax/.emacs.d/snippets/c++-mode" c++-mode)
| 2 <- yas--load-directory-1: !non-local\ exit!
1 <- yas--load-pending-jits: !non-local\ exit!
```

**Comment by npostavs** [comment]
> ```
> 1 -> (yas--load-pending-jits)
> | 2 -> (yas--load-directory-1 "/home/dentrax/.emacs.d/snippets/c++-mode" c++-mode)
> | 2 <- yas--load-directory-1: !non-local\ exit!
> 1 <- yas--load-pending-jits: !non-local\ exit!
> ```

Ah, looks like some kind of error happens when loading. Do you see any error messages in `*Messages*`? I guess the problem might be in your `c++-mode/.yas-setup.el` file.

> Note: For my Go problem: Yes i have only 2 snippet. `if` and `func`

> ```
> drwxrwxrwx      - dentrax 24 Oct 12:12  ├── go-mode
> .rwxrwxrwx    442 dentrax 24 Oct 12:12  │  ├── .yas-compiled-snippets.el
> .rwxrwxrwx     67 dentrax 12 Oct 20:12  │  ├── for
> .rwxrwxrwx    107 dentrax 11 Oct 15:35  │  └── function
> ```

Since you have just those two snippets for `go-mode` it looks like it's working as expected. I would note that if you have `.yas-compiled-snippets.el` it is preferred over the individual snippet files, even if you add new ones.

**Comment by npostavs** [comment]
> My _Messages_ buffer currently like this:

That's your `*trace-output*` buffer, your `*Messages* buffer would not look like that. But I don't see anything indicating errors, so no need to post your `*Messages*` buffer.

> (Is there anything going wrong?)

Looks okay, though it seems you're loading yasnippet-snippets and yasnippet-classic-snippets before overriding them with your own snippets which is going to make your startup time slower than it needs to be.

**Comment by Dentrax** [comment]
I checked my *Messages* buffer, it looks like all things was loaded successfully. 

I just want to use my self-made snippets instead of classic ones. How can i override that snippets to increase my startup time?

**Comment by npostavs** [comment]
> I just want to use my self-made snippets instead of classic ones. How can i override that snippets to increase my startup time?

If you uninstall `yasnippet-snippets` and `yasnippet-classic-snippet` packages, you will have faster startup. And since you only want to use your own snippets those packages aren't helping you anyway.

**Comment by Dentrax** [comment]
I don't plan on removing them. Looks like everythings working fine now. Thanks! 🥇
