### ISSUE TITLE
fix #953 other problems caused

### ISSUE THREAD

**Issue by yydcnjjw** [joaotavora/yasnippet#964]
[company-lsp issues 64](https://github.com/tigersoldier/company-lsp/issues/62)

**Comment by npostavs** [comment]
Thanks for reporting this. Does the patch in #966 help? Is there a way to reproduce this without having an LSP server installed?

**Comment by yydcnjjw** [comment]
This patch is helpful.
The completion problem that occurs should be caused by ccls listening for the wrong text and then returning the wrong `textEdit` field.
So this problem may only happen in `company-lsp`
