### ISSUE TITLE
Getting stuck on Yasnippet mode and can't get out

### ISSUE THREAD

**Issue by mrbig033** [joaotavora/yasnippet#967]
+ GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.31) of 2018-08-16
+ yasnippet-20180621.50, Version: 20180621.50
+  evil-20180911.959, Version: 20180911.959
+ [init.el](https://gitlab.com/mrbig/emacs/blob/master/init.el)

I'm always get stuck after completing an expansion. I mapped `C-s` to `yas-expand` on `evil-insert-mode`. It triggers correctly, the problem is getting out of it. I stay in snippet mode until I use `C-s` again. `yas-reload-all` also to fix the issue.

**Comment by npostavs** [comment]
>     * init.el

That's a pretty long file, can you narrow it down a bit please?

**Comment by mrbig033** [comment]
Sure. I think these are all the relevant parts (notice that I have the problem with or without `advice-add 'company-complete-common`:

```
(use-package ivy-yasnippet
  :after yasnippet)

(use-package aggressive-indent
:defer t
:config
(setq aggressive-indent-sit-for-time 0.2))

(use-package yasnippet
  :defer t
  :ensure t
  :init
  (setq yas--default-user-snippets-dir "~/.emacs.d/etc/yasnippet")
  :config
  (setq yas-triggers-in-field nil)
  (yas-global-mode))

(use-package yasnippet-snippets
  :after yasnippet
  :config (yasnippet-snippets-initialize))


(advice-add 'company-complete-common :before (lambda () (setq my-company-point (point))))
(advice-add 'company-complete-common :after (lambda ()
  		  				(when (equal my-company-point (point))
  			  			  (yas-expand))))

(add-hook 'prog-mode-hook 'my-prog-hooks)

(defun my-prog-hooks ()
(electric-pair-local-mode 1)
(electric-operator-mode 1)
(subword-mode 1)
(company-mode 1)
(flycheck-mode 1)
(outline-minor-mode 1)
(rainbow-delimiters-mode 1)
(tab-jump-out-mode 1)
(show-smartparens-mode 1)
(smartparens-mode 1)
(aggressive-indent-mode 1)
(highlight-indent-guides-mode 1)
(line-numbers))

(imap :keymaps 'override
  "C-s" 'yas-expand)
```

**Comment by npostavs** [comment]
I don't see `evil` being configured there, does that mean you can trigger this without it?

> (notice that I have the problem with or without `advice-add 'company-complete-common`:

Then it's not relevant, please leave it out. What about `my-prog-hooks`? Are all of those relevant too?

> (imap :keymaps 'override "C-s" 'yas-expand)

Where is `imap` defined?
