### ISSUE TITLE
multi-line indent not work when expand with binding.

### ISSUE THREAD

**Issue by zw963** [joaotavora/yasnippet#968]
```rb
class TestClass
  def meth
    puts 'hello'
    puts 'world'
  end
end
```

first, i select two puts line, as following image:

![image](https://user-images.githubusercontent.com/549126/48978464-d4e93e00-f0e6-11e8-9542-c61ae109a487.png)

When i press l, what i expect is, wrapped code with a loop block (this defined by snippets):

```rb
class TestClass
  def meth
    loop do
      puts 'hello'
      puts 'world'
    end
  end
end
```

but, current version output is:

![image](https://user-images.githubusercontent.com/549126/48978456-bb47f680-f0e6-11e8-945f-ccb4021fcc95.png)

this can reproduce in builtin ruby-mode, with only yasnippet mode included.

```cl
# -*- mode: snippet -*-
# name: loop { ... }
# key: loop
# binding: l
# condition: (yas-use-region-p)
# --
loop do
  `(yas-selected-text)`$0
end
```

**Comment by zw963** [comment]
For more discuss, see https://github.com/joaotavora/yasnippet/issues/850#issuecomment-439612650

**Comment by zw963** [comment]
After update to 1d96da2, and set `yas-also-auto-indent-first-line` to `t`, it worked now, thanks.

**Comment by zw963** [comment]
Maybe we should set `yas-also-auto-indent-first-line` to `t` as default? thanks

**Comment by npostavs** [comment]
> Maybe we should set `yas-also-auto-indent-first-line` to `t` as default?

I'm pretty sure there were some cases where it gives bad results, and that's why it's not the default. Unfortunately, I can't remember what those cases are.

**Comment by zw963** [comment]
Thanks, i set this to `t` for a while, seem like just work.
