### ISSUE TITLE
yas-snippet-dirs has problems to resolve symbolic links without trailing '/'

### ISSUE THREAD

**Issue by DirkSchmitt** [joaotavora/yasnippet#971]
# Description #
If an entry in the list  yas-snippet-dirs points to a directory, which is a symbolic link to another directory, the content is loaded not at emacs startup. A manual reload of snippets is needed in this case.

I run in this problem because I use a symlink to a directory in an svn repository checkout.

## Environment ##
Debian with:
-  elpa-yasnippet   0.13.0-2       
- emacs25  25.1+1-4+deb9u1 

## Reproduce ##
1. Create symlink (`ln -s`) from `/tmp/demo` to a valid snippet directory.
2. In emacs startup, e.g. ~/.emacs:
    `(setq-default yas-snippet-dirs
              (list yas--default-user-snippets-dir "/tmp/demo"))

## Mitigation ##
Add a trailing slash solves the problem.
    `(setq-default yas-snippet-dirs
              (list yas--default-user-snippets-dir "/tmp/demo/"))

**Comment by npostavs** [comment]
>     2\. In emacs startup, e.g. ~/.emacs:
>         `(setq-default yas-snippet-dirs
>         (list yas--default-user-snippets-dir "/tmp/demo"))

Please give a full recipe, this doesn't show where/when you call `yas-global-mode` or `yas-minor-mode`.

**Comment by noctuid** [comment]
I can reproduce this as well but not with a minimal config. I did not have this problem until recently. I will post information on how to reproduce if I can figure out how to do so reliably.

**Comment by npostavs** [comment]
No news for many months, I'm going to ahead and close this.
