### ISSUE TITLE
yas-maybe-expand doesn't fallback in comment

### ISSUE THREAD

**Issue by whatacold** [joaotavora/yasnippet#973]
Hi,

`yas-maybe-expand` cannot fall back to do self insertion in comment with below recipe, which I think is a bug:

```
$ emacs --version
GNU Emacs 26.1
$ cd /tmp/
$ git clone https://github.com/joaotavora/yasnippet.git yasnippet-bug
$ cd yasnippet-bug
$ git log -1 --oneline
1d96da2 (HEAD -> reproduce-yas-maybe-expand, origin/master, master) Don't call before/after change-functions twice

$ emacs -Q -L . # then open reproduce.el and M-x eval-buffer
```

where `reproduce.el` contains:
```elisp
(require 'yasnippet)
(yas-global-mode 1)

(setq yas-buffer-local-condition yas-not-string-or-comment-condition)

(define-key yas-minor-mode-map (kbd "SPC") yas-maybe-expand)

					; hit SPC while point is right after `dolist` below, no SPACE is inserted
					; dolist
```

P.S. It works if I setup the obsolete fallback mechanism additionally with `(setq yas-fallback-behavior 'call-other-command)`

**Comment by npostavs** [comment]
It's because `yas-not-string-or-comment-condition` looks at `this-command` which is not set during the initial key-filter predicate. Easiest fix is to bind it (see #978), though it all feels a bit fragile...

**Comment by npostavs** [comment]
I'm thinkg about removing the `this-command` check from
`yas-not-string-or-comment-condition` instead.

I see it was added in 503e105b3eed4c4677b999de8612351676612568, but
there's no commentary about why.  @jaotavora, do you remember anything
about it?

**Comment by whatacold** [comment]
Thanks.

I'm sorry, but I still can reproduce it after updating to `master`, is it fixed on your side?

**Comment by npostavs** [comment]
Yes, it's working here. How are you testing? Is it possible you have a stale .elc file? What is the value of `yas-buffer-local-condition`?

**Comment by whatacold** [comment]
I tested it with the steps above when I first reported it.
I've confirmed that there is no .el and here are variables that you may be interested in:

    ELISP> yas-buffer-local-condition
    (if
        (let
    	((ppss
    	  (syntax-ppss)))
          (or
           (nth 3 ppss)
           (nth 4 ppss)))
        '(require-snippet-condition . force-in-comment)
      t)
    
    ELISP> yas-fallback-behavior
    return-nil

**Comment by npostavs** [comment]
Hmm, definitely working for me, and that `yas-buffer-local-condition` looks like it should be working for you too.

Can you try adding a trace before hitting SPC at the problem spot:
```elisp
(mapc 'trace-function '(yas-maybe-expand-abbrev-key-filter
			yas--templates-for-key-at-point
			yas--template-can-expand-p
			yas--require-template-specific-condition-p
			yas--templates-for-key-at-point))
```

**Comment by whatacold** [comment]
Sorry for late reply, the trace output is:

    ======================================================================
    1 -> (yas--templates-for-key-at-point)
    | 2 -> (yas--require-template-specific-condition-p)
    | 2 <- yas--require-template-specific-condition-p: force-in-comment
    | 2 -> (yas--template-can-expand-p nil force-in-comment)
    | 2 <- yas--template-can-expand-p: nil
    | 2 -> (yas--require-template-specific-condition-p)
    | 2 <- yas--require-template-specific-condition-p: force-in-comment
    | 2 -> (yas--template-can-expand-p nil force-in-comment)
    | 2 <- yas--template-can-expand-p: nil
    | 2 -> (yas--require-template-specific-condition-p)
    | 2 <- yas--require-template-specific-condition-p: force-in-comment
    | 2 -> (yas--template-can-expand-p nil force-in-comment)
    | 2 <- yas--template-can-expand-p: nil
    | 2 -> (yas--require-template-specific-condition-p)
    | 2 <- yas--require-template-specific-condition-p: force-in-comment
    | 2 -> (yas--template-can-expand-p nil force-in-comment)
    | 2 <- yas--template-can-expand-p: nil
    | 2 -> (yas--require-template-specific-condition-p)
    | 2 <- yas--require-template-specific-condition-p: force-in-comment
    | 2 -> (yas--template-can-expand-p nil force-in-comment)
    | 2 <- yas--template-can-expand-p: nil
    1 <- yas--templates-for-key-at-point: nil

**Comment by npostavs** [comment]
Hmm, my trace is almost the same, but yours misses the outer `(yas-maybe-expand-abbrev-key-filter yas-expand)` (see below). What do you get from `M-: (key-binding " ") RET` and `(lookup-key yas-minor-mode-map " ")`? (Should be `self-insert-command` and `nil` respectively).
```
1 -> (yas-maybe-expand-abbrev-key-filter yas-expand)
| 2 -> (yas--templates-for-key-at-point)
| | 3 -> (yas--require-template-specific-condition-p)
| | 3 <- yas--require-template-specific-condition-p: force-in-comment
| | 3 -> (yas--template-can-expand-p nil force-in-comment)
| | 3 <- yas--template-can-expand-p: nil
| | 3 -> (yas--require-template-specific-condition-p)
| | 3 <- yas--require-template-specific-condition-p: force-in-comment
| | 3 -> (yas--template-can-expand-p nil force-in-comment)
| | 3 <- yas--template-can-expand-p: nil
| | 3 -> (yas--require-template-specific-condition-p)
| | 3 <- yas--require-template-specific-condition-p: force-in-comment
| | 3 -> (yas--template-can-expand-p nil force-in-comment)
| | 3 <- yas--template-can-expand-p: nil
| | 3 -> (yas--require-template-specific-condition-p)
| | 3 <- yas--require-template-specific-condition-p: force-in-comment
| | 3 -> (yas--template-can-expand-p nil force-in-comment)
| | 3 <- yas--template-can-expand-p: nil
| | 3 -> (yas--require-template-specific-condition-p)
| | 3 <- yas--require-template-specific-condition-p: force-in-comment
| | 3 -> (yas--template-can-expand-p nil force-in-comment)
| | 3 <- yas--template-can-expand-p: nil
| 2 <- yas--templates-for-key-at-point: nil
1 <- yas-maybe-expand-abbrev-key-filter: nil
```

**Comment by whatacold** [comment]
Both of them eval to `yas-expand`, am I do something wrong?

**Comment by npostavs** [comment]
Hmm, something isn't making sense. What do you get from `M-: yas-maybe-expand RET`?

**Comment by whatacold** [comment]
I'm so sorry that I accidently `(define-key yas-minor-mode-map (kbd "SPC") 'yas-expand)` in my setup, which I haven't noticed before.
It works fine after removing it.

And thanks.

**Comment by npostavs** [comment]
Ah, right, that would explain everything then, thanks.
