### ISSUE TITLE
Yasnippet warn keyword at point has a snippet available

### ISSUE THREAD

**Issue by eubarbosa** [joaotavora/yasnippet#974]
Hi, 

Are there any variable to turn on so Yasnippet warns that keyword at point has a snippet available.

An echo warning would be neat! 

eg: 

- Point move to inside `p|rintf` 
-> Echo Message "Snippet available to keyword at point"  

- Point move out of `printf  |`

-> Echo Message disappear!  
 
I am aware that Yasnippet probe if there is a snippet to keyword before "expanding"...

Thanks !

**Comment by npostavs** [comment]
> Are there any variable to turn on so Yasnippet warns that keyword at point has a snippet available.

Not at this time. I guess you could implement it by adding a `post-command-hook` entry that uses `yas-maybe-expand-abbrev-key-filter`.

**Comment by eubarbosa** [comment]
oh, cool. Trying it for sure!
