### ISSUE TITLE
yas-define-snippets example

### ISSUE THREAD

**Issue by bumbker** [joaotavora/yasnippet#975]
please give an example for this:
the help info for (yas-define-snippets ) says
(yas-define-snippets MODE SNIPPETS)
Define SNIPPETS for MODE.
SNIPPETS is a list of snippet definitions, each taking the
following form
(KEY TEMPLATE NAME CONDITION GROUP EXPAND-ENV LOAD-FILE KEYBINDING UUID SAVE-FILE)
I cannot glean exactly how to write this
(yas-define-snippets 'emacs-lisp-mode ;;NOW WHAT?  - what's the syntax for SNIPPETS 
I want to make a long list of command style snippets to do what these would do.  Or to invoke these with no parenthesis, so to speak.  using a list structure instead of a file for each snippet.
(defun tnt () (insert "(number-to-string )") (backward-char 1))
(defun tpp () (insert "(buffer-name )") (backward-char 1))
(defun tmn () (insert "(buffer-file-name )") (backward-char 1))
(defun tgs () (insert "(current-buffer )") (backward-char 1)) ... etc.
If I could get an example to look at, that would help. Thank you for the good work.

**Comment by bumbker** [comment]
(yas-define-snippets MODE SNIPPETS)
Define SNIPPETS for MODE.
SNIPPETS is a list of snippet definitions, each taking the
following form
 (KEY TEMPLATE NAME CONDITION GROUP EXPAND-ENV LOAD-FILE KEYBINDING UUID SAVE-FILE)
I cannot glean exactly how to write this 
(yas-define-snippets 'emacs-lisp-mode ;;NOW WHAT? 
I want to make a long list of snippets such as
(defun tnt () (insert "(number-to-string )") (backward-char 1))
(defun tnn () (insert "(buffer-name )") (backward-char 1))
(defun tnm () (insert "(buffer-file-name )") (backward-char 1))
(defun tnf () (insert "(current-buffer )") (backward-char 1)) ... etc.
If I could get an example to look at, that would help.  Thank you for the good work.

**Comment by dericbytes** [comment]
```
(yas-define-snippets 'emacs-lisp-mode
'(("tpp"
  "(buffer-name $0)"
   "buffer-name leave cursor at first arg")))
```
Are you just wanting to create emacs-lisp-mode specific snippets? If so use

M-x yas-new-snippet in a buffer with emacs-lisp-mode active

```
# name: buffer-name leave cursor at first arg
# key: tpp
# --
(buffer-name $0)
```

Then C-c C-c to `yas-load-snippet-buffer-and-close'

**Comment by bumbker** [comment]
Thanks. I knew the second way already.  You're first answer was what I was looking for, so I can have a list instead of a file for each snippet.  Shouldn't the last line have been a comment though???
(yas-define-snippets 'emacs-lisp-mode
'(("tpp"
  "(buffer-name $0)")))
  ;;buffer-name leave cursor at first arg

**Comment by dericbytes** [comment]
See `M-x yas-define-snippets`.

```
 (KEY TEMPLATE NAME CONDITION GROUP EXPAND-ENV LOAD-FILE KEYBINDING UUID SAVE-FILE)
```
The third argument is an abitrary name you give to the snippet. 

It's helpful if you want to use the command.

`M-x  yas-visit-snippet-file RET
`

To search for a snippet and change it.

**Comment by npostavs** [comment]
> The third argument is an abitrary name you give to the snippet.
> 
> It's helpful if you want to use the command `M-x yas-visit-snippet-file RET TAB `

`LOAD-FILE` is more relevant for that. `NAME` is mainly for `M-x yas-insert-snippet`, and possibly if you insert snippets via company-mode or something.
