### ISSUE TITLE
Use snippet file name as key (snippet abbrev}?

### ISSUE THREAD

**Issue by QiangF** [joaotavora/yasnippet#977]
In all my snippet, the name of the snippet file is the same as the key name, is it possible to omit the key and name specification in the snippet file?

**Comment by QiangF** [comment]
One example here:
https://github.com/hlissner/emacs-snippets/blob/master/org-mode/elisp
The snippet file is named elisp, and the key has the same value, it's unnecessary to specify the name twice.

**Comment by npostavs** [comment]
> In all my snippet, the name of the snippet file is the same as the key name, is it possible to omit the key and name specification in the snippet file?

No, omitting the key gives you an abbrev-less snippet, which you could still expand with `yas-insert-snippet`, or with a keybinding.
