### ISSUE TITLE
Disable global minor mode by default in hidden buffers

### ISSUE THREAD

**Issue by memeplex** [joaotavora/yasnippet#985]
Many major modes internally use hidden buffers (those starting with a space, as described [here](https://www.gnu.org/software/emacs/manual/html_node/ido/Hidden-Buffers-and-Files.html)). Some modes use these buffers to font lock blocks of code using some major mode (for example, both python.el and org mode do that). When yasnippet is enabled in this kind of buffers bad things might happen  while programatically inserting contents. In particular, I've seen the jit font locker complaining about args out of range when yas-mode was enabled. This kind of errors are really difficult to trace and I see no point in enabling snippets in buffers where nobody will type anything, anyway. Could you add something like `(lambda () (string-prefix-p " " (buffer-name)))` by default to `yas-dont-activate-functions` in order to play well with major modes?

**Comment by npostavs** [comment]
With org-mode there might still be some extra complications because there is some non-working code that attempts to transfer the snippet overlays into the temp buffer. So I'm not entirely sure what's going to happen there, but not enabling `yas-minor-mode` in temp buffers makes sense anyway.

**Comment by memeplex** [comment]
Thanks, Noam!
