### ISSUE TITLE
Filter hook for all commands in yas-keymap?

### ISSUE THREAD

**Issue by dgutov** [joaotavora/yasnippet#987]
It would be helpful if there was a hook that we could add predicates to, to determine whether any bindings from this keymap should be active at a given moment.

This should help solve the big remaining problem we have in company-mode WRT key bindings, namely that `TAB` binding for `company-complete-common` cannot work when point is inside a snippet field. The only other approach  for fixing this (AFAIK) is to company-mode to transition to setting the current keymap via overlays as well, which will mean again futzing around with adding/removing newlines, because point must be strictly inside an overlay (and it can't happen when point is at eob).

This comment gave me the idea: https://github.com/company-mode/company-mode/issues/881#issuecomment-477757558

**Comment by dgutov** [comment]
> a hook that we could add predicates to

A predicate variable (with a non-nil default value) should work as well, though.

**Comment by npostavs** [comment]
> The only other approach for fixing this (AFAIK) is to company-mode
> to transition to setting the current keymap via overlays as well,
> which will mean again futzing around with adding/removing newlines, [...]

Yeah, that makes sense.  I see that there was already
`yas-overlay-priority` which mentions `company-mode` in its docstring,
but definitely avoiding overlays is generally better if possible.

Does the code in #993 look like what you had in mind?

**Comment by dgutov** [comment]
It does, thank you! And it's working fine in my quick tests.

Hopefully it doesn't look like too much extra complexity on your side. I was thinking of other options as well (like collecting/saving/removing/restoring the keymap property on all overlays near point in pre- and post- command hooks), but none seem particularly attractive.

Regarding `yas-overlay-priority`, maybe it helped with `auto-complete`. `company-mode`, however, never assigned key bindings through overlays.

**Comment by npostavs** [comment]
> I hope it doesn't look like too much extra complexity on your side. I was thinking of other options as well (like collecting/saving/removing/restoring the keymap property on all overlays near point in pre- and post- command hooks), but none seem particularly attractive.

Yeah, that sounds fragile. I seem to recall @joaotavora made a suggestion at some point about changing yasnippet to use a "snippet expansion" minor mode to activate the keymap, instead of overlays, but that would be a much bigger change, and who knows how many configs it would break.

> Regarding `yas-overlay-priority`, maybe it helped with `auto-complete`. `company-mode`, however, never assigned key bindings through overlays.

Yes. In fact I was the one who added that variable (I had totally forgotten about it), and it was indeed for `auto-complete` (#828), though the problem was sort of the inverse of this one: `auto-complete` uses overlays with a very high priority. Not sure why I had put `company` in the docstring.

**Comment by dgutov** [comment]
> suggestion at some point about changing yasnippet to use a "snippet expansion" minor mode to activate the keymap, instead of overlays

Hmm, I kind of figured you're using this approach because some other code (a subfeature of Org, probably) also assigns the keymap through overlays. Just like with that `<tab>`/`TAB` annoyance.

Overlays are a pretty nice abstraction for this, actually. Especially when one doesn't have to consider interaction with other packages.

> though the problem was sort of the inverse of this one: auto-complete uses overlays with a very high priority

Right, and you for some reason wanted to disable it inside the template fields. Not sure I understand that feature request, to be honest. Here, I want the reverse: to use the full features of code completion even when I'm filling out a template.

**Comment by dgutov** [comment]
Thanks Noam!

I have now pushed the corresponding change to company-mode. Waiting for inevitable feedback from people who are too used to the current behavior. :)
