### ISSUE TITLE
How to expand automatically in inline math ($...$) or enviroments but not elsewhere

### ISSUE THREAD

**Issue by maikol-solis** [joaotavora/yasnippet#990]
I have the following snippet in latex-mode

```
# -*- mode: snippet -*-
# name: Parenthesis
# binding: ()
# key: ()
# --
\left($1\right)
```

I will like expand the snippet everytime that type `()` in math-mode (between dolars and math enviroments), but not elsewhere. 

For example if I type 

```
The parenthesis are $()$
```

I would like to get expanded to 

```
The parenthesis are $\left(<CURSOR HERE>\right)$
```

The same behavior should happen in any math enviroment `equation`, `align`, etc. 

But, if I write 

```
The parenthesis are ()
```

They remain without expansion. 

Thanks for any help.

**Comment by Zetagon** [comment]
Have a look at the section "The condition system" in the documentation: http://joaotavora.github.io/yasnippet/snippet-expansion.html . It does a similar thing but for python comments.

The function `texmathp` returns `t` if inside a math expression and `nil` if not.

**Comment by npostavs** [comment]
Thanks @Zetagon, couldn't have said it better myself.
