### ISSUE TITLE
Whitespace char is replaced with tab char after commit of completion(of company-mode)

### ISSUE THREAD

**Issue by netjune** [joaotavora/yasnippet#995]
Here is a screen record video to produce the bug.  http://121.43.160.118:3080/upload/yasnippet_bug.mp4

Reproduce steps:
1. emacs -Q
2. install these packages from melpa: yasnippet, company-mode, go-mode
3. open the test go file, and set `company-backends` to '(company-dabbrev-code)`
4. turn on company-mode and yas-minor-mode
5. do as in the screen record video

the snippet `ap`:
```
# name: append(slice, elt)
# key: ap
# --
${1:slice} = append($1, ${2:elem})
```

**Comment by npostavs** [comment]
Thanks, I think #997 should fix this. (direct link to fixed code: https://raw.githubusercontent.com/npostavs/yasnippet/indent-later/yasnippet.el)

**Comment by netjune** [comment]
Thanks for your confirmation. It works here.
